```{r, message=FALSE, warning=FALSE}
library(dplyr)
library(ggplot2)
surv_dat <- gfplot::get_survey_sets("pacific cod", ssid = c(1, 3))
# d <- readRDS("~/src/gfsynopsis/report/data-cache3/pacific-cod.rds")
# surv_dat <- filter(d$survey_sets, survey_abbrev %in% c("SYN QCS", "SYN HS"))
```

```{r}
calc_bio <- function(dat, i = seq_len(nrow(dat))) {
  dat[i, , drop = FALSE] %>%
    group_by(year, survey_id, area_km2, grouping_code) %>%
    summarise(density = mean(density_kgpm2*1e6)) %>%
    group_by(year) %>%
    summarise(biomass = sum(density * area_km2)) %>%
    pull(biomass)
}

boot_biomass <- function(dat, reps = 100) {
  out <- dat %>%
    group_by(year) %>%
    do({
      b <- boot::boot(., statistic = calc_bio, strata = .$grouping_code, R = reps)
      suppressWarnings(bci <- boot::boot.ci(b, type = "perc"))
      tibble::tibble(
        mean_boot = mean(b$t),
        median_boot = median(b$t),
        lwr = bci$percent[[4]],
        upr = bci$percent[[5]],
        cv = sd(b$t)/mean(b$t),
        biomass = calc_bio(.))
    })
}
```

```{r, message=FALSE, warning=FALSE}
out <- boot_biomass(surv_dat, 1000)
```

```{r}
ggplot(out, aes(year, biomass)) +
  geom_ribbon(aes(ymin = lwr, ymax = upr), alpha = 0.3) +
  geom_line() + geom_point() +
  ylim(0, NA) +
  guides(fill = FALSE) +
  gfplot::theme_pbs()
saveRDS(out, "data/qcs-hs-survey-index.rds")
```

