\clearpage

# FIGURES

## Area 5ABCD


```{r fig-sens15-biomass-5abcd, fig.cap="Biomass."}
b.plot(c(base.model.5abcd, sens.models.15), c(base.model.5abcd.name, sens.models.name.15))
```

```{r fig-sens15-biomass-3cd, fig.cap="Biomass."}
b.plot(c(base.model.3cd, sens.models.16), c(base.model.3cd.name, sens.models.name.16))
```




```{r fig-catch-5abcd, fig.cap="Catch for Area 5ABCD"}
make.catches.plot(catch.5)
```

```{r fig-base-mcmc-trace-5abcd, fig.cap="Traceplots of posterior samples for the Area 5ABCD base reference model. $\\bar{R} = R_{Avg}$, $q_1$ = Hecate Strait Assemblage survey, $q_2$ = Queen Charlotte Sound Synoptic Survey, $q_3$ = Hecate Strait Synoptic Survey, $q_4$ = Commercial CPUE pre-1996, and $q_5$ = Commercial CPUE post-1995."}
make.traces.plot(base.model.5abcd)
```

```{r fig-base-mcmc-priors-5abcd, fig.cap="Prior probability distributions used in the Area 5ABCD base reference model. $\\bar{R} = R_{Avg}$, $q_1$ = Hecate Strait Assemblage survey, $q_2$ = Queen Charlotte Sound Synoptic Survey, $q_3$ = Hecate Strait Synoptic Survey, $q_4$ = Commercial CPUE pre-1996, and $q_5$ = Commercial CPUE post-1995."}
make.priors.posts.plot(base.model.5abcd)
```

```{r fig-base-mcmc-priors-posts-5abcd, fig.cap="Histograms of posterior samples with prior probability distributions (lines) used in the Area 5ABCD base reference model. $\\bar{R} = R_{Avg}$, $q_1$ = Hecate Strait Assemblage survey, $q_2$ = Queen Charlotte Sound Synoptic Survey, $q_3$ = Hecate Strait Synoptic Survey, $q_4$ = Commercial CPUE pre-1996, and $q_5$ = Commercial CPUE post-1995."}
make.priors.posts.plot(base.model.5abcd, priors.only = FALSE)
```

```{r fig-base-mcmc-autocor-5abcd, fig.cap="Autocorrelation plots for the Area 5ABCD base reference model. $\\bar{R} = R_{Avg}$, $q_1$ = Hecate Strait Assemblage survey, $q_2$ = Queen Charlotte Sound Synoptic Survey, $q_3$ = Hecate Strait Synoptic Survey, $q_4$ = Commercial CPUE pre-1996, and $q_5$ = Commercial CPUE post-1995."}
make.autocor.plot(base.model.5abcd)
```

```{r fig-base-mcmc-pairs-5abcd, fig.cap="Pairs plots of posterior samples for the Area 5ABCD base reference model. $\\bar{R} = R_{Avg}$, $q_1$ = Hecate Strait Assemblage survey, $q_2$ = Queen Charlotte Sound Synoptic Survey, $q_3$ = Hecate Strait Synoptic Survey, $q_4$ = Commercial CPUE pre-1996, and $q_5$ = Commercial CPUE post-1995."}
make.pairs.plot(base.model.5abcd)
```

```{r fig-base-index-fits-5abcd, fig.cap="MPD fits to observed indices of abundance (points) for the Area 5ABCD base reference model from: (a) the Hecate Strait Assemblage survey, (b) the Queen Charlotte Sound Synoptic Survey, (c) the Hecate Strait Synoptic Survey, (d) the Commercial CPUE pre-1996, and (e) the Commercial CPUE post-1995."}
plot_grid(i.plot(base.model.5abcd, base.model.5abcd.name, 1, every = 5),
          i.plot(base.model.5abcd, base.model.5abcd.name, 2, every = 5),
          i.plot(base.model.5abcd, base.model.5abcd.name, 3, every = 5),
          i.plot(base.model.5abcd, base.model.5abcd.name, 4, every = 10),
          i.plot(base.model.5abcd, base.model.5abcd.name, 5, every = 5),
          nrow = 2,
          ncol = 3,
          labels = c("(a)", "(b)", "(c)", "(d)", "(e)"),
          label_x = 0.2)
```


```{r fig-base-biomass-5abcd, fig.cap="Biomass for the Reference Model, Area 5ABCD.  The green dashed line shows the Upper Stock Reference (USR) which is the mean biomass estimate for the years 1956--2004. The red dashed line shows the Limit Reference Point (LRP) which is the lowest biomass from which the stock has recovered, in this case it is the biomass estimate for 1971."}
b.plot(base.model.5abcd,
       base.model.5abcd.name,
       depl = FALSE,
       add.hist.ref = TRUE,
       lrp = c(1971, 1971),
       usr = c(1956, 2004))
```

```{r fig-base-depl-5abcd, fig.cap="Relative biomass for the Reference Model, Area 5ABCD."}
b.plot(base.model.5abcd,
       base.model.5abcd.name,
       depl = TRUE)
```

```{r fig-base-f-5abcd, fig.cap="Fishing mortality for the Reference Model, Area 5ABCD."}
f.plot(base.model.5abcd,
       base.model.5abcd.name)
```

```{r fig-base-recr-5abcd, fig.cap="Recruitment (a) and recruitment deviations (b) for the Reference Model, Area 5ABCD.  The green dashed line shows the mean of the MCMC posterior medians, the blue dashed line shows the median of the MCMC posterior medians."}
plot_grid(r.plot(base.model.5abcd,
                 base.model.5abcd.name,
                 add.meds = TRUE,
                 x.axis.angle = 90),
          r.devs.plot(base.model.5abcd,
                      base.model.5abcd.name,
                      x.axis.angle = 90),
          nrow = 1,
          ncol = 2,
          labels = c("(a)", "(b)"),
          label_x = c(0.15, 0.1))
```

```{r fig-base-retro-biomass-5abcd, fig.cap="Retrospective biomass for the Reference Model, Area 5ABCD."}
b.plot.mpd(c(base.model.5abcd, base.retro.models.5abcd),
           c(base.model.5abcd.name, retro.names),
           depl = FALSE)
```

```{r fig-sens1-biomass-5abcd, fig.cap="Biomass for the Sensitivity to removing the year/locality interaction term from the commercial CPUE indices and using the annual CVs resulting from the analysis as the annual weighting terms in the objective function for two CV options, and to removal of the CPUE indices, Area 5ABCD."}
b.plot(c(base.model.5abcd, sens.models.1), c(base.model.5abcd.name, sens.models.name.1))
```

```{r fig-sens1-recr-5abcd, fig.cap="Recruitment for the Sensitivity to removing the year/locality interaction term from the commercial CPUE indices and using the annual CVs resulting from the analysis as the annual weighting terms in the objective function for two CV options, Area 5ABCD."}
r.plot(c(base.model.5abcd, sens.models.1.sub),
       c(base.model.5abcd.name, sens.models.name.1.sub))
```

```{r fig-sens1-depletion-5abcd, fig.cap="Relative biomass for the Sensitivity to removing the year/locality interaction term from the commercial CPUE indices and using the annual CVs resulting from the analysis as the annual weighting terms in the objective function for two CV options, and to removal of the CPUE indices, Area 5ABCD."}
b.plot(c(base.model.5abcd, sens.models.1), c(base.model.5abcd.name, sens.models.name.1), depl = TRUE)
```

```{r fig-sens1-f-5abcd, fig.cap="Fishing mortality for the Sensitivity to removing the year/locality interaction term from the commercial CPUE indices and using the annual CVs resulting from the analysis as the annual weighting terms in the objective function for two CV options, and to removal of the CPUE indices, Area 5ABCD."}
f.plot(c(base.model.5abcd, sens.models.1), c(base.model.5abcd.name, sens.models.name.1))
```

```{r fig-sens2-biomass-5abcd, fig.cap="Biomass for the Sensitivity to the mean of the catchability, $q$, being set equal for the QCS and HSS surveys, and to a uniform prior being used for both surveys, Area 5ABCD."}
b.plot(c(base.model.5abcd, sens.models.2), c(base.model.5abcd.name, sens.models.name.2))
```
```{r fig-sens2-recr-5abcd, fig.cap="Recruitment for the Sensitivity to the mean of the catchability, $q$, being set equal for the QCS and HSS surveys, and to a uniform prior being used for both surveys, Area 5ABCD."}
r.plot(c(base.model.5abcd, sens.models.2), c(base.model.5abcd.name, sens.models.name.2))
```

```{r fig-sens2-depl-5abcd, fig.cap="Relative biomass for the Sensitivity to the mean of the catchability, $q$, being set equal for the QCS and HSS surveys, and to a uniform prior being used for both surveys, Area 5ABCD."}
b.plot(c(base.model.5abcd, sens.models.2), c(base.model.5abcd.name,
sens.models.name.2), depl = TRUE)
```

```{r fig-sens2-f-5abcd, fig.cap="Fishing mortality for the Sensitivity to the mean of the catchability, $q$, being set equal for the QCS and HSS surveys, and to a uniform prior being used for both surveys, Area 5ABCD."}
f.plot(c(base.model.5abcd, sens.models.2), c(base.model.5abcd.name, sens.models.name.2))
```

```{r fig-sens3-biomass-5abcd, fig.cap="Biomass for the Sensitivity to the parameters on the normal prior for natural mortality, M, Area 5ABCD."}
b.plot(c(base.model.5abcd, sens.models.3), c(base.model.5abcd.name, sens.models.name.3))
```

```{r fig-sens3-recr-5abcd, fig.cap="Recruitment for the Sensitivity to the parameters on the normal prior for natural mortality, M, Area 5ABCD."}
r.plot(c(base.model.5abcd, sens.models.3), c(base.model.5abcd.name, sens.models.name.3))
```

```{r fig-sens3-depl-5abcd, fig.cap="Relative biomass for the Sensitivity to the parameters on the normal prior for natural mortality, M, Area 5ABCD."}
b.plot(c(base.model.5abcd, sens.models.3), c(base.model.5abcd.name,
sens.models.name.3), depl = TRUE)
```

```{r fig-sens3-f-5abcd, fig.cap="Fishing mortality for the Sensitivity to the parameters on the normal prior for natural mortality, M, Area 5ABCD."}
f.plot(c(base.model.5abcd, sens.models.3), c(base.model.5abcd.name, sens.models.name.3))
```

```{r fig-sens4-biomass-5abcd, fig.cap="Biomass for the Sensitivity to the prior probability distribution for steepness, including using a bounded uniform prior and a beta prior, Area 5ABCD."}
b.plot(c(base.model.5abcd, sens.models.4), c(base.model.5abcd.name, sens.models.name.4))
```

```{r fig-sens4-recr-5abcd, fig.cap="Recruitment for the Sensitivity to the prior probability distribution for steepness, including using a bounded uniform prior and a beta prior, Area 5ABCD."}
r.plot(c(base.model.5abcd, sens.models.4), c(base.model.5abcd.name, sens.models.name.4))
```

```{r fig-sens4-depl-5abcd, fig.cap="Relative biomass for the Sensitivity to the prior probability distribution for steepness, including using a bounded uniform prior and a beta prior, Area 5ABCD."}
b.plot(c(base.model.5abcd, sens.models.4), c(base.model.5abcd.name,
sens.models.name.4), depl = TRUE)
```

```{r fig-sens4-f-5abcd, fig.cap="Fishing mortality for the Sensitivity to the prior probability distribution for steepness, including using a bounded uniform prior and a beta prior, Area 5ABCD."}
f.plot(c(base.model.5abcd, sens.models.4), c(base.model.5abcd.name, sens.models.name.4))
```

```{r fig-sens5-biomass-5abcd, fig.cap="Biomass for the Sensitivity to setting $k_{age} = 3y$ and update the Ford-Walford parameters accordingly, and to using the growth parameters used in the previous stock assessment, Area 5ABCD."}
b.plot(c(base.model.5abcd, sens.models.5), c(base.model.5abcd.name, sens.models.name.5))
```

```{r fig-sens5-recr-5abcd, fig.cap="Recruitment for the Sensitivity to setting $k_{age} = 3y$ and update the Ford-Walford parameters accordingly, and to using the growth parameters used in the previous stock assessment, Area 5ABCD."}
r.plot(c(base.model.5abcd, sens.models.5), c(base.model.5abcd.name, sens.models.name.5))
```

```{r fig-sens5-depl-5abcd, fig.cap="Relative biomass for the Sensitivity to setting $k_{age} = 3y$ and update the Ford-Walford parameters accordingly, and to using the growth parameters used in the previous stock assessment, Area 5ABCD."}
b.plot(c(base.model.5abcd, sens.models.5), c(base.model.5abcd.name,
sens.models.name.5), depl = TRUE)
```

```{r fig-sens5-f-5abcd, fig.cap="Fishing mortality for the Sensitivity to setting $k_{age} = 3y$ and update the Ford-Walford parameters accordingly, and to using the growth parameters used in the previous stock assessment, Area 5ABCD."}
f.plot(c(base.model.5abcd, sens.models.5), c(base.model.5abcd.name, sens.models.name.5))
```

```{r fig-sens6-biomass-5abcd, fig.cap="Biomass for the Sensitivity to the assumed value of observation and process errors, Area 5ABCD."}
b.plot(c(base.model.5abcd, sens.models.6), c(base.model.5abcd.name, sens.models.name.6))
```

```{r fig-sens6-recr-5abcd, fig.cap="Recruitment for the Sensitivity to the assumed value of observation and process errors, Area 5ABCD."}
r.plot(c(base.model.5abcd, sens.models.6), c(base.model.5abcd.name, sens.models.name.6))
```

```{r fig-sens6-depl-5abcd, fig.cap="Relative biomass for the Sensitivity to the assumed value of observation and process errors, Area 5ABCD."}
b.plot(c(base.model.5abcd, sens.models.6), c(base.model.5abcd.name,
sens.models.name.6), depl = TRUE)
```

```{r fig-sens6-f-5abcd, fig.cap="Fishing mortality for the Sensitivity to the assumed value of observation and process errors, Area 5ABCD."}
f.plot(c(base.model.5abcd, sens.models.6), c(base.model.5abcd.name, sens.models.name.6))
```

```{r fig-sens6-index-hsmas-5abcd, fig.cap="Index fit for the Sensitivity to the assumed value of observation and process errors, HSMAS, Area 5ABCD."}
i.plot(c(base.model.5abcd, sens.models.6), c(base.model.5abcd.name, sens.models.name.6), ind = 1)
```

```{r fig-sens6-index-qcss-5abcd, fig.cap="Index fit for the Sensitivity to the assumed value of observation and process errors, QCSS, Area 5ABCD."}
i.plot(c(base.model.5abcd, sens.models.6), c(base.model.5abcd.name, sens.models.name.6), ind = 2)
```

```{r fig-sens6-index-hsss-5abcd, fig.cap="Index fit for the Sensitivity to the assumed value of observation and process errors, HSSS, Area 5ABCD."}
i.plot(c(base.model.5abcd, sens.models.6), c(base.model.5abcd.name, sens.models.name.6), ind = 3)
```

```{r fig-sens6-index-cpue-pre1996-5abcd, fig.cap="Index fit for the Sensitivity to the assumed value of observation and process errors, commercial CPUE pre-1996, Area 5ABCD."}
i.plot(c(base.model.5abcd, sens.models.6), c(base.model.5abcd.name, sens.models.name.6), ind = 4, every = 5)
```

```{r fig-sens6-index-cpue-post1995-5abcd, fig.cap="Index fit for the Sensitivity to the assumed value of observation and process errors, commercial CPUE post-1995, Area 5ABCD."}
i.plot(c(base.model.5abcd, sens.models.6), c(base.model.5abcd.name, sens.models.name.6), ind = 5, leg.loc = "topleft")
```

```{r fig-sens7-biomass-5abcd, fig.cap="Biomass for the Sensitivity to the assumed value of $\\sigma_{W}$, Area 5ABCD."}
b.plot(c(base.model.5abcd, sens.models.7), c(base.model.5abcd.name, sens.models.name.7))
```

```{r fig-sens7-recr-5abcd, fig.cap="Recruitment for the Sensitivity to the assumed value of $\\sigma_{W}$, Area 5ABCD."}
r.plot(c(base.model.5abcd, sens.models.7), c(base.model.5abcd.name, sens.models.name.7))
```

```{r fig-sens7-depl-5abcd, fig.cap="Relative biomass for the Sensitivity to the assumed value of $\\sigma_{W}$, Area 5ABCD."}
b.plot(c(base.model.5abcd, sens.models.7), c(base.model.5abcd.name,
sens.models.name.7), depl = TRUE)
```

```{r fig-sens7-f-5abcd, fig.cap="Fishing mortality for the Sensitivity to the assumed value of $\\sigma_{W}$, Area 5ABCD."}
f.plot(c(base.model.5abcd, sens.models.7), c(base.model.5abcd.name, sens.models.name.7))
```

\clearpage

## Area 3CD

```{r fig-catch-3cd, fig.cap="Catch for Area 3CD"}
make.catches.plot(catch.3)
```

```{r fig-base-mcmc-trace-3cd, fig.cap="Traceplots of posterior samples for the Area 3CD base reference model. $\\bar{R} = R_{Avg}$, $q_1$ = West Coast Vancouver Island Synoptic Survey, $q_2$ = Commercial CPUE pre-1996, $q_3$ = Commercial CPUE post-1995, and $q_3$ = NMFS Triennial Survey (Canadian portion)."}
make.traces.plot(base.model.3cd)
```

```{r fig-base-mcmc-priors-3cd, fig.cap="Prior probability distributions used in the Area 3CD base reference model. $\\bar{R} = R_{Avg}$, $q_1$ = West Coast Vancouver Island Synoptic Survey, $q_2$ = Commercial CPUE pre-1996, $q_3$ = Commercial CPUE post-1995, and $q_3$ = NMFS Triennial Survey (Canadian portion)."}
make.priors.posts.plot(base.model.3cd)
```

```{r fig-base-mcmc-priors-posts-3cd, fig.cap="Histograms of posterior samples with prior probability distributions (lines) used in the Area 3CD base reference model. $\\bar{R} = R_{Avg}$, $q_1$ = West Coast Vancouver Island Synoptic Survey, $q_2$ = Commercial CPUE pre-1996, $q_3$ = Commercial CPUE post-1995, and $q_3$ = NMFS Triennial Survey (Canadian portion)."}
make.priors.posts.plot(base.model.3cd, priors.only = FALSE)
```

```{r fig-base-mcmc-autocor-3cd, fig.cap="Autocorrelation plots for the Area 3CD base reference model. $\\bar{R} = R_{Avg}$, $q_1$ = West Coast Vancouver Island Synoptic Survey, $q_2$ = Commercial CPUE pre-1996, $q_3$ = Commercial CPUE post-1995, and $q_3$ = NMFS Triennial Survey (Canadian portion)."}
make.autocor.plot(base.model.3cd)
```

```{r fig-base-mcmc-pairs-3cd, fig.cap="Pairs plots of posterior samples for the Area 3CD base reference model. $\\bar{R} = R_{Avg}$, $q_1$ = West Coast Vancouver Island Synoptic Survey, $q_2$ = Commercial CPUE pre-1996, $q_3$ = Commercial CPUE post-1995, and $q_3$ = NMFS Triennial Survey (Canadian portion)."}
make.pairs.plot(base.model.3cd)
```

```{r fig-base-index-fits-3cd, fig.cap="MPD fits to observed indices of abundance (points) for the Area 3CD base reference model from: (a) the West Coast Vancouver Island Synoptic Survey, (b) the Commercial CPUE pre-1996, (c) the Commercial CPUE post-1995, and (d) the NMFS Triennial Survey (Canadian portion)."}
plot_grid(i.plot(base.model.3cd, base.model.3cd.name, 1, every = 5),
          i.plot(base.model.3cd, base.model.3cd.name, 2, every = 5),
          i.plot(base.model.3cd, base.model.3cd.name, 3, every = 5),
          i.plot(base.model.3cd, base.model.3cd.name, 4, every = 5),
          nrow = 2,
          ncol = 2,
          labels = c("(a)", "(b)", "(c)", "(d)"),
          label_x = c(0.15, 0.13, 0.13, 0.2))
```

```{r fig-base-biomass-3cd, fig.cap="Biomass for the Reference Model, Area 3CD."}
b.plot(base.model.3cd, base.model.3cd.name)
```

```{r fig-base-depl-3cd, fig.cap="Relative biomass for the Reference Model, Area 3CD."}
b.plot(base.model.3cd,
       base.model.3cd.name,
       depl = TRUE)
```

```{r fig-base-f-3cd, fig.cap="Fishing mortality for the Reference Model, Area 3CD."}
f.plot(base.model.3cd,
       base.model.3cd.name)
```

```{r fig-base-recr-3cd, fig.cap="Recruitment (a) and recruitment deviations (b) for the Reference Model, Area 3CD.  The green dashed line shows the mean of the MCMC posterior medians, the blue dashed line shows the median of the MCMC posterior medians."}
plot_grid(r.plot(base.model.3cd, base.model.3cd.name, add.meds = TRUE, x.axis.angle = 90),
          r.devs.plot(base.model.3cd, base.model.3cd.name, x.axis.angle = 90),
          nrow = 1,
          ncol = 2,
          labels = c("(a)", "(b)"),
          label_x = c(0.17, 0.1))
```

```{r fig-base-retro-biomass-3cd, fig.cap="Retrospective biomass for the Reference Model, Area 3CD."}
b.plot.mpd(c(base.model.3cd, base.retro.models.3cd),
           c(base.model.3cd.name, retro.names),
           depl = FALSE)
```

```{r fig-sens8-biomass-3cd, fig.cap="Biomass for the Sensitivity to removing the year/locality interaction term from the commercial CPUE indices and using the annual CVs resulting from the analysis as the annual weighting terms in the objective function for two CV options, to removal of the CPUE indices, and to the removal of the Triennial survey index, Area 3CD."}
b.plot(c(base.model.3cd, sens.models.8), c(base.model.3cd.name, sens.models.name.8))
```

```{r fig-sens8-recr-3cd, fig.cap="Recruitment for the Sensitivity to removing the year/locality interaction term from the commercial CPUE indices and using the annual CVs resulting from the analysis as the annual weighting terms in the objective function for two CV options, Area 3CD."}
r.plot(c(base.model.3cd, sens.models.8.sub),
       c(base.model.3cd.name, sens.models.name.8.sub))
```

```{r fig-sens9-biomass-3cd, fig.cap="Biomass for the Sensitivity to the SD for the WCVIS survey being set equal to the SD for the QCS and HSS surveys, and to a uniform prior being used for the WCVIS survey, Area 3CD."}
b.plot(c(base.model.3cd, sens.models.2), c(base.model.3cd.name, sens.models.name.2))
```

```{r fig-sens9-recr-3cd, fig.cap="Recruitment for the Sensitivity to the SD for the WCVIS survey being set equal to the SD for the QCS and HSS surveys, and to a uniform prior being used for the WCVIS survey, Area 3CD."}
r.plot(c(base.model.3cd, sens.models.2), c(base.model.3cd.name, sens.models.name.2))
```

```{r fig-sens9-depl-3cd, fig.cap="Relative biomass for the Sensitivity to the SD for the WCVIS survey being set equal to the SD for the QCS and HSS surveys, and to a uniform prior being used for the WCVIS survey, Area 3CD."}
b.plot(c(base.model.3cd, sens.models.2), c(base.model.3cd.name,
sens.models.name.2), depl = TRUE)
```

```{r fig-sens9-f-3cd, fig.cap="Fishing mortality for the Sensitivity to the SD for the WCVIS survey being set equal to the SD for the QCS and HSS surveys, and to a uniform prior being used for the WCVIS survey, Area 3CD."}
f.plot(c(base.model.3cd, sens.models.2), c(base.model.3cd.name, sens.models.name.2))
```

```{r fig-sens10-biomass-3cd, fig.cap="Biomass for the Sensitivity to the parameters on the normal prior for natural mortality, M, Area 3CD."}
b.plot(c(base.model.3cd, sens.models.10), c(base.model.3cd.name, sens.models.name.10))
```

```{r fig-sens10-recr-3cd, fig.cap="Recruitment for the Sensitivity to the parameters on the normal prior for natural mortality, M, Area 3CD."}
r.plot(c(base.model.3cd, sens.models.10), c(base.model.3cd.name, sens.models.name.10))
```

```{r fig-sens10-depl-3cd, fig.cap="Relative biomass for the Sensitivity to the parameters on the normal prior for natural mortality, M, Area 3CD."}
b.plot(c(base.model.3cd, sens.models.10), c(base.model.3cd.name,
sens.models.name.10), depl = TRUE)
```

```{r fig-sens10-f-3cd, fig.cap="Fishing mortality for the Sensitivity to the parameters on the normal prior for natural mortality, M, Area 3CD."}
f.plot(c(base.model.3cd, sens.models.10), c(base.model.3cd.name, sens.models.name.10))
```

```{r fig-sens11-biomass-3cd, fig.cap="Biomass for the Sensitivity to the prior probability distribution for steepness, including using a bounded uniform prior and a beta prior, Area 3CD."}
b.plot(c(base.model.3cd, sens.models.11), c(base.model.3cd.name, sens.models.name.11))
```

```{r fig-sens11-recr-3cd, fig.cap="Recruitment for the Sensitivity to the prior probability distribution for steepness, including using a bounded uniform prior and a beta prior, Area 3CD."}
r.plot(c(base.model.3cd, sens.models.11), c(base.model.3cd.name, sens.models.name.11))
```

```{r fig-sens11-depl-3cd, fig.cap="Relative biomass for the Sensitivity to the prior probability distribution for steepness, including using a bounded uniform prior and a beta prior, Area 3CD."}
b.plot(c(base.model.3cd, sens.models.11), c(base.model.3cd.name,
sens.models.name.11), depl = TRUE)
```

```{r fig-sens11-f-3cd, fig.cap="Fishing mortality for the Sensitivity to the prior probability distribution for steepness, including using a bounded uniform prior and a beta prior, Area 3CD."}
f.plot(c(base.model.3cd, sens.models.11), c(base.model.3cd.name, sens.models.name.11))
```

```{r fig-sens12-biomass-3cd, fig.cap="Biomass for the Sensitivity to setting $k_{age} = 3y$ and update the Ford-Walford parameters accordingly, and to using the growth parameters used in the previous stock assessment, Area 3CD."}
b.plot(c(base.model.3cd, sens.models.12), c(base.model.3cd.name, sens.models.name.12))
```

```{r fig-sens12-recr-3cd, fig.cap="Recruitment for the Sensitivity to setting $k_{age} = 3y$ and update the Ford-Walford parameters accordingly, and to using the growth parameters used in the previous stock assessment, Area 3CD."}
r.plot(c(base.model.3cd, sens.models.12), c(base.model.3cd.name, sens.models.name.12))
```

```{r fig-sens12-depl-3cd, fig.cap="Relative biomass for the Sensitivity to setting $k_{age} = 3y$ and update the Ford-Walford parameters accordingly, and to using the growth parameters used in the previous stock assessment, Area 3CD."}
b.plot(c(base.model.3cd, sens.models.12), c(base.model.3cd.name,
sens.models.name.12), depl = TRUE)
```

```{r fig-sens12-f-3cd, fig.cap="Fishing mortality for the Sensitivity to setting $k_{age} = 3y$ and update the Ford-Walford parameters accordingly, and to using the growth parameters used in the previous stock assessment, Area 3CD."}
f.plot(c(base.model.3cd, sens.models.12), c(base.model.3cd.name, sens.models.name.12))
```

```{r fig-sens13-biomass-3cd, fig.cap="Biomass for the Sensitivity to the assumed value of observation and process errors, Area 3CD."}
b.plot(c(base.model.3cd, sens.models.13), c(base.model.3cd.name, sens.models.name.13))
```

```{r fig-sens13-recr-3cd, fig.cap="Recruitment for the Sensitivity to the assumed value of observation and process errors, Area 3CD."}
r.plot(c(base.model.3cd, sens.models.13), c(base.model.3cd.name, sens.models.name.13))
```

```{r fig-sens13-depl-3cd, fig.cap="Relative biomass for the Sensitivity to the assumed value of observation and process errors, Area 3CD."}
b.plot(c(base.model.3cd, sens.models.13), c(base.model.3cd.name,
sens.models.name.13), depl = TRUE)
```

```{r fig-sens13-f-3cd, fig.cap="Fishing mortality for the Sensitivity to the assumed value of observation and process errors, Area 3CD."}
f.plot(c(base.model.3cd, sens.models.13), c(base.model.3cd.name, sens.models.name.13))
```

```{r fig-sens13-index-wcviss-3cd, fig.cap="Index fit for the Sensitivity to the assumed value of observation and process errors, WCVISS, Area 3CD."}
i.plot(c(base.model.3cd, sens.models.13), c(base.model.3cd.name, sens.models.name.13), ind = 1, leg.loc = "topleft")
```

```{r fig-sens13-index-cpue-pre1996-3cd, fig.cap="Index fit for the Sensitivity to the assumed value of observation and process errows, commercial CPUE pre-1996, Area 3CD."}
i.plot(c(base.model.3cd, sens.models.13), c(base.model.3cd.name, sens.models.name.13), ind = 2, every = 5)
```

```{r fig-sens13-index-cpue-post1995-3cd, fig.cap="Index fit for the Sensitivity to the assumed value of observation and process errors, commercial CPUE post-1995, Area 3CD."}
i.plot(c(base.model.3cd, sens.models.13), c(base.model.3cd.name, sens.models.name.13), ind = 3, leg.loc = "topleft")
```

```{r fig-sens13-index-triennial-3cd, fig.cap="Index fit for the Sensitivity to the assumed value of observation and process errors, NMFS Triennial survey, Area 3CD."}
i.plot(c(base.model.3cd, sens.models.13), c(base.model.3cd.name, sens.models.name.13), ind = 4)
```

```{r fig-sens14-biomass-3cd, fig.cap="Biomass for the Sensitivity to the assumed value of $\\sigma_{W}$, Area 3CD."}
b.plot(c(base.model.3cd, sens.models.14), c(base.model.3cd.name, sens.models.name.14))
```

```{r fig-sens14-recr-3cd, fig.cap="Recruitment for the Sensitivity to the assumed value of $\\sigma_{W}$, Area 3CD."}
r.plot(c(base.model.3cd, sens.models.14), c(base.model.3cd.name, sens.models.name.14))
```

```{r fig-sens14-depl-3cd, fig.cap="Relative biomass for the Sensitivity to the assumed value of $\\sigma_{W}$, Area 3CD."}
b.plot(c(base.model.3cd, sens.models.14), c(base.model.3cd.name,
sens.models.name.14), depl = TRUE)
```

```{r fig-sens14-f-3cd, fig.cap="Fishing mortality for the Sensitivity to the assumed value of $\\sigma_{W}$, Area 3CD."}
f.plot(c(base.model.3cd, sens.models.14), c(base.model.3cd.name, sens.models.name.14))
```
