\clearpage

# DELAY-DIFFERENCE MODEL

The last assessment for Pacific Cod for Areas 5AB and 5CD used a delay-difference model [@forrest2013]. A delay-difference model is essentially a collapsed age-structured model, subject to certain assumptions
age-structured models. The delay-difference structure tracks the effects of recruitment, survival and growth on biomass, without requiring a fully age-structured framework. Difference equations, which allow for a time-delay between spawning and recruitment, are used to build the population model in discrete annual time-steps, in which the surviving biomass for next year is predicted from the surviving biomass from last year, afte adjusting for growth and adding recruitment. An advantage of delay-difference models over simpler production models is that they do not assume constant recruitment over time.

The key assumptions of the delay-difference model are:

- Growth in mean body weight Wa follows the linear relationship described by the
  Ford-Walford equation, $W_a = \alpha_g + \rho W_{a-1}$, where $W_a$ is derived from the von Bertalanffy growth parameters;
- Knife edge selectivity, where all fish aged $k$ and older are equally
  vulnerable to the fishing gear, and knife-edged maturity at age $k$; and
- Constant mortality $M$ at age.

The delay-difference model collapses all the equations needed to fully describe the population's age structure into equations for the total numbers ($N_t$) and biomass ($B_t$) at time $t$:

\begin{equation}
  B_t = S_{t-1}(\alpha_g N_{t-1} + \rho_g B_{t-1}) + w_k R_t
  (\#eq:ddbiomass)
\end{equation}

and

\begin{equation}
  N_t = S_{t-1} N_{t-1} + R_t
  (\#eq:ddnumbers)
\end{equation}

where $S$ is survival, given by

\begin{equation}
  S_t = e^{-(M + F_t)}
  (\#eq:ddsurvival)
\end{equation}

where $M$ is natural mortality rate; $F$ is the estimated instantaneous fishing mortality rate; $\alpha_g$ and $\rho_g$ are the intercept and slope of the Ford-Walford equation, for all ages > $k$, where $k$ is the age at which fish are assumed to become fully vulnerable to fishing; $w_k$ is the weight at $k$; and $R_t$ is the assumed stock-recruit function, here constrained to conform to a Beverton-Holt function with $a$ and $b$ the constants of this equation (Eq. \@ref(eq:ddrt)). For both 5ABCD and 3CD stocks, it is assumed that recruitment to the fishery, survey and spawning stock occurs at age 2 y (i.e., $k$ = 2 *y*), as assumed by @sinclair2001, @sinclair2005 and @forrest2013.

A list of model parameters is given in Table \@ref(tab:tab-param-list). Equilibrium and dynamic equations are given in Sections \@ref(summary-of-equilibrium-equations-for-the-delay-difference-model) and \@ref(time-dynamic-equations-and-likelihood-components-for-the-delay-difference-model). Variance parameters and components of the objective function are given in are given in Section \@ref(time-dynamic-equations-and-likelihood-components-for-the-delay-difference-model). Leading estimated
parameters are shown in bold type in Table \@ref(tab:tab-param-list). Fixed parameter values
and prior probability distributions are given in the description of the Reference Case models (Section \@ref(reference-case-models)).

To avoid the assumption that the stocks were at equilibrium in 1956, @forrest2013 used the same approach as an age-structured model for initializing numbers in the first year. The same approach was used here (Eq. \@ref(eq:ddn1)).

From 1956-2017, bias-corrected annual recruitments were estimated as the product of an estimated average unfished recruitment ($R_{0}$, estimated in log space) and bias-corrected annual log recruitment deviations ($\omega_t$), which were weakly constrained to a normal distribution with $\omega_t \sim \mathcal{N}(0,2^2)$.  $\ln(R_{0})$ and an estimated vector of eight years of log deviates (age 3--age 10; $\omega_{t\_init}$),  was used to fill the first year of the numbers-at-age matrix, with natural mortality used to calculate survival Eq. \@ref(eq:ddn1). The number of fish in the first year was then calculated as the sum of numbers at age in the first year Eq. \@ref(eq:ddnt). For the years 1957-2013, annual numbers of fish ($N_t$) were calculated using (Eq. \@ref(eq:ddnt)). Biomass in the first year was calculated as the sum over ages of the product of numbers-at-age and the weight-at-age (Eq. \@ref(eq:ddbt)), with the latter derived from the von Bertlanffy growth parameters (Table \@ref(tab:tab-param-list)). Delay-difference equations were used to calculate annual biomass ($B_t$) for the years 1957-2014 (Eq. \@ref(eq:ddbt)), with recruitment given by Eq. \@ref(eq:ddrt). Log recruitment anomalies in the 2018 projection year were drawn from a normal distribution, $\omega_t \sim \mathcal{N}(0,\sigma_R^2)$.

## CONDITIONING THE MODEL
Models were fit to observed catch data, observed mean weight data and fishery-independent and -dependent indices of abundance.

## OBJECTIVE FUNCTION COMPONENTS

The objective function in the delay-difference model contained five major components:

- the negative log-likelihood for the relative abundance data;
- the negative log-likelihood for the catch data;
- the negative log-likelihood for the mean weight data;
- the prior distributions for model parameters;
- three penalty functions that:

>  i. constrain the estimates of annual recruitment to conform to
>  a Beverton-Holt stock-recruit function (Eq. \@ref(eq:ddrt));

>  ii. weakly constrain the log recruitment deviations to a normal distribution
>  ($\sim \mathcal{N}(0,2^2)$);

>  iii. very weakly constrain estimates of log fishing mortality to a normal
>  distribution ($\sim \mathcal{N}(\ln(0.2), 4.0^2)$), to prevent estimates of
>  catch from exceeding estimated biomass.

Tests showed the model was insensitive to changes in the penalty function parameters, indicating that the other likelihood components and prior probability distributions were the most important contributors to the
objective function.

## INDICES OF ABUNDANCE

The fishery-independent and -dependent abundance indices (Appendices \@ref(fishery-independent-indices-of-abundance) and \@ref(commercial-cpue-standardization)) were treated as relative abundance indices, assumed to be directly proportional to the biomass with lognormal errors. The survey scaling (catchability) parameter $q_j$ for each survey $j$ was treated as an uncertain parameter, with the conditional maximum posterior density (MPD) estimate of $q_j$ used in the objective function (Eq. \@ref(eq:ddljt), where the parameter $j_z$ represents the maximum likelihood estimate of $\ln(j_q)$, conditional on other model parameters, with $n_j$ the number of observations in index $j$ [@walters1994; Eqs. \@ref(eq:ddzjt)--\@ref(eq:dddjt)].

## CATCH DATA

The model was conditioned on total catch, with annual log fishing mortality rates for the bottom trawl fishery estimated directly. Estimated fishing mortality rates ($F_t$) were then used to predict catch using the Baranov catch equation (Eq. \@ref(eq:ddzjt)). Log residuals (Eq. \@ref(eq:dddct)) were assumed to be normally distributed with fixed standard deviation $\sigma_C$ (Eq. \@ref(eq:ddclt)).

### MEAN WEIGHT

Predicted annual mean weight ($\hat{\bar{W}}_t$) was calculated using Eq. \@ref(eq:ddwt). Log residuals (Eq. \@ref(eq:dddwt)) were assumed to be normally distributed with fixed standard deviation $\sigma_W$ (Eq. \@ref(eq:ddwlt)).

## RECRUITMENT

Bias-corrected annual recruitment (Eq. \@ref(eq:ddrt)) was estimated as the product of estimated mean unfished recruitment ($R_{0}$) and estimated annual deviations ($\omega_t$), with both parameters estimated in log space. Predicted recruits ($\hat{R}_t$) were assumed to come from Beverton-Holt stock-recruit function. Log recruitment residuals (Eq. \@ref(eq:dddrt)) were assumed to be normally distributed with standard deviation $\sigma_R$ (Eq. \@ref(eq:ddrlt)).

@sinclair2005 included an environmental correlate into the stock-recruit relationship, linking recruitment anomalies to Prince Rupert Sea Level anomalies (after @sinclair2005-2). @sinclair2005 reported that the effect of including the environmental correlate made very little difference to estimates of biomass. Unpublished analyses by the authors of the current assessment suggested that model estimates of biomass and recruitment were most strongly influenced by catch and commercial annual mean weight data; and that
incorporating a parameter relating the stock-recruit function to an updated time series of air pressure adjusted Prince Rupert sea level data (@forrest2013, their Figure 55) simply resulted in a shift in estimated recruitment anomalies, resulting in almost identical estimates of biomass and recruits. For this reason, the current assessment does not incorporate the Prince Rupert sea level data for Area 5ABCD.

## VARIANCE COMPONENTS AND WEIGHTING OF INDEX DATA

Variance components of the delay-difference model implemented within the iScam modelling framework [@martell2011] were partitioned using an errors in variables approach. The key variance parameter is the inverse of the total variance $\phi^{-2}$ (i.e., total precision). This parameter can be fixed or
estimated, and was fixed here. The total variance is partitioned into observation and process error components by the model parameter $\rho$, which represents the proportion of the total variance that is due to observation error [@punt1993; @deriso2007].

The equation for the observation error component of the total variance ($\sigma_O$) is given in Eq. \@ref(eq:ddsigo), while the process error term, $\sigma_R$ is given in Eq. \@ref(eq:ddsigo). The process error term ($\sigma_R$) enters the objective function in the log likelihood function for the recruitment residuals (Eq. \@ref(eq:ddrlt)). In cases when the index of abundance data are informative about absolute abundance (e.g.,an acoustic survey), one or both of these parameters, $\phi^{-2}$ and $\rho$, may be estimable. In practice, however, one or both of these parameters usually must be fixed.

The overall observation error term $\sigma_O$ influences the fit to all indices of abundance through its contribution to $\sigma_{j,t}$, the standard deviation of log observation residuals for each index $j$ in survey year $t$ in the log-likelihood function (Eq. \@ref(eq:ddljt)). For a theoretical assessment with only one index of abundance with equally weighted observations, $\sigma_{j,t}$ would be equal to $\sigma_O$ for all observations. Commonly, however, there are multiple surveys available. Within a given survey, annual coefficients of variation ($CV_{j,t}$) for each observation may also differ from year to year, due to annual sampling differences (e.g., sample size, spatial effects, etc.). It is therefore desirable to weight each observation according to its $CV_{j,t}$,where a low $CV_{j,t}$ for a given observation gives it a higher weight (and lower standard deviation in the objective function). This is implemented multiplicatively using Eqs. \@ref(eq:ddsigjt) and \@ref(eq:ddcjt), where the $c_{j,t}$ term allows each observation to be weighted relative to the total observation error $\sigma_O$. In this case, $c_{j,t}$ is simply obtained from the inverse of $CV_{j,t}$ (Eq. \@ref(eq:ddcjt)). For consistency with the use of an overall observation error term applied to all indices of abundance, the vector of $c_{j,t}$ terms was normalized across all surveys by dividing by the mean value of $c_{j,t}$. This had the effect
weighting each survey observation consistently across all three datasets.

For the fishery-independent survey indices, annual coefficients of variation ($CV_{j,t}$) were derived from
bootstrapping the swept area estimates (Appendix \@ref(fishery-independent-indices-of-abundance)). For the commercial CPUE indices, annual coefficients of variation were derived from the GLMMs used to produce the indices (Appendix \@ref(commercial-cpue-standardization)).

A number of authors have noted that there is little consensus on the best approach to managing the relative weighting of multiple survey indices, and that there is always a degree of subjectivity in the choice of weighting strategy (e.g., @francis2011, @mcallister2001). In particular, there is no objective means of deciding how well a model should fit to commercial CPUE data, given that there is no independent means of knowing the degree to which commercial CPUE data are proportional to the underlying biomass. Commercial
fisheries do not sample populations randomly; catchability and selectivity are unlikely to be constant through time; and spatial effects can impact the underlying relationship between CPUE and abundance [@hilborn1992]. Surveys are assumed to be proportional to abundance by virtue of survey design, however
this assumption too can be vulnerable to various effects.

@francis2011 reviewed some approaches to weighting abundance indices in fisheries stock assessment and advised against subjective down-weighting of commercial CPUE data. He described a two-stage approach to weighting some or all of the datasets with the intention of making data weights more consistent
with model output, i.e., satisfying a statistical fit criterion. He proposed a survey-specific weighting term, set so that the standard deviation of normalized Pearson residuals (SDNR) for each index of abundance dataset is equal to about 1.0 [@francis2011].

In the current assessment, adopting an iterative re-weighting approach similar to that reported in @francis2011 would necessitate introducing a third, survey-specific weighting term to the calculation of $\sigma_{j,t}$. That is, $\sigma_{j,t}$ would be composed of $\sigma_O$, $c_{j,t}$, and a survey-specific weighting term $w_j$ that would bring SDNR close to 1.0 @francis2011. Given that both $\sigma_O$ and the commercial CPUE $CV_{j,t}$ terms were already fixed at subjectively-determined values, and that
$c_{j,t}$ was already normalized across surveys, it seemed an unwarranted addition to introduce another fixed weighting term. @francis2011 stated that the overall goal is a stock assessment that fits all indices of abundance well, and that the SDNR provides a means of judging whether that is the case. However, expert judgment can also be employed [@mcallister2001]. We present sensitivity analyses to the values of fixed variance parameters (Section \@ref(sensitivity-analyses)) and suggest that an understanding of the impact of fixed variance assumptions on management advice for Pacific Cod can be obtained without an iterative re-weighting step.

\clearpage

```{r tab-param-list, fig.pos="H"}
model.param.desc.table(cap = paste0("List of parameters for the delay-difference model.",
                                    "Estimated (or fixed) leading parameters are highlighted ",
                                    "in bold type."))
```

\clearpage

## SUMMARY OF EQUILIBRIUM EQUATIONS FOR THE DELAY-DIFFERENCE MODEL

**Equilibrium equations for calculation of stock-recruit parameters**

Equilibrium unfished survival:

\begin{equation}
{S_0} = {e^{ - M}}
(\#eq:ddso)
\end{equation}

Equilibrium unfished mean weight:

\begin{equation}
{\bar w_0} = \frac{{{S_0}{\alpha _g} + {w_k}\left( {1 - {S_0}} \right)}}{{1 - {\rho _g}{S_0}}}
(\#eq:ddwo)
\end{equation}

Equilibrium unfished numbers:

\begin{equation}
{N_0} = \frac{{{R_0}}}{{\left( {1 - {S_0}} \right)}}
(\#eq:ddno)
\end{equation}

Equilibrium unfished biomass:

\begin{equation}
{B_0} = {N_0}{\bar w_0}
(\#eq:ddbo)
\end{equation}

Recruitment compensation ratio (Beverton-Holt):

\begin{equation}
{\rm{CR}} = \frac{{4h}}{{1 - h}}
(\#eq:ddcr)
\end{equation}

Parameters of the stock-recruit relationship (Beverton-Holt):

\begin{equation}
b = \frac{{{\rm{CR}} - 1}}{{\,{B_0}}}
(\#eq:ddbeta)
\end{equation}

**Equilibrium equations for fishery reference points**

Equilibrium survival rate at fixed long-term fishing mortality $F_e$:

\begin{equation}
{S_e} = {e^{ - \left( {M + {F_e}} \right)}}
(\#eq:ddse)
\end{equation}

Equilibrium long-term mean weight at $F_e$:

\begin{equation}
{\bar w_e} = \frac{{{S_e}{\alpha _g} + {w_k}\left( {1 - {S_e}} \right)}}{{1 - {\rho _g}{S_e}}}
(\#eq:ddwe)
\end{equation}

Equilibrium long-term biomass at $F_e$:

\begin{equation}
{B_e} =  - \frac{{\left( {{\rm{ - }}{{{\rm{\bar W}}}_e}{\rm{  +  }}{{\rm{S}}_e}{\alpha _g}{\rm{  +  }}{{\rm{S}}_e}{\rho _g}{{{\rm{\bar W}}}_e} + {W_k}a{{{\rm{\bar W}}}_e}} \right)}}{{b\left( {{\rm{ - }}{{{\rm{\bar W}}}_e}{\rm{  +  }}{{\rm{S}}_e}{\alpha _g}{\rm{  +  }}{{\rm{S}}_e}{\rho _g}{{{\rm{\bar W}}}_e}} \right)}}
(\#eq:ddbe)
\end{equation}

Equilibrium long-term yield at $F_e$:

\begin{equation}
{Y_e} = {B_e}\frac{{{F_e}}}{{\left( {{F_e} + M} \right)}}\left( {1 - {e^{ - \left( {{F_e} + M} \right)}}} \right)
(\#eq:ddye)
\end{equation}

\clearpage

## TIME-DYNAMIC EQUATIONS AND LIKELIHOOD COMPONENTS FOR THE DELAY-DIFFERENCE MODEL

**Time-dynamic equations**

Survival rate:

\begin{equation}
{S_t} = e^{-(M{ + F_t)}}
(\#eq:ddst)
\end{equation}

Initial numbers at age calculations:

\begin{equation}
\left\{ \begin{array}{l}{N_{2,1}} = {R_{0}}{e^{{\omega _1}}}\quad \quad \quad \quad \quad \quad \quad \quad a = 2\\{N_{a,1}} = \left( {{R_{0}}{e^{\omega Ini{t_a}}}} \right){e^{ - M\left( {a - 2} \right)}} \quad 2 < a < A\\{N_{A,1}} = \frac{{\left( {{R_{0}}{e^{\omega Ini{t_A}}}} \right){e^{ - M\left( {A - 2} \right)}}}}{{\left( {1 - {e^{ - M}}} \right)}}\quad \quad a = A\end{array} \right\}
(\#eq:ddn1)
\end{equation}

Numbers:

\begin{equation}
\left\{ \begin{array}{l}{N_t} = \sum\limits_{i = 2}^A {{N_{a,1}}} \quad \quad \quad t = 1956\\{N_t} = {S_{t - 1}}{N_{t - 1}} + {R_t}\quad t > 1956\end{array} \right\}
(\#eq:ddnt)
\end{equation}

Biomass:

\begin{equation}
\left\{ \begin{array}{l}{B_t} = \sum\limits_{a = 2}^A {{N_{a,t}}{w_{a,t}}} \quad t = 1956\\{B_t} = {S_{t - 1}}\left( {{\alpha _g}{\rm{ }}{N_{t - 1}} + {\rho _g}{B_{t - 1}}} \right){\rm{ }} + {W_k}{R_t}\quad t > 1956\end{array} \right\}
(\#eq:ddbt)
\end{equation}

Recruits:

\begin{equation}
{R_t} = {R_{0}}{e^{{\omega _t} - \frac{{\sigma _R^2}}{2}}}
(\#eq:ddrt)
\end{equation}

**Predicted variables used in objective function**

Predicted catch:

\begin{equation}
{\hat C_t} = {B_t}\frac{{{F_t}}}{{\left( {{F_t} + M} \right)}}\left( {1 - {e^{ - \left( {{F_t} + M} \right)}}} \right)
(\#eq:ddct)
\end{equation}

Predicted mean weight:

\begin{equation}
{\hat{\bar{W_t}}} = \frac{{{B_t}}}{{{N_t}}}
(\#eq:ddwt)
\end{equation}

Predicted recruits:

\begin{equation}
{\rm{ }}{\hat R_{\rm{t}}} = {\rm{ }}\frac{{a{B_{{\rm{t - k}} + {\rm{1}}}}}}{{1 + b{B_{{\rm{t - k}} + {\rm{1}}}}}}
(\#eq:ddrt)
\end{equation}

## CALCULATION OF VARIANCE PARAMETERS, RESIDUALS AND LIKELIHOODS

**Variance parameters**

Base standard deviation in index of abundance residuals:

\begin{equation}
{\sigma _O} = \sqrt {\frac{\rho }{{{\varphi ^{ - 2}}}}}
(\#eq:ddsigo)
\end{equation}

Standard deviation in ln recruitment residuals:

\begin{equation}
{\sigma _R} = \sqrt {\frac{{\left( {1 - \rho } \right)}}{{{\varphi ^{ - 2}}}}}
(\#eq:ddsigr)
\end{equation}

Standard deviation in index of abundance observations:

\begin{equation}
{\sigma _{_{j,t}}} = \frac{{{\sigma _O}}}{{{c_{j,t}}}}
(\#eq:ddsigjt)
\end{equation}

Weighting term for index observations:

\begin{equation}
{c_{j,t}} = \frac{1}{{{\rm{C}}{{\rm{V}}_{j,t}}}}
 (\#eq:ddcjt)
\end{equation}

**Indices of abundance**

Residuals:

\begin{equation}
{z_{j,t}} = \ln \left( {{I_{j,t}}} \right) - \ln \left( {{{\hat B}_t}} \right)
(\#eq:ddzjt)
\end{equation}

\begin{equation}
{\bar z_j} = \frac{{\sum\limits_t^{{n_j}} {{z_{j,t}}} }}{{{n_j}}}
(\#eq:ddzbar)
\end{equation}

\begin{equation}
{d_{j,t}} = {z_{j,t}} - {\bar z_j}
(\#eq:dddjt)
\end{equation}

Ln likelihood:

\begin{equation}
{L_{j,t}} = \ln \left( {\sigma _{j,t}^2} \right) + \frac{{d_{j,t}^2}}{{2\sigma _{j,t}^2}}
(\#eq:ddljt)
\end{equation}

**Catch**

Residuals:

\begin{equation}
{d_C}_t = \ln \left( {{C_t}} \right) - \ln \left( {{{\hat C}_t}} \right)
(\#eq:dddct)
\end{equation}

Ln likelihood:

\begin{equation}
{L_t} = \ln \left( {{\sigma _C}{{^2}}} \right) + \frac{{{d_C}_t^2}}{{2{\sigma _C}^2}}
(\#eq:ddclt)
\end{equation}

**Mean weight**

Residuals:

\begin{equation}
{d_W}_t = \ln \left( {{{\bar W}_t}} \right) - \ln \left( {{{\hat{\bar{W}}_t}}} \right)
(\#eq:dddwt)
\end{equation}

Ln likelihood:

\begin{equation}
{L_t} = \ln \left( {{\sigma _W}{{^2}}} \right) + \frac{{{d_W}_t^2}}{{2{\sigma _W}^2}}
(\#eq:ddwlt)
\end{equation}

**Recruitment**

Residuals:

\begin{equation}
{d_R}_t = \ln \left( {{R_t}} \right) - \ln \left( {{{\hat R}_t}} \right)
(\#eq:dddrt)
\end{equation}

Ln likelihood:

\begin{equation}
{L_t} = \ln \left( {{\sigma _R}{{^2}}} \right) + \frac{{{d_R}_t^2}}{{2{\sigma _R}^2}}
(\#eq:ddrlt)
\end{equation}

\clearpage
