\clearpage

# TABLES

```{r tab-catch-5abcd}
catch.table(catch.5,
            catch.5.discards,
            area = "5ABCD",
 cap = paste0("Reported catch (mt) of Pacific Cod in Area 5ABCD ",
              "by Canada and the USA, ",
              min(catch.5$year, catch.5.discards$year), "--", max(catch.5$year, catch.5.discards$year),
              ". The reported discards for the period ", min(catch.5$year, catch.5.discards$year),
              "--1995 are ",
              "unrepresentative of true discarding because the estimates were taken ",
              "from logbooks. Discard estimates since 1996 are based on at-sea ",
              "observations and are considered to be more representative of true discarding."))
```


```{r tab-catch-3cd}
catch.table(catch.3,
            catch.3.discards,
            area = "3CD",
 cap = paste0("Reported catch (mt) of Pacific Cod in Area 3CD ",
              "by Canada and the USA, ",
              min(catch.3$year, catch.3.discards$year), "--", max(catch.3$year, catch.3.discards$year),
              ". The reported discards for the period ", min(catch.3$year, catch.3.discards$year),
              "--1995 are ",
              "unrepresentative of true discarding because the estimates were taken ",
              "from logbooks. Discard estimates since 1996 are based on at-sea ",
              "observations and are considered to be more representative of true discarding."))
```

\clearpage

```{r tab-tac}
tac.table(tac,
 cap = paste0("Summary of TACs by area."))
```

\clearpage

```{r tab-priors-5abcd}
priors.table(base.model.5abcd,
             cap = paste0("Priors and their parameters and initial values used in the ",
                          "Area 5ABCD Reference Case model. ", q.5abcd.desc))
```

```{r tab-priors-3cd}
priors.table(base.model.3cd,
             cap = paste0("Priors and their parameters and initial values used in the ",
                          "Area 3CD reference model. ", q.3cd.desc))
```

```{r suggested-ref-points}
df <- data.frame(referencepoint = c("Bmin",
                     "Bavg",
                     "Favg",
                     "B2019",
                     "F2018"),
                 Definition = c(
                   "Minimum biomass from which the stock recovered to above average (1971 in  5ABCD; 1986 in 3CD)",
                   "Average biomass for the period 1956-2004",
                   "Average fishing mortality for the period 1956-2004",
                   "Projected biomass in 2019",
                   "Projected fishing mortality in 2018"),
                 Role = c("LRP",
                        "USR",
                        "LRR",
                        "Benchmark",
                        "Benchmark")) %>%

  mutate(referencepoint = gsub("Bmin", "$B_{\t{Min}}$", referencepoint)) %>%
  mutate(referencepoint = gsub("Bavg", "$B_{\t{Avg}}$", referencepoint)) %>%
  mutate(referencepoint = gsub("Favg", "$F_{\t{Avg}}$", referencepoint)) %>%
  mutate(referencepoint = gsub("B2019", "$B_{\t{2019}}$", referencepoint)) %>%
  mutate(referencepoint = gsub("F2018", "$F_{\t{2018}}$", referencepoint)) %>%
  mutate(Definition = gsub("1971", "$B_{\t{1971}}$", Definition)) %>%
  mutate(Definition = gsub("1986", "$B_{\t{1986}}$", Definition)) %>%
  rename("Reference point" = referencepoint)

  kable(df,
        caption = paste0("Suggested reference points for the Reference Case ",
                         "5ABCD and 3CD models."),
                         booktabs = TRUE,
                         linesep = "",
                         escape = FALSE) %>%
        column_spec(2, width = "10cm") %>%
    kableExtra::kable_styling(latex_options = "hold_position")

```

\clearpage

## MODEL RESULTS: AREA 5ABCD

```{r tab-param-table-5abcd, results='asis', cache=FALSE}
make.parameters.table(base.model.5abcd,
  caption = paste0("Estimated and fixed parameters and prior probablilty distributions used ",
    "in the Reference Case, Area 5ABCD."),
  omit_pars = c("Log initial recruitment ($\\ln(\\overline{R}_{init})$)", 
    "Log mean recruitment ($\\ln(\\overline{R})$)"),
  omit_selectivity_pars = TRUE)
```

```{r tab-param-est-table-5abcd, results='asis', cache=FALSE}
make.parameters.est.table(base.model.5abcd,
  caption = paste0("Posterior (2.5\\textsuperscript{th} percentile, Median, and ",
    "97.5\\textsuperscript{th} percentile) and MPD ",
    "estimates of key parameters from the Reference Case, Area 5ABCD. TO DO: REMOVE Ravg and Rinit.",
    q.5abcd.desc),
  omit_pars = c("$\\overline{R}_{init}$", "$\\overline{R}$"))
```

```{r tab-ref-points-table-5abcd, results='asis', cache=FALSE}
make.ref.points.table(base.model.5abcd,
                      omit_msy = TRUE,
                      digits = 2,
                      caption = paste0("Posterior (2.5\\textsuperscript{th} percentile, Median, and ",
                                       "97.5\\textsuperscript{th} percentile) of proposed reference points for Area 5ABCD. ",
                                       "Biomass numbers are in tonnes."))
```

```{r tab-post-biomass-5abcd, results='asis', cache=FALSE}
make.value.table(base.model.5abcd,
                 1,
                 digits = 0,
                 caption = paste0("Posterior (2.5\\textsuperscript{th} percentile, Median, and 97.5\\textsuperscript{th} ",
                                  "percentile) and MPD estimates of biomass (t) forthe Reference Case, ",
                                  "Area 5ABCD."))
```

```{r tab-post-depl-5abcd, cache=FALSE}
make.value.table(base.model.5abcd,
                 5,
                 digits = 2,
                 caption = paste0("Posterior (2.5\\textsuperscript{th} percentile, Median, and 97.5\\textsuperscript{th} ",
                                  "percentile) and MPD estimates of relative biomass ",
                                  "for the Reference Case, Area 5ABCD."))
```

```{r tab-post-recr-5abcd, results='asis', cache=FALSE}
make.value.table(base.model.5abcd,
                 2,
                 digits = 0,
                 caption = paste0("Posterior (2.5\\textsuperscript{th} percentile, Median, and 97.5\\textsuperscript{th} ",
                                  "percentile) and MPD estimates of recruitment (thousands) for the Reference Case, ",
                                  "Area 5ABCD."))
```

```{r tab-post-f-5abcd, results='asis', cache=FALSE}
make.value.table(base.model.5abcd,
                 3,
                 digits = 2,
                 caption = paste0("Posterior (2.5\\textsuperscript{th} percentile, Median, and 97.5\\textsuperscript{th} ",
                                  "percentile) and MPD estimates of fishing mortality, F, ",
                                  "for the Reference Case, Area 5ABCD."))
```

\clearpage

## MODEL RESULTS: AREA 3CD

```{r tab-param-table-3cd, results='asis', cache=FALSE}
make.parameters.table(base.model.3cd,
  caption = paste0("Estimated and fixed parameters and prior probablilty distributions used ",
    "in the Reference Case, Area 3CD."),
  omit_pars = c("Log initial recruitment ($\\ln(\\overline{R}_{init})$)", 
    "Log mean recruitment ($\\ln(\\overline{R})$)"),
  omit_selectivity_pars = TRUE)
```

```{r tab-param-est-table-3cd, results='asis', cache=FALSE}
make.parameters.est.table(base.model.3cd,
  caption = paste0("Posterior (2.5\\textsuperscript{th} percentile, Median, and ",
    "97.5\\textsuperscript{th} percentile) and MPD ",
    "estimates of key parameters from the reference Case, Area 3CD. TO DO: REMOVE Ravg and Rinit. ",
    q.5abcd.desc),
  omit_pars = c("$\\overline{R}_{init}$", "$\\overline{R}$"))
```

```{r tab-ref-points-table-3cd, results='asis', cache=FALSE}
make.ref.points.table(base.model.3cd,
                      omit_msy = TRUE,
                      digits = 2,
                      caption = paste0("Posterior (2.5\\textsuperscript{th} percentile, Median, and ",
                                       "97.5\\textsuperscript{th} percentile) of proposed reference points for Area 3CD. ",
                                       "Biomass numbers are in tonnes."))
```

```{r tab-post-biomass-3cd, results='asis', cache=FALSE}
make.value.table(base.model.3cd,
                 1,
                 digits = 0,
                 caption = paste0("Posterior (2.5\\textsuperscript{th} percentile, Median, and 97.5\\textsuperscript{th} ",
                                  "percentile) and MPD estimates of biomass (t) for ",
                                  "the Reference Case, Area 3CD."))
```

```{r tab-post-depl-3cd, cache=FALSE}
make.value.table(base.model.3cd,
                 5,
                 digits = 2,
                 caption = paste0("Posterior (2.5\\textsuperscript{th} percentile, Median, and 97.5\\textsuperscript{th} ",
                                  "percentile) and MPD estimates of relative biomass ",
                                  "for the Reference Case, Area 3CD."))
```

```{r tab-post-recr-3cd, results='asis', cache=FALSE}
make.value.table(base.model.3cd,
                 2,
                 digits = 0,
                 caption = paste0("Posterior (2.5\\textsuperscript{th} percentile, Median, and 97.5\\textsuperscript{th} ",
                                  "percentile) and MPD estimates of recruitment (thousands) for the Reference Case,",
                                  "Area 3CD."))
```

```{r tab-post-f-3cd, results='asis', cache=FALSE}
make.value.table(base.model.3cd,
                 3,
                 digits = 2,
                 caption = paste0("Posterior (2.5\\textsuperscript{th} percentile, Median, and 97.5\\textsuperscript{th} ",
                                  "percentile) and MPD estimates of fishing mortality, F, ",
                                  "for the Reference Case, Area 3CD."))
```

\clearpage

## SELECTED SENSITIVITY RESULTS: AREA 5ABCD

```{r tab-param-table-sens3a-5abcd, results='asis', cache=FALSE}
make.parameters.est.table(sens.models.3[[1]],
 caption = paste0("Estimated and fixed parameters and prior probablilty distributions used ",
                  "for Sc 3a (mean ln(M)=ln(0.5), SD=0.2), Area 5ABCD. TO DO: REMOVE MSY-based pars, Ravg and Rinit."))
```

```{r tab-param-table-sens3b-5abcd, results='asis', cache=FALSE}
make.parameters.est.table(sens.models.3[[2]],
 caption = paste0("Posterior (2.5\\textsuperscript{th} percentile, Median, and ",
                   "97.5\\textsuperscript{th} percentile) and MPD ",
                   "estimates of key parameters ",
                  "for Sc 3b (mean ln(M)=ln(0.4), SD=0.1), Area 5ABCD. TO DO: REMOVE Ravg and Rinit."))
```

```{r tab-param-table-sens3c-5abcd, results='asis', cache=FALSE}
make.parameters.est.table(sens.models.3[[3]],
 caption = paste0("Posterior (2.5\\textsuperscript{th} percentile, Median, and ",
                   "97.5\\textsuperscript{th} percentile) and MPD ",
                   "estimates of key parameters ",
                  "for Sc 3c (mean ln(M)=ln(0.4), SD=0.2), Area 5ABCD. TO DO: REMOVE Ravg and Rinit."))
```

```{r tab-param-table-sens4a-5abcd, results='asis', cache=FALSE}
make.parameters.est.table(sens.models.4[[1]],
 caption = paste0("Posterior (2.5\\textsuperscript{th} percentile, Median, and ",
                   "97.5\\textsuperscript{th} percentile) and MPD ",
                   "estimates of key parameters ",
                  "for Sc 4a (Uniform prior for steepness), Area 5ABCD. TO DO: REMOVE Ravg and Rinit."))
```

```{r tab-param-table-sens4b-5abcd, results='asis', cache=FALSE}
make.parameters.est.table(sens.models.4[[2]],
 caption = paste0("Posterior (2.5\\textsuperscript{th} percentile, Median, and ",
                   "97.5\\textsuperscript{th} percentile) and MPD ",
                   "estimates of key parameters ",
                  "for Sc 4b (beta prior for steepness with mean = 0.85 and SD = 0.15), Area 5ABCD. TO DO: REMOVE Ravg and Rinit."))
```

\clearpage

## SELECTED SENSITIVITY RESULTS: AREA 3CD

```{r tab-param-table-sens3a-3cd, results='asis', cache=FALSE}
make.parameters.est.table(sens.models.10[[1]],
 caption = paste0("Posterior (2.5\\textsuperscript{th} percentile, Median, and ",
                   "97.5\\textsuperscript{th} percentile) and MPD ",
                   "estimates of key parameters ",
                  "for Sc 3a (mean ln(M)=ln(0.5), SD=0.2), Area 3CD. TO DO: REMOVE Ravg and Rinit."))
```

```{r tab-param-table-sens3b-3cd, results='asis', cache=FALSE}
make.parameters.est.table(sens.models.10[[2]],
 caption = paste0("Posterior (2.5\\textsuperscript{th} percentile, Median, and ",
                   "97.5\\textsuperscript{th} percentile) and MPD ",
                   "estimates of key parameters ",
                  "for Sc 3b (mean ln(M)=ln(0.4), SD=0.1), Area 3CD. TO DO: REMOVE Ravg and Rinit."))
```

```{r tab-param-table-sens3c-3cd, results='asis', cache=FALSE}
make.parameters.est.table(sens.models.10[[3]],
 caption = paste0("Posterior (2.5\\textsuperscript{th} percentile, Median, and ",
                   "97.5\\textsuperscript{th} percentile) and MPD ",
                   "estimates of key parameters ",
                  "for Sc 3c (mean ln(M)=ln(0.4), SD=0.2), Area 3CD. TO DO: REMOVE Ravg and Rinit."))
```

```{r tab-param-table-sens4a-3cd, results='asis', cache=FALSE}
make.parameters.est.table(sens.models.11[[1]],
 caption = paste0("Posterior (2.5\\textsuperscript{th} percentile, Median, and ",
                   "97.5\\textsuperscript{th} percentile) and MPD ",
                   "estimates of key parameters ",
                  "for Sc 4a (Uniform prior for steepness), Area 3CD. TO DO: REMOVE Ravg and Rinit."))
```

```{r tab-param-table-sens4b-3cd, results='asis', cache=FALSE}
make.parameters.est.table(sens.models.11[[2]],
 caption = paste0("Posterior (2.5\\textsuperscript{th} percentile, Median, and ",
                   "97.5\\textsuperscript{th} percentile) and MPD ",
                   "estimates of key parameters ",
                  "for Sc 4b (beta prior for steepness with mean = 0.85 and SD = 0.15), Area 3CD. TO DO: REMOVE Ravg and Rinit."))
```
