\clearpage

`r if(knitr:::is_latex_output()) '\\Appendices'`

`r if(!knitr:::is_latex_output()) '# (APPENDIX) Appendix {-}'`

```{r cpue-params}
params <- list()
params$species_proper <- "Pacific Cod"
params$april1_year <- TRUE
params$area <- c("5[ABCD]+", "3[CD]+")
params$area_name <- c("5ABCD", "3CD")
params$skip_single_variable_models <- FALSE
```

```{r cpue-run-historic}
params$era <- "historic"
source(here::here("index/cpue.R"))
dfleet_hist <- dfleet
gg_cpue_hist <- gg_cpue
cpue_pred_hist <- predictions
arith_cpue_hist <- arith_cpue
m_historic <- readRDS(here::here("data/generated/cpue-models-pcod-historic.rds"))
```

```{r cpue-run-modern}
params$era <- "modern"
source(here::here("index/cpue.R"))
dfleet_modern <- dfleet
gg_cpue_modern <- gg_cpue
cpue_pred_modern <- predictions
arith_cpue_modern <- arith_cpue
m_modern <- readRDS(here::here("data/generated/cpue-models-pcod-modern.rds"))
```

```{r cpue-catch-effort-ts, fig.cap="TODO", fig.asp=1.1}
make_catch_effort_ts_plot <- function(dat) {
  bind_rows(dat) %>% group_by(year, area) %>%
    summarise(
      `Species catch` = sum(spp_catch)/1000,
      `Hours fished` = sum(hours_fished)/1000) %>%
    reshape2::melt(id.vars = c("year", "area")) %>%
    ggplot(aes(year, value)) +
    geom_line() +
    facet_grid(variable~area, scales = "free_y") +
    ylab("Value (1000 kg or 1000 hours)") + xlab("") +
    ylim(0, NA)
}
g1 <- make_catch_effort_ts_plot(dfleet_hist)  +
  ggtitle("1956-1995 data")
g2 <- make_catch_effort_ts_plot(dfleet_modern) +
  ggtitle("1996+ data")
cowplot::plot_grid(g1, g2, ncol = 1)
```

```{r, cpue-depth-hists, fig.asp=0.8, fig.cap="TODO"}
g1 <- gg_cpue_modern$depth + ylab("Fishing event count") + xlab("Depth") +
  labs(fill = "Fishing event\ncaught\nPacific Cod") +
  theme(legend.position = c(0.95, 0.95), legend.background = element_rect(fill = "white"),
    legend.justification = c(1, 1)) +
  ggtitle("1996+ data")

g2 <- gg_cpue_hist$depth + ylab("Trip count") + xlab("Depth") +
  labs(fill = "Trip\ncaught\nPacific Cod") +
  theme(legend.position = c(0.95, 0.95), legend.background = element_rect(fill = "white"),
    legend.justification = c(1, 1)) +
  ggtitle("1956-1995 data")

cowplot::plot_grid(g2, g1, ncol = 1)
```

```{r cpue-bubble-funcs}
make_bubble_dat <- function(dat,
  measure.vars = c("month", "locality_code", "vessel", "latitude", "depth")) {
  bubble_pos <- bind_rows(dat) %>%
    filter(spp_catch > 0) %>%
    reshape2::melt(id.vars = c("year", "area"),
      measure.vars = measure.vars) %>%
    group_by(area, year, variable, value) %>%
    summarize(n_pos = n())
  
  bubble_all <- bind_rows(dat) %>%
    reshape2::melt(id.vars = c("year", "area"),
      measure.vars = measure.vars) %>%
    group_by(area, year, variable, value) %>%
    summarize(n = n())
  
  left_join(bubble_all, bubble_pos, by = c("area", "year", "variable", "value")) %>%
    ungroup() %>%
    mutate(variable = gfplot:::firstup(gsub("_", " ", variable)))
}

make_facet_bubble_plot <- function(dat, group = "fishing events") {
  ggplot(dat, aes_string("as.factor(year)", y = "value")) +
    geom_point(aes_string(size = "n_pos", fill = "n"), alpha = 0.4, pch = 21) +
    geom_point(aes_string(size = "n"), alpha = 0.4, pch = 21) +
    facet_wrap(~variable, scales = "free", ncol = 2) +
    ggplot2::scale_x_discrete(breaks = seq(1950, 2020, 5)) +
    xlab("") + ylab("") +
    labs(size = paste0("Number of\n", group)) +
    labs(fill = paste0("Number of\n", group)) +
    ggplot2::scale_size_continuous(range = c(0, 7)) +
    ggplot2::scale_fill_viridis_c(trans = "log", breaks = c(1, 10, 100, 500)) +
    theme_pbs() +
    theme(legend.position = c(0.95, 0.05), legend.justification = c(1, 0),
      legend.direction = "horizontal")
}
```

```{r cpue-bubble-plots-hist-3CD, fig.asp=1.35, fig.cap="Distribution of predictors in CPUE standardization models for 1956--1995 3CD dataset. Area of outermost circles represents the number of trip-locality combinations for that predictor value and year combination. Inner "}
dfleet_hist %>%
  make_bubble_dat(measure.vars = c("month", "locality", "depth")) %>%
  filter(area == "3CD") %>%
  make_facet_bubble_plot(group = "trips") +
  ggtitle("1956-1995 3CD")
```

```{r cpue-bubble-plots-hist-5ABCD, fig.asp=1.35, fig.cap="TODO"}
dfleet_hist %>%
  make_bubble_dat(measure.vars = c("month", "locality", "depth")) %>%
  filter(area == "5ABCD") %>%
  make_facet_bubble_plot(group = "trips") +
  ggtitle("1956-1995 5ABCD")
```

```{r cpue-bubble-plots-moder-3CD, fig.asp=1.35, fig.cap="TODO"}
dfleet_modern %>% make_bubble_dat() %>%
  filter(area == "3CD") %>%
  make_facet_bubble_plot() +
  ggtitle("1996+ 3CD")
```

```{r cpue-bubble-plots-modern-5ABCD, fig.asp=1.35, fig.cap="TODO"}
dfleet_modern %>% make_bubble_dat() %>%
  filter(area == "5ABCD") %>%
  make_facet_bubble_plot() +
  ggtitle("1996+ 5ABCD")
```

```{r cpue-index-ts-funcs}
make_cpue_ts_dat <- function(dat) {
  pp <- dat %>%
    group_by(formula_version, model, area) %>%
    mutate(geo_mean = exp(mean(log(est)))) %>%
    mutate(upr = upr / geo_mean, lwr = lwr / geo_mean, est = est / geo_mean) %>%
    ungroup() %>%
    mutate(formula_version =
        gsub("Full standardization minus interactions",
          "Full standardization\nminus interactions", formula_version)) %>%
    mutate(formula_version =
        forcats::fct_relevel(formula_version,
          "Full standardization\nminus interactions", after = Inf)) %>%
    mutate(formula_version =
        forcats::fct_relevel(formula_version,
          "Full standardization", after = Inf))
  uns <- filter(pp, formula_version == "Unstandardized") %>% select(-formula_version)
  list(stand = pp, unstand = uns)
}

make_cpue_ts_plot <- function(dat) {
  dat$stand %>%
    filter(formula_version != "Unstandardized") %>%
    ggplot(aes(year, est, ymin = lwr, ymax = upr, fill = formula_version)) +
    geom_line() +
    geom_ribbon(data = dat$unstand, aes(x = year, ymin = lwr, ymax = upr),
      fill = "black", alpha = 0.5,
      inherit.aes = FALSE) +
    geom_line(data = dat$unstand, aes(x = year, y = est),
      colour = "black", inherit.aes = FALSE) +
    labs(fill = "Version", colour = "Version", y = "") +
    geom_ribbon(alpha = 0.5) +
    geom_line(aes(colour = formula_version)) +
    facet_grid(formula_version~area) +
    ylab("CPUE (kg/hour) divided\nby geometric mean") +
    guides(fill = FALSE, colour = FALSE) + xlab("")
}
```

```{r cpue-index-ts-hist, fig.asp=1.1, fig.cap="TODO"}
make_cpue_ts_dat(cpue_pred_hist) %>% make_cpue_ts_plot() +
  ggtitle("1956-1995 CPUE")
```

```{r cpue-index-ts-modern, fig.asp=1.35, fig.cap="TODO"}
make_cpue_ts_dat(cpue_pred_modern) %>% make_cpue_ts_plot() +
  ggtitle("1996+ CPUE")
```

```{r cpue-int-test-funcs}
make_cpue_ts_dat_noint <- function(dat) {
  pp <- dat %>%
    group_by(formula_version, model, area) %>%
    mutate(geo_mean = exp(mean(log(est)))) %>%
    mutate(upr = upr / geo_mean, lwr = lwr / geo_mean, est = est / geo_mean) %>%
    ungroup() %>%
    mutate(formula_version =
        gsub("Full standardization minus interactions",
          "Full standardization\nminus interactions", formula_version)) %>%
    mutate(formula_version =
        forcats::fct_relevel(formula_version,
          "Full standardization\nminus interactions", after = Inf)) %>%
    mutate(formula_version =
        forcats::fct_relevel(formula_version,
          "Full standardization", after = Inf))
  uns <- filter(pp, formula_version == "Full standardization\nminus interactions") %>% 
    select(-formula_version)
  list(stand = pp, unstand = uns)
}

make_cpue_ts_plot_noint <- function(dat) {
  dat$stand %>%
    filter(formula_version == "Full standardization") %>%
    ggplot(aes(year, est, ymin = lwr, ymax = upr, fill = formula_version)) +
    geom_line() +
    geom_ribbon(data = dat$unstand, aes(x = year, ymin = lwr, ymax = upr),
      fill = "black", alpha = 0.5,
      inherit.aes = FALSE) +
    geom_line(data = dat$unstand, aes(x = year, y = est),
      colour = "black", inherit.aes = FALSE) +
    labs(fill = "Version", colour = "Version", y = "") +
    geom_ribbon(alpha = 0.5) +
    geom_line(aes(colour = formula_version)) +
    facet_wrap(~area, ncol = 2) +
    ylab("CPUE (kg/hour) divided\nby geometric mean") +
    guides(fill = FALSE, colour = FALSE) + xlab("")
}
```

```{r cpue-int-test-plot, fig.asp=0.85, fig.cap="A comparison of CPUE timeseries standardized with a model that does not include locality-year random effects (black/grey) and a model that does include the locality-year random effects (red)."}
g1 <- make_cpue_ts_dat_noint(cpue_pred_hist) %>% make_cpue_ts_plot_noint() +
  ggtitle("1956-1995 CPUE")
g2 <- make_cpue_ts_dat_noint(cpue_pred_modern) %>% make_cpue_ts_plot_noint() +
  ggtitle("1996+ CPUE")
cowplot::plot_grid(g1, g2, ncol = 1)
```

```{r}
make_fe_plots <- function(object) {
  su <- summary(object)$coefficients$cond
  sud <- as.data.frame(su)
  sud$param <- row.names(su)
  row.names(sud) <- NULL
  sud <- rename(sud, est = Estimate, se = `Std. Error`)
  sud <- mutate(sud, par_value = gsub("^[A-Z_a-z]+", "", param))
  sud <- mutate(sud, par_group = gsub("^([A-Z_a-z]+)[0-9.]+$", "\\1", param))
  ggplot(sud, aes_string("est", "forcats::fct_rev(par_value)",
    yend = "forcats::fct_rev(par_value)"
  )) +
    ggplot2::geom_segment(aes_string(
      x = "est - 1.96 * se",
      xend = "est + 1.96 * se"
    ), lwd = 0.5) +
    ggplot2::geom_segment(aes_string(
      x = "est - 0.67 * se",
      xend = "est + 0.67 * se"
    ), lwd = 1.25) +
    geom_point() +
    facet_wrap(~par_group, scales = "free") +
    theme_pbs() + guides(shape = FALSE, colour = FALSE) +
    labs(x = "Coefficient value (log space)", y = "Predictor value")
}
make_re_dat <- function(object) {
  re <- ranef(object)
  plyr::ldply(re$cond, function(x) {
    sud <- as.data.frame(x)
    sud$par_value <- row.names(sud)
    row.names(sud) <- NULL
    sud
  }) %>% 
    rename(par_group = .id) %>%
    rename(est = `(Intercept)`) %>% 
    as_tibble() %>% 
    mutate(loc_group = gsub("^([0-9]+)[ -]*([0-9a-zA-Z]+)$", "\\2", par_value)) %>% 
    mutate(loc_year = gsub("^([0-9]+)[ -]*[0-9a-zA-Z]+$", "\\1", par_value))
}
make_re_plots <- function(object, re_names = c("locality")) {
  re <- make_re_dat(object)
  filter(re, par_group %in% re_names) %>% 
    ggplot(aes_string("est", "forcats::fct_rev(par_value)")) +
    geom_vline(xintercept = 0, lty = 2, alpha = 0.4) +
    geom_point(bg = "white") +
    facet_wrap(~par_group, scales = "free") +
    theme_pbs() + guides(shape = FALSE, colour = FALSE) +
    labs(x = "Random intercept value (log space)", y = "")
}
make_year_locality_plots <- function(object) {
  re <- make_re_dat(object)
  filter(re, par_group == "year_locality") %>% 
    ggplot(aes_string("as.numeric(loc_year)", "est", group = "loc_group")) +
    geom_hline(yintercept = 0, lty = 2, alpha = 0.4) +
    geom_point(alpha = 0.7) +
    geom_line(alpha = 0.3) +
    # facet_wrap(~loc_group) +
    theme_pbs() + guides(shape = FALSE, colour = FALSE) +
    labs(x = "Year", y = "Random intercept\n(interaction) value (log space)")
}
```

```{r cpue-re-int-ts-funcs}
most_common <- function(x) names(rev(sort(table(as.character(x)))))[[1]]
basel_level <- function(x) levels(x)[[1]]

plot_cpue_int_res <- function(model, fleet, index_data, 
  era = c("modern", "historical"), ref_type = c("base", "common"),
  the_formula_version = "Full standardization") {
  
  era <- match.arg(era)
  ref_type <- match.arg(ref_type)
  
  library(glmmTMB)
  
  if (ref_type == "base") {
    newdata <- select(fleet, year_factor, locality) %>%
      unique() %>% 
      mutate(year = as.numeric(as.character(year_factor))) %>% 
      group_by(locality) %>% 
      do({
        data_frame(year = seq(min(.$year), max(.$year)))
      }) %>% 
      group_by(locality) %>%
      mutate(
        depth = basel_level(fleet$depth),
        month = basel_level(fleet$month)
      )
    if (era == "modern") {
      newdata <- newdata %>% mutate(
        latitude = basel_level(fleet$latitude),
        vessel = basel_level(fleet$vessel))
    }
  } else {
    if (era != "modern") {
    newdata <- fleet %>% 
      mutate(year = as.numeric(as.character(year_factor))) %>% 
      group_by(locality) %>%
      summarise(
        year_min = min(year), 
        year_max = max(year), 
        depth = most_common(depth), 
        month = most_common(month)
      )
    }
    if (era == "modern") {
      newdata <- fleet %>% 
      mutate(year = as.numeric(as.character(year_factor))) %>% 
      group_by(locality) %>%
      summarise(
        year_min = min(year), 
        year_max = max(year), 
        depth = most_common(depth), 
        month = most_common(month),
        latitude = most_common(latitude), 
        vessel = most_common(vessel)
      )
    }
    if (era != "modern") {
      newdata <- newdata %>% group_by(locality) %>%
        do({
          data_frame(
            year = seq(.$year_min, .$year_max),
            depth = .$depth,
            month = .$month
          )
        })
    }
    if (era == "modern") {
      newdata <- newdata %>% group_by(locality) %>%
        do({
          data_frame(
            year = seq(.$year_min, .$year_max),
            depth = .$depth,
            month = .$month,
            vessel = .$vessel,
            latitude = .$latitude
          )
        })
    }
  }
  newdata <- ungroup(newdata)
  newdata <- newdata %>% mutate(year_locality = paste(year, locality))
  newdata <- newdata %>% mutate(year_factor = as.character(year))
  
  pp <- predict(model, newdata = newdata)
  newdata$loc_pred <- pp
  newdata <- arrange(newdata, year, locality)
  
  stand <- filter(index_data, formula_version == the_formula_version, 
    area == unique(fleet$area)[[1]]) %>% 
    select(year, est_link, se_link)
  
  ggplot(newdata, aes(year, loc_pred)) + 
    geom_line(alpha = 0.7, aes(group = locality, colour = locality)) +
    geom_line(data = stand, aes(x = year, est_link), inherit.aes = FALSE, lwd = 1) +
    geom_ribbon(data = stand,
      aes(x = year, ymin = est_link - 1.96 * se_link,
        ymax = est_link + 1.96 * se_link), inherit.aes = FALSE, alpha = 0.4) +
    guides(colour = FALSE) +
    scale_color_discrete() + ylab("Log of standardized CPUE") +
    xlab("")
}
```

```{r cpue-re-int-ts, fig.cap="Locality-specific CPUE index trends. The coloured lines indicate the effect of including locality and locality-year random effects. The black line and shaded ribbon indicate the overall average annual CPUE --- the standardized CPUE timeseries used elsewhere.", fig.asp=0.8}
stopifnot(length(m_modern) == 16L)
g1 <- plot_cpue_int_res(m_modern[[8]], fleet = dfleet_modern[[1]], 
  index_data = cpue_pred_modern,
  era = "modern") + ggtitle("1996+ 5ABCD")

g2 <- plot_cpue_int_res(m_modern[[16]], fleet = dfleet_modern[[2]], 
  index_data = cpue_pred_modern,
  era = "modern") + ggtitle("1996+ 3CD")

stopifnot(length(m_historic) == 12L)
g3 <- plot_cpue_int_res(m_historic[[6]], fleet = dfleet_hist[[1]], 
  index_data = cpue_pred_hist,
  era = "historical")+ ggtitle("1956-1995 5ABCD")

g4 <- plot_cpue_int_res(m_historic[[12]], fleet = dfleet_hist[[2]], 
  index_data = cpue_pred_hist,
  era = "historical")+ ggtitle("1956-1995 3CD")

cowplot::plot_grid(g4, g3, g2, g1, ncol = 2)
```

```{r cpue-re-int-ts-common, fig.cap="Locality-specific CPUE index trends with other predictors at their most common locality value. The coloured lines indicate the effect of including locality and locality-year random effects. The black line and shaded ribbon indicate the overall average annual CPUE --- the standardized CPUE timeseries used elsewhere.", fig.asp=0.8}
g1 <- plot_cpue_int_res(m_modern[[8]], fleet = dfleet_modern[[1]], 
  index_data = cpue_pred_modern, ref_type = "common",
  era = "modern") + ggtitle("1996+ 5ABCD")

g2 <- plot_cpue_int_res(m_modern[[16]], fleet = dfleet_modern[[2]], 
  index_data = cpue_pred_modern, ref_type = "common",
  era = "modern") + ggtitle("1996+ 3CD")

g3 <- plot_cpue_int_res(m_historic[[6]], fleet = dfleet_hist[[1]], 
  index_data = cpue_pred_hist, ref_type = "common",
  era = "historical")+ ggtitle("1956-1995 5ABCD")

g4 <- plot_cpue_int_res(m_historic[[12]], fleet = dfleet_hist[[2]], 
  index_data = cpue_pred_hist, ref_type = "common",
  era = "historical")+ ggtitle("1956-1995 3CD")

cowplot::plot_grid(g4, g3, g2, g1, ncol = 2)
```

```{r cpue-re-no-int-ts, fig.cap="Locality-specific CPUE index trends. The coloured lines indicate the effect of including locality random effects. The black line and shaded ribbon indicate the overall average annual CPUE.", fig.asp=0.8}
g1 <- plot_cpue_int_res(m_modern[[7]], fleet = dfleet_modern[[1]], 
  index_data = cpue_pred_modern,
  the_formula_version = "Full standardization minus interactions",
  era = "modern") + ggtitle("1996+ 5ABCD")

g2 <- plot_cpue_int_res(m_modern[[15]], fleet = dfleet_modern[[2]], 
  index_data = cpue_pred_modern,
  the_formula_version = "Full standardization minus interactions",
  era = "modern") + ggtitle("1996+ 3CD")

g3 <- plot_cpue_int_res(m_historic[[5]], fleet = dfleet_hist[[1]], 
  index_data = cpue_pred_hist,
  the_formula_version = "Full standardization minus interactions",
  era = "historical")+ ggtitle("1956-1995 5ABCD")

g4 <- plot_cpue_int_res(m_historic[[11]], fleet = dfleet_hist[[2]], 
  index_data = cpue_pred_hist,
  the_formula_version = "Full standardization minus interactions",
  era = "historical")+ ggtitle("1956-1995 3CD")

cowplot::plot_grid(g4, g3, g2, g1, ncol = 2)
```


```{r cpue-re-no-int-ts-common, fig.cap="Locality-specific CPUE index trends with other predictors at their most common locality value. The coloured lines indicate the effect of including locality random effects. The black line and shaded ribbon indicate the overall average annual CPUE.", fig.asp=0.8}
g1 <- plot_cpue_int_res(m_modern[[7]], fleet = dfleet_modern[[1]], 
  index_data = cpue_pred_modern, ref_type = "common",
  the_formula_version = "Full standardization minus interactions",
  era = "modern") + ggtitle("1996+ 5ABCD")

g2 <- plot_cpue_int_res(m_modern[[15]], fleet = dfleet_modern[[2]], 
  index_data = cpue_pred_modern, ref_type = "common",
  the_formula_version = "Full standardization minus interactions",
  era = "modern") + ggtitle("1996+ 3CD")

g3 <- plot_cpue_int_res(m_historic[[5]], fleet = dfleet_hist[[1]], 
  index_data = cpue_pred_hist, ref_type = "common",
  the_formula_version = "Full standardization minus interactions",
  era = "historical")+ ggtitle("1956-1995 5ABCD")

g4 <- plot_cpue_int_res(m_historic[[11]], fleet = dfleet_hist[[2]], 
  index_data = cpue_pred_hist, ref_type = "common",
  the_formula_version = "Full standardization minus interactions",
  era = "historical")+ ggtitle("1956-1995 3CD")

cowplot::plot_grid(g4, g3, g2, g1, ncol = 2)
```
