\clearpage

`r if(knitr:::is_latex_output()) '\\Appendices'`

`r if(!knitr:::is_latex_output()) '# (APPENDIX) Appendix {-}'`

# FISHERY-INDEPENDENT INDICES OF ABUNDANCE

## CANADIAN SURVEYS

### HECATE STRAIT ASSEMBLAGE SURVEY

A series of multi-species groundfish bottom trawl surveys was conducted in
Hecate Strait in May-June of 1984, 1987, 1989, 1991, 1993, 1995, 1996, 1998,
2000, 2002, and 2003 @westrheim1984, @fargo1984, @fargo1988,
@wilson1991, @hand1994, @workman1996, @workman1997, @choromanski2002).
The results up to 2000 were reported in the 2001 assessment
[@sinclair2001] and results from 2002 and 2003 were presented in the
2005 assessment [@sinclair2005].

The original design of this survey assigned fishing locations by 10 fm depth
intervals within a 10 nm grid of Hecate Strait. The survey was
post-stratified for the purpose of calculating an abundance index for Pacific
Cod [@sinclair2000]. The post stratification used 10 fm depth intervals for
the entire survey area, thereby treating each depth interval as a single
stratum.

The Hecate Strait Assemblage survey was designed as a systematic
fixed-station survey. Despite attempts to apply post-sampling stratification,
this approach had high survey variance [@sinclair2007]. In 2004 the Hecate
Strait Assemblage survey was discontinued in favour of the Hecate Strait
Synoptic survey (described below).

### HECATE STRAIT SYNOPTIC SURVEY

The Hecate Strait synoptic groundfish bottom trawl survey is part of a
coordinated set of long-term surveys that together cover the continental shelf
and upper slope of most of the BC coast. The Hecate Strait synoptic survey has
been conducted during May-June, in odd years since 2005. All the synoptic
surveys follow a random depth stratified design. The survey area is divided
into 2 km by 2 km blocks and each block is assigned to one of four depth
strata based on the average bottom depth in the block. The four depth strata
for the Hecate Strait survey are 10--70m, 70--130m, 130--220m, and
220--500m. Each year blocks are randomly selected within each depth strata.
The relative allocation of blocks amongst depth strata was determined by
modeling the expected catches of groundfish and determining the target number
of tows per stratum that would provide the most precise catch rate data for
as many species as possible.

### QUEEN CHARLOTTE SOUND SYNOPTIC SURVEY

The Queen Charlotte Sound synoptic groundfish bottom trawl survey is part of
a coordinated set of long-term surveys that together cover the continental shelf
and upper slope of most of the BC coast. The Queen Charlotte Sound survey has
been conducted in July-August in 2003, 2004 and in odd years since 2005. All
the synoptic surveys follow a random depth stratified design. The survey area
is divided into 2 km by 2 km blocks and each block is assigned to one of four
depth strata based on the average bottom depth in the block. The four depth
strata for the QCS survey are 50--125m, 125--200m, 200--330m,
and 330--500 m. Each year blocks are randomly selected within each depth strata.
In addition, for the purposes of allocating blocks, the QCS survey is divided
into northern and southern spatial strata.

The relative allocation of blocks amongst depth strata was determined by
modeling the expected catches of groundfish and determining the target number
of tows per stratum that would provide the most precise catch rate data for as
many species as possible.

### WEST COAST VANCOUVER ISLAND SYNOPTIC SURVEY

*TODO* edit as needed:

The West Coast Vancouver Island synoptic bottom trawl survey was first
conducted in 2004 and is conducted in alternating (even-numbered) years on
a chartered commercial trawler. The survey area is off the west coast of
Vancouver Island from approximately 49$^\circ$ 12$^\prime$ to 50$^\circ$
36$^\prime$ North latitude and approximately 124$^\circ$ 48$^\prime$ to
128$^\circ$ 30$^\prime$ West longitude. The southern boundary is contiguous
with the Canada/U.S. boundary. The survey has a single aerial stratum in
Pacific Fishery Management Area regions 3C and 3D  separated into four depth
strata: 50-125 m; 125-200 m; 200-330 m; and 330-500 m. Approximately 150 to 180
4 km^2^ blocks are selected randomly among the four depth strata when
conducting each survey.

### SWEPT AREA ANALYSIS
For all Canadian surveys, a swept area estimate of biomass in any year y was obtained
by summing the product of the CPUE and the area surveyed across the surveyed
strata $i$:

\begin{equation}
  B_y = \sum_{i=1}^kC_{y_i}A_i=\sum_{i=1}^kB_{y_i}
  (\#eq:sweptareabiomass)
\end{equation}

where
$C_{y_i}$ = mean CPUE density (kg/km^2^) for Pacific Cod in stratum $i$
$A_i$ = area of stratum $i$ (km^2^), and
$B_{y_i}$ = biomass of Pacific Cod in stratum $i$ for year $y$
$k$ = number of strata

CPUE ($C_{y_i}$) for Pacific Cod in stratum $i$ for year $y$ was
calculated as a density in kg/km^2^ by

\begin{equation}
  C_{y_i}=\frac{1}{n_{y_i}} \sum\limits_{j=1}^{n_{y_i}} \frac{W_{y_i,j}}{D_{y_i,j}w_{y_i,j}}
  (\#eq:sweptareacpue)
\end{equation}

where
$W_{y_i,j}$ = catch weight (kg) for Pacific Cod in stratum $i$ for year $y$ and tow $j$
$D_{y_i,j}$ = distance travelled (km) by tow $j$ in stratum $i$ for year $y$
$w_{y_i,j}$ = net opening (km) by tow $j$ in stratum $i$ for year $y$
$n_{y_i}$ = number of tows in stratum $i$

The variance of the survey biomass estimate $V_y$ for Pacific Cod in year $y$
is calculated in kg^2^ as follows:

\begin{equation}
  V_y=\sum_{i=1}^k\frac{\sigma_{y_i}^2A_i^2}{n_{y_i}}=\sum_{i=1}^kV_{y_i}
  (\#eq:sweptareavariance)
\end{equation}

where $\sigma_{y_i}^2$ is the variance of the CPUE in $kg^2/km^4$ for year $y$ in
stratum $i$, $V_{y_i}$ is the variance of Pacific Cod in stratum $i$ for year $y$,
where $\sigma_{y_i}^2$ was obtained from bootstrapped samples (see below).

The CV for Pacific Code for each year $y$ was calculated as follows:

\begin{equation}
  (CV)_y=\frac{{V_y}^{1/2}}{B_y}
  (\#eq:sweptareacv)
\end{equation}

where $(CV)_y$ is the CV for year $y$.

One thousand bootstrap replicates with replacement were constructed from the
survey data to estimate bias corrected 95% confidence regions for each survey
year [@efron1982].

## NMFS TRIENNIAL SURVEY (IN CANADIAN WATERS)

A relative abundance index was developed from data from the National Marine Fisheries Service (NMFS) Triennial survey operated off the lower half of Vancouver Island.

### Analytical methods

*TO DO. Update this section, add equations. Check - could be the same as for synoptic surveys*

Catch and effort data for strata \[i\] in year \[y\] yield catch per unit effort (CPUE) values\[{U_{yi}}\]. Given a set of data \[\left\{ {{C_{yij}},{E_{yij}}} \right\}\] for tows\[j = 1, \ldots ,{n_{yi}}\],
Eq. B.1	\[{U_{yi}} = \frac{1}{{{n_{yi}}}}\sum\limits_{j = 1}^{{n_{yi}}} {\frac{{{C_{yij}}}}{{{E_{yij}}}}} \],	
where	\[{C_{yij}}\]	=	catch (kg) in tow \[j\], stratum \[i\], year \[y\];
	\[{E_{yij}}\]	=	effort (h) in tow \[j\], stratum \[i\], year \[y\];
	\[{n_{yi}}\]	=	number of tows in stratum \[i\], year \[y\].
CPUE values \({U_{yi}}\) convert to CPUE densities \[{\delta _{yi}}\] (kg/km2) using:
Eq. B.2	\[{\delta _{yi}} = \frac{1}{{vw}}{U_{yi}}\],	
where	\[v\]	=	average vessel speed (km/h);
	\[w\]	=	average net width (km).
Alternatively, if vessel information exists for every tow, CPUE density can be expressed
Eq. B.3	\({\delta _{yi}} = \frac{1}{{{n_{yi}}}}\,\,\sum\limits_{j = 1}^{{n_{yi}}} {\,\frac{{{C_{yij}}}}{{{D_{yij}}{w_{yij}}}}} \),	
where 	\({C_{yij}}\)	=	catch weight (kg) for tow \[j\], stratum \[i\], year \[y\];
	\({D_{yij}}\)	=	distance travelled (km) for tow\[j\], stratum\[i\], year\[y\];
	\({w_{yij}}\)	=	net opening (km) for tow\[j\], stratum\[i\], year\[y\];
	\({n_{yi}}\)	=	number of tows in stratum\[i\], year\[y\].
The annual biomass estimate is then the sum of the product of CPUE densities and bottom areas across \[m\] strata:
Eq. B.4	\[{B_y} = \sum\limits_{i = 1}^m {{\delta _{yi}}{A_i}}  = \sum\limits_{i = 1}^m {{B_{yi}}} \],	
where 	\({\delta _{yi}}\)	=	mean CPUE density (kg/km2) for stratum \[i\], year \[y\];
	\({A_i}\)	=	area (km2) of stratum\[i\];
	\({B_{yi}}\)	=	biomass (kg) for stratum\[i\], year\[y\];
	\[m\]	=	number of strata.
The variance of the survey biomass estimate \({V_y}\) (kg2) follows:
Eq. B.5	\({V_y} = \sum\limits_{i = 1}^m {\frac{{\sigma _{yi}^2A_i^2}}{{{n_{yi}}}}\,}  = \,\,\,\sum\limits_{i = 1}^m {{V_{yi}}} \),	
where 	\(\sigma _{yi}^2\)	=	variance of CPUE density (kg2/km4) for stratum \[i\], year \[y\];
	\({V_{yi}}\)	=	variance of the biomass estimate (kg2) for stratum\[i\], year \[y\].
The coefficient of variation (CV) of the annual biomass estimate for year \[y\] is
Eq. B.6	\(C{V_y} = \frac{{\sqrt {\,{V_y}} }}{{{B_y}}}\).

###  Data selection

