# Clean up the directory after a LaTeX build. Windows version
del *.aux
del *.bbl
del *.blg
del *.dvi
del *.log
del *.lot
del *.lof
del *.ps
del *.toc
del *.txt
del *.out
del *.snm
del *.nav
del *-concordance.tex
del *.synctex.gz*
del res-doc.tex
del res-doc.pdf
del Presentation.tex
del Presentation.pdf
