# INTRODUCTION

## STRUCTURE DU STOCK ET CYCLE BIOLOGIQUE

La morue du Pacifique (*Gadus macrocephalus*) est un membre de la famille des gadidés à la durée de vie relativement courte et à la croissance rapide. En Colombie-Britannique (C.-B.), elle est souvent appelée « morue grise ». Les populations de morue du Pacifique sont réparties de la Californie au golfe de l’Alaska, à la mer de Béring et jusqu’en Russie, en Corée, au Japon et en Chine, et occupent toutes les eaux de la Colombie-Britannique [@hart1973]. L’âge maximal observé en Colombie-Britannique est d’environ 10 à 11 ans [@westrheim1996, ce document], et d’environ 13 ans pour les stocks de l’Alaska [@roberson2001]. La longueur maximale enregistrée en Colombie-Britannique est de 100 cm [@hart1973], mais des spécimens plus gros ont été observés en Alaska et en Russie [@westrheim1996]. Lors des récents relevés synoptiques au chalut en Colombie-Britannique, la longueur maximale enregistrée était de 93 cm (annexe A, tableau \@ref(tab:length-biosamples-surv)). La morue du Pacifique est un reproducteur démersal, et plusieurs études indiquent que le frai a fort probablement lieu de février à mars. @westrheim1996 présente un examen complet de la biologie, du cycle biologique et de la répartition de la morue du Pacifique en Colombie-Britannique.

Quatre stocks de morue du Pacifique sont définis à des fins de gestion sur la côte de la Colombie-Britannique : le détroit de Georgie (4B); la côte ouest de l’île de Vancouver (3CD); le bassin de la Reine-Charlotte (5AB); et le détroit d’Hécate (5CD). La présente étude porte sur les populations du bassin de la Reine-Charlotte combinées à celles du détroit d’Hécate (5ABCD) et de la côte ouest de l’île de Vancouver (3CD) (figure \@ref(fig:fig-map)).

Des analyses génétiques récentes ont permis d’établir une distinction entre les populations de morue du Pacifique de l’Amérique du Nord et de l’Asie, de même qu’une certaine distinction entre les populations de l’Alaska et celles du sud de l’entrée Dixon en Colombie-Britannique [examen dans @forrest2013]. Certaines données probantes montrent aussi que les poissons pêchés au large de la côte de l’État de Washington et de la côte ouest de l’île de Vancouver pourraient être différents de ceux échantillonnés dans le détroit de Georgie ou dans la baie Puget. Toutefois, les liens, s’il en existe, entre les stocks de la Colombie-Britannique et de l’Alaska demeurent mal compris. À ce jour, on ne sait pas avec certitude s’il existe une structure génétique de la population dans les eaux de la Colombie-Britannique [@forrest2013]. Des échantillons génétiques ont été prélevés dans les frayères du détroit d’Hécate et du bassin de la Reine-Charlotte depuis l’évaluation de 2013, mais ils n’ont pas encore été analysés.

Le choix de fournir un avis scientifique pour les zones combinées 5AB et 5CD dans une seule évaluation des stocks était principalement attribuable à de mauvais diagnostics du modèle et à l’absence d’indices historiques de l’abondance indépendants de la pêche pour la zone 5AB [@forrest2013]. Il n’existe pas non plus de preuve d’une distinction génétique entre ces deux stocks. La fourniture d’avis scientifiques pour les zones 5ABCD combinées ne devrait pas sous-entendre que ces zones devraient être gérées comme une seule zone; ce choix revient aux gestionnaires des pêches, en consultation avec les membres de l’industrie de la pêche et les autres parties intéressées.

## CONSIDÉRATIONS ÉCOSYSTÉMIQUES

La dynamique des populations de morue du Pacifique en Colombie-Britannique est caractérisée par d’importantes variations estimées de l’abondance [p. ex. @sinclair2001; @forrest2013], bien que les causes n’en soient pas claires. Des hypothèses sont avancées pour expliquer l’abondance cyclique apparente dans le détroit d’Hécate : les cycles prédateur-proie [@walters1986], la croissance et la mortalité dépendantes de la densité [@fournier1983] et le transport des larves dans l’eau vers le nord [@tyler1986; @tyler1991]. La mortalité naturelle a été estimée comme atteignant 0,6-0,65 *a*^-1^ dans certaines évaluations des stocks [p. ex. @fournier1983; @sinclair2005], bien que des estimations plus basses (~0,4 *a*^-1^) aient également été obtenues [@sinclair2001; @forrest2013]. La combinaison d’une dynamique apparemment volatile avec une courte durée de vie et une mortalité naturelle élevée donne à penser que des périodes de surexploitation ou de sous-exploitation pourraient se produire si les stratégies de récolte ne sont pas solides par rapport à ces caractéristiques. De plus, dans le contexte de la pêche intégrée du poisson de fond en Colombie-Britannique, une approche monospécifique ne dicte pas nécessairement la meilleure stratégie de récolte du fait des contraintes imposées par les quotas pour d’autres espèces et les considérations économiques.

### PROIES ET PRÉDATEURS

La morue du Pacifique est omnivore, se nourrissant principalement d’invertébrés marins, y compris d’amphipodes, d’euphausiacés, de crevettes et de crabes. Lorsqu’elle atteint une longueur d’environ 50 à 55 cm, elle devient également piscivore et le lançon (*Ammodytes hexapterus*) et le hareng du Pacifique (*Clupea pallasi*) composent alors une partie importante de son alimentation [@westrheim1996]. La morue charbonnière juvénile (*Anoplopoma fimbria*) et le merlu du Chili adulte (*Merluccius productus*) ont également été signalés dans le régime alimentaire de la morue du Pacifique au large de la côte ouest de l’île de Vancouver (@ware1986). La morue du Pacifique est la proie du flétan du Pacifique (*Hippoglossus stenolepis*), de l’aiguillat commun du Pacifique Nord (*Squalus suckleyi*), des oiseaux de mer, des phoques et des otaries [@westrheim1996].

@walters1986 ont démontré une interaction de type prédateur-proie entre le hareng et la morue du Pacifique dans le détroit d’Hécate, contrairement à @ware1986. Les modèles de simulation élaborés par @walters1986 ont mené à la conclusion que la disponibilité du hareng du Pacifique en tant que proie pourrait être un facteur important de la production de morue du Pacifique dans le détroit d’Hécate. De même, la prédation par la morue du Pacifique pourrait être un facteur important de l’abondance du hareng du Pacifique. Ces auteurs ont reconnu que d’autres hypothèses peuvent expliquer les cycles d’abondance de la morue du Pacifique et du hareng du Pacifique (p. ex. le forçage environnemental; voir ci-après) et ont suggéré que des expériences de gestion à grande échelle seront peut-être la seule façon de distinguer les hypothèses concurrentes.

### ENVIRONNEMENT


Plusieurs études ont examiné les liens entre le recrutement et les indices environnementaux pour la morue du Pacifique dans le détroit d’Hécate (voir l'examen dans @westrheim1996). L’hypothèse dominante est une relation inverse entre le recrutement et l’advection des larves vers le nord [@tyler1986; @tyler1991]. Il a été démontré que l’advection vers le nord est positivement corrélée avec le niveau moyen annuel de la mer à Prince Rupert pendant la saison du frai, qui à son tour a été utilisé comme variable explicative pour le recrutement par un certain nombre d’auteurs [@fournier1983; @sinclair2000; @sinclair2005-2; @sinclair2005]. Toutefois, de récentes mises à jour des analyses effectuées par @tyler1991 n’ont pas permis de trouver une corrélation continue entre le niveau de la mer à Prince Rupert et le recrutement de la morue du Pacifique dans le détroit d’Hécate (R. Forrest, Station biologique du Pacifique, données inédites). Cela pourrait être dû en partie aux quotas bas (et donc aux prises plus faibles) depuis 2001, contribuant aux estimations basses du recrutement tirées de l’évaluation des stocks ces dernières années [@forrest2013].

### AUTRES ESPÈCES

D’autres espèces sont capturées avec la morue du Pacifique, notamment la plie à grande bouche (*Atheresthes stomias*), le sébaste à queue jaune (*Sebastes flavidus*), le sébaste à longue mâchoire (*S. alutus*), la morue-lingue (*Ophiodon elongatus*), le sébaste argenté (*S. brevispinis*), le carlottin anglais (*Parophrys vetulus*) et la raie biocellée (*Raja binoculata*) [@forrest2013]. Les navires qui pêchent la morue du Pacifique doivent détenir un quota pour toutes les espèces contingentées rencontrées [@dfo2017]. Depuis 1996, le niveau de présence des observateurs en mer est de 100 % à bord des chalutiers de fond commerciaux en Colombie-Britannique. Les observateurs consignent les rejets en mer et les imputent au quota du bateau, selon les taux convenus de mortalité des rejets.

### PÊCHES

En Colombie-Britannique, la morue du Pacifique est capturée presque entièrement dans la pêche au chalut de fond du poisson de fond, dans le cadre de la pêche intégrée du poisson de fond de la province [@dfo2017]. La morue du Pacifique est l’une des principales espèces ciblées par la pêche au chalut dans le détroit d’Hécate. À l’heure actuelle, la plus grande partie des prises de morue du Pacifique en Colombie-Britannique provient du détroit d’Hécate (zone 5CD) (figures \@ref(fig:fig-catch-5ab),\@ref(fig:fig-catch-5cd) et \@ref(fig:fig-catch-3cd)).

La morue du Pacifique est répartie dans tout le détroit d’Hécate (zone 5CD), essentiellement à des profondeurs de moins de 150 m. Sa densité semble être la plus élevée sur les lieux de pêche de Two Peaks/Butterworth, White Rocks, Shell Ground, l’île Reef et Horseshoe [annexes \@ref(app:fishery-independent-indices-of-abundance) et \@ref(app:commercial-cpue-standardization), @forrest2013]. Dans le bassin de la Reine-Charlotte (zone 5AB), la morue du Pacifique est pêchée principalement au large du cap Scott et des bancs Mexicana, au nord de l’île de Vancouver, dans la zone 5A, et autour de la lisière du banc de l’île Goose, dans la zone 5B [annexes \@ref(app:fishery-independent-indices-of-abundance) et \@ref(app:commercial-cpue-standardization), @forrest2013]. La tranche d’eau des captures dans la zone 5ABCD est d’environ 60 à 200 m, les données montrant un déplacement vers des profondeurs plus grandes depuis 1996 (annexe B, figure \@ref(fig:cpue-depth-hists)). La transition vers des lieux de pêche plus profonds reflète une plus grande proportion de prises provenant des eaux plus profondes du bassin de la Reine-Charlotte ces dernières années (figures \@ref(fig:fig-catch-5ab) et \@ref(fig:fig-catch-5cd)). Les prises annuelles déclarées de morue du Pacifique dans le détroit d’Hécate et le bassin de la Reine-Charlotte affichent une variabilité considérable depuis le début de la série chronologique en 1956 (figure \@ref(fig:fig-catch-5abcd)). La tranche d’eau des prises au large de la côte ouest de l’île de Vancouver (zone 3CD) est semblable à celle de la zone 5ABCD, la majorité des prises provenant de zones de 50 à 200 m de profondeur (annexe B, figure \@ref(fig:cpue-depth-hists)). Voir la description des changements des tranches d’eau historiques de la pêche dans @sinclair2001. Voir aussi l’annexe B. Les prises historiques dans la zone 3CD ont suivi un profil variable semblable à celui de la zone 5ABCD (figure \@ref(fig:fig-catch-3cd))

Avant la mise en place de la couverture par les observateurs en mer en 1996, les estimations des rejets en mer (rejets) pour la période 1956-1995 étaient tirées des journaux de bord des bateaux de pêche. Elles sont considérées comme une sous-estimation des rejets réels (tableaux \@ref(tab:tab-catch-5abcd) et \@ref(tab:tab-catch-3cd)). Les estimations des années qui ont suivi l’introduction du niveau de présence de 100 % des observateurs en mer en 1996 peuvent être considérées comme exactes. Depuis 1996, les proportions des rejets estimés sont considérablement plus élevées que celles des années qui ont précédé la mise en place des observateurs en mer (tableaux \@ref(tab:tab-catch-5abcd) et \@ref(tab:tab-catch-3cd)), surtout dans le bassin de la Reine-Charlotte, en grande partie en raison de la réduction des prises totales et des TAC (tableau \@ref(tab:tab-tac)). Les chalutiers ont le droit de rejeter la morue du Pacifique en Colombie-Britannique. Toutefois, les observateurs à bord estiment d’abord la quantité rejetée. Ainsi, en plus d’une plus grande exactitude dans la déclaration des rejets depuis 1996, les mesures incitatives pour éviter les rejets sont également plus importantes.

Des navires japonais et soviétiques ont également pêché au chalut au large de la Colombie-Britannique à la fin des années 1960 et au début des années 1970. Ces navires ciblaient principalement le sébaste, et ce, probablement à des profondeurs supérieures à 150 m. Les prises accessoires de morue du Pacifique dans ces pêches sont toutefois inconnues. Étant donné l’incertitude relative aux prises et aux rejets étrangers dans les premières tranches de la série chronologique, les estimations des prises totales devraient être considérées comme des sous-estimations avant 1996.

L’effort total de pêche des chalutiers de fond a diminué dans toutes les régions ces dernières années. Une analyse détaillée des captures par unité d’effort (CPUE) est présentée à l’annexe B. Comme il est indiqué dans @sinclair2000, l’utilisation des captures commerciales par unité d’effort comme indice de la biomasse pour la morue du Pacifique pose un certain nombre de problèmes. Les changements apportés au régime de gestion, qui est passé d’une pêche sans restriction avant 1992 à l’introduction des TAC (1992-1996), puis à des quotas individuels de bateau (QIB) (1997-aujourd’hui), ainsi que plusieurs augmentations de la taille du maillage [@forrest2013, leur tableau 5] ont influencé la relation sous-jacente entre les captures commerciales par unité d’effort et l’abondance, de même que la relation entre l’effort de pêche et la mortalité par pêche. Au cours des dernières années, avec les quotas de morue du Pacifique plus bas (tableau \@ref(tab:tab-tac)), de nombreux capitaines de bateau de pêche déclarent avoir activement évité la morue du Pacifique pour éviter de dépasser leur quota de cette espèce avant d’avoir capturé les quotas disponibles pour d’autres espèces. Dans la présente évaluation, les séries de CPUE sont divisées en séries avant et après 1996, et nous utilisons des modèles linéaires généralisés mixtes pour tenter de normaliser les indices (annexe \@ref(app:commercial-cpue-standardization)).

### HISTORIQUE DES ÉVALUATIONS

Un certain nombre de méthodes ont été utilisées pour évaluer la morue du Pacifique dans le détroit d’Hécate depuis les années 1980. @fournier1983 a mis au point un modèle structuré selon l’âge qu’il a utilisé pour mettre à l’essai des données probantes sur les tendances de la mortalité naturelle dépendante de l’âge, de la mortalité naturelle dépendante de la densité et de la capturabilité, ainsi que pour démontrer l’incidence d’un facteur environnemental sur le recrutement. On a constaté une relation entre le niveau moyen de la mer à Prince Rupert et le recrutement, ainsi qu’une mortalité naturelle dépendante de la densité. @fournier1983 a estimé la mortalité naturelle à 0,65 *a*^-1^. Cet auteur a mis en garde contre la possibilité de confusion entre les paramètres du modèle et les biais de données systématiques qui pourraient influencer les conclusions de l’analyse. Les estimations de l’âge ont été tirées de l’analyse de la fréquence des longueurs [@foucher1982].

La morue du Pacifique est l’une des espèces de poissons de fond du Pacifique dont l’âge est le plus difficile à déterminer. Les anneaux annuels (annuli) des otolithes, les autres structures osseuses et les écailles sont difficiles à distinguer des anneaux de croissance interannuels [@beamish1981; @chilton1982; @roberson2001; @johnston2012]. En Colombie-Britannique, les compositions selon l’âge ont été estimées à l’aide d’approches fondées sur la longueur, des écailles, des otolithes et, actuellement, de coupes des rayons des nageoires dorsales, bien que toutes les méthodes présentent des difficultés. En l’absence de données directes fiables sur l’âge, des approches fondées sur la longueur ont été utilisées pour évaluer le stock du détroit d’Hécate dans les années 1990 [p. ex. @haist1995; @haist1998]. Dans cette dernière référence, @haist1998 a indiqué que le stock avait atteint un creux historique en 1996, suivi d’une légère remontée.

@sinclair2000 a utilisé un modèle de production excédentaire simple ajusté à un indice des captures commerciales par unité d’effort pour évaluer le stock de la zone 5CD en 2000. Cet auteur a expliqué que les changements structurels importants intervenus dans la pêche au cours des années 1990 ont entraîné des changements dans la qualité et la comparabilité des données dépendantes de la pêche disponibles pour l’analyse. Ces changements comprenaient les augmentations volontaires de la taille du maillage dans la pêche commerciale et l’introduction des quotas individuels de bateau (QIB) en 1997, comme nous l ‘avons déjà mentionné. Compte tenu des grandes différences structurelles entre les modèles précédents fondés sur la longueur et le modèle de production excédentaire, @sinclair2000 a noté que les résultats étaient remarquablement comparables jusqu’en 1994, avec trois pics d’abondance estimés en 1965, 1974-1975 et 1986-1987. Les deux approches divergent considérablement après 1994, le modèle Multifan fondé sur la longueur [@haist1998] donnant une augmentation de la biomasse, tandis que le modèle de production excédentaire estimait une diminution. Ces différences ont été interprétées comme étant attribuables aux différences dans les indices de l’abondance utilisés pour régler les modèles, ainsi qu’aux différences structurelles des modèles.

@sinclair2001 a élaboré un modèle de type différence-délai [@deriso1980; @schnute1985] contenant une fonction de Ricker pour le stock-recrutement afin d’évaluer la morue du Pacifique dans les zones 3CD et 5CD. Le recrutement était présumé en lame de couteau à l’âge de 2 ans. Une fiche sommaire des renseignements disponibles pour le stock a également été élaborée. Le modèle de type différence-délai a fourni une meilleure correspondance statistique aux données que le modèle de production excédentaire appliqué antérieurement [@sinclair2000]. Toutefois, les estimations de la biomasse affichaient une tendance et une ampleur semblables. Le stock de la zone 3CD de 2001 a été mis à jour en 2002 [@Starr2002] en reprenant le modèle de type différence-délai élaboré l’année précédente [@sinclair2001] et en ajoutant les données du relevé du MPO au chalut sur la crevette. Les auteurs de l’évaluation de 2002 ont noté que les points de référence estimés fondés sur le rendement maximal soutenu, *F*~RMS~ et *B*~RMS~, n’étaient pas bien estimés [@Starr2002].

L’évaluation de la zone 5CD a été mise à jour en 2004 [@sinclair2005] à l'aide d’un modèle de type différence-délai semblable à celui utilisé par @sinclair2001, mais en utilisant une fonction de Beverton-Holt pour le stock-recrutement. Des ajustements du modèle ont été présentés avec d’autres combinaisons de la mortalité naturelle (*M*) fixe ou estimée et du paramètre de pente de la fonction stock-recrutement, *h* (Mace et Doonan 1988). Ces auteurs ont déclaré des ajustements et des estimations de la biomasse semblables pour les deux scénarios, mais ont noté des estimations très différentes des paramètres de gestion de l’équilibre fondés sur le RMS avec d’autres combinaisons des valeurs fixes et estimées de *h* et de *M*. Ils ont proposé des points de référence « fondés sur l’historique », basés sur des estimations de la biomasse et de la mortalité par pêche historiques, en raison du manque de fiabilité des points de référence fondés sur le RMS. Les stocks des zones 5AB et 5CD ont été évalués pour la dernière fois en 2013 [@forrest2013] à l’aide d’un nouveau modèle de type différence-délai avec une fonction de Beverton-Holt pour le stock-recrutement et l’hypothèse de la sélectivité en lame de couteau à 2 ans. Ce modèle présentait quelques différences structurelles mineures par rapport à l’évaluation précédente, bien que les analyses de transition aient montré qu’elles avaient un effet relativement mineur [@forrest2013, leur annexe A]. L’évaluation de 2013 a adopté les mêmes points de référence historiques que ceux qui avaient été utilisés en 2004 et qui avaient été acceptés lors de l’examen par les pairs pour la zone 5CD [@dfo2015]. Toutefois, aucun point de référence n’a été accepté pour la zone 5AB [@dfo2015-2]. Les principales incertitudes relevées par @forrest2013 étaient les suivantes :

1. l’incertitude des paramètres de variance fixes, en particulier l’erreur d’observation présumée dans les relevés, et la composante de la fonction objective de l’ajustement aux poids moyens annuels;
2. la fiabilité des captures commerciales par unité d’effort comme indice de l’abondance et les effets des changements de gestion après 1996 sur les CPUE;
3. l’incertitude dans la distribution de la probabilité a priori utilisée pour la mortalité naturelle *M*;
4. l’incertitude dans la fonction de croissance (paramètres du modèle et hypothèses de stationnarité);
5. la possibilité de contredire l’hypothèse du recrutement en lame de couteau à l’âge de 2 ans, compte tenu des éléments probants concernant des poissons plus jeunes dans les données sur la composition selon la longueur provenant de la pêche commerciale;
6. l’incertitude dans la structure des stocks.

@forrest2013 a partiellement abordé la sensibilité aux trois premières incertitudes en présentant des analyses de sensibilité et d’autres tableaux de décision fondés sur la « moyenne des modèles » pour les zones 5AB et 5CD. La présente évaluation prend partiellement en compte les quatrième et cinquième incertitudes par l’ajout d’analyses de sensibilité supplémentaires comparant les paramètres de croissance précédents et mis à jour, et comparant les résultats avec l’hypothèse de la sélectivité en lame de couteau (section \@ref(sec:sensitivity-analyses). La sixième est encore une incertitude clé pour la morue du Pacifique. Dans la présente évaluation, les données des zones 5AB et 5CD sont combinées, en partant de l’hypothèse que les morues du Pacifique du bassin de la Reine-Charlotte et du détroit d’Hécate appartiennent à un seul stock.

# SOURCES DE DONNÉES {#sec:data-sources}

## BASES DE DONNÉES

Les données ont été extraites d’un certain nombre de bases de données différentes :

**GFBio** :
Base de données sur les échantillons biologiques et les campagnes de recherche. Section du poisson de fond, Division des écosystèmes marins et de l’aquaculture, Direction générale des sciences, Pêches et Océans Canada, Station biologique du Pacifique. Cette archive de données comprend la plupart des données sur les spécimens de poissons de fond recueillies depuis les années 1950. Elle renferme donc des données provenant de diverses sources (échantillonnage commercial dans les ports et en mer, échantillonnage des relevés de recherche), collectées à l’aide de diverses méthodes d’échantillonnage.

**GFCatch** :
Débarquements des chalutiers au Canada, 1954-1995 [@rutherford1999].

**PacHarvTrawl** :
Débarquements des chalutiers au Canada, de 1996 au 31 mars 2007. Base de données SQL Server, Section du poisson de fond, Division des écosystèmes marins et de l’aquaculture, Direction générale des sciences, Pêches et Océans Canada, Station biologique du Pacifique.

**GFFOS** :
Débarquements des chalutiers au Canada, du 1er avril 2007 à 2017. Vue de la base de données des Opérations des pêches (FOS) de Pêches et Océans Canada (MPO). Section du poisson de fond, Division des écosystèmes marins et de l’aquaculture, Direction générale des sciences, Pêches et Océans Canada, Station biologique du Pacifique.

### DONNÉES SUR LES PRISES

Les pêches du poisson de fond ont été gérées par année civile jusqu’en 1996. Depuis 1997-1998, l’année de pêche a été changée, du 1er avril au 31 mars. En 2010-2011, elle a été modifiée de nouveau et a passé du 21 février au 20 février. Tout au long du présent document, comme dans @forrest2013, les années de pêche sont définies comme commençant le 1er avril pour toutes les années, et sont mentionnées par année de début (p. ex. l’année de pêche 1957 va du 1er avril 1957 au 31 mars 1958). Ces définitions ont été utilisées de façon uniforme dans tous les calculs concernant les données sur les prises commerciales, y compris l’élaboration de l’indice des CPUE commerciales (annexe \@ref(app:commercial-cpue-standardization)) et le calcul de la moyenne annuelle du poids moyen des prises (annexe \@ref(app:analysis-of-biological-data)). Les données sur les débarquements sont présentées séparément pour le Canada et les États-Unis (tableaux \@ref(tab:tab-catch-5abcd) et \@ref(tab:tab-catch-3cd)). Les données combinées sur les débarquements des États-Unis et du Canada ont été tirées des rapports de la Commission des pêches maritimes du Pacifique pour 1956-1981, et la portion des débarquements aux États-Unis a été déterminée en soustrayant la quantité des débarquements au Canada du total combiné pour chaque année. Dans les cas où la différence était négative, la quantité des débarquements aux États-Unis a été fixée à zéro. Les données canadiennes proviennent de la base de données GFCatch pour la période 1954-1995 [@rutherford1999], de la base de données PacHarvest pour la période de 1996 au 31 mars 2007, et de la base de données FOS de Pêches et Océans Canada (MPO) depuis le 1er avril 2007. Les compositions annuelles selon la taille des prises commerciales et des débarquements ont été estimées à partir des échantillons, prélevés au port et en mer par des observateurs et archivés dans la base de données GFBio (annexe \@ref(app:analysis-of-biological-data)).

## INDICES DE L’ABONDANCE

Les modèles d’évaluation des stocks dans la zone 5ABCD ont été ajustés à trois indices de relevés indépendants de la pêche (relevé de la communauté d’espèces ou multispécifique dans le détroit d’Hécate, relevé synoptique dans le détroit d’Hécate et relevé synoptique dans le bassin de la Reine-Charlotte) et à deux indices des CPUE commerciales tirés des données sur les captures commerciales et l’effort au chalut de fond (avant 1996 et après 1995).

Les modèles d’évaluation des stocks dans la zone 3CD ont été ajustés à deux indices de relevés indépendants de la pêche (relevé synoptique sur la côte ouest de l’île de Vancouver et relevé triennal du NMFS au Canada) et deux indices des CPUE commerciales tirés des données sur les captures commerciales et l’effort au chalut de fond (avant 1996 et après 1995).

Les indices de l’abondance indépendants de la pêche ont été élaborés à l’aide d’analyses de la superficie balayée. Des détails sont donnés à l’annexe \@ref(app:fishery-independent-indices-of-abundance).

Les indices des CPUE commerciales ont été normalisés pour la profondeur, le lieu de pêche, le mois, le navire et la latitude, lorsque ces données étaient disponibles, à l’aide de modèles linéaires généralisés à effets mixtes (MLGM), selon une distribution de Tweedie. Des détails sont fournis à l’annexe \@ref(app:commercial-cpue-standardization).

## DONNÉES BIOLOGIQUES

Les mises à jour des estimations de la croissance, de la maturité et des poids moyens annuels dans les prises commerciales sont indiquées à l’annexe \@ref(app:analysis-of-biological-data).

# MODÈLE D’ÉVALUATION DES STOCKS {#sec:stock-assessment-model}

Tous les modèles présentés dans ce document sont des modèles bayésiens mis en œuvre dans AD Model Builder [@fournier2012]. Les modèles sont fondés sur le modèle statistique intégré des prises selon l’âge (iSCAM), présenté pour la première fois dans @martell2011. Les auteurs de @forrest2013 et de la présente évaluation y ont apporté une modification majeure en incluant des calculs de la différence-délai. Dans sa formulation actuelle, le modèle est entièrement décrit à l’annexe \@ref(app:delay-difference-model). Il existe deux différences importantes entre le modèle actuel et l’évaluation précédente [@forrest2013] :

1. Le modèle actuel n’estime qu’un paramètre de recrutement moyen ($R_{0}$). Les modèles décrits dans @forrest2013 et @martell2011 estimaient trois paramètres de recrutement moyen :

  - $R_{0}$, le recrutement non exploité moyen utilisé dans le calcul des paramètres du stock-recrutement;
  - $R_{Init}$, le recrutement moyen initial utilisé pour initialiser la structure selon l’âge la première année;
  - $R_{Avg}$, le recrutement moyen pour la série chronologique.

Nous avons décidé d’utiliser un seul paramètre de recrutement moyen parce qu’il y a peu ou pas d’information pour estimer trois paramètres dans le modèle de type différence-délai, qui ne contient aucune information explicite sur la composition selon l’âge.

De plus, les paramètres de croissance de von Bertalanffy ont été mis à jour dans la présente évaluation pour les deux stocks, afin de refléter les données plus récentes sur l’âge et la longueur. Les détails se trouvent à l’annexe \@ref(app:analysis-of-biological-data).

Les modèles de référence pour les évaluations des zones 5ABCD et 3CD sont examinés de manière plus détaillée à la section \@ref(sec:reference-case-models).

# POINTS DE RÉFÉRENCE {#sec:reference-points}

Le cadre décisionnel pour les pêches intégrant l’approche de précaution du MPO [@dfo2009] exige que l’état des stocks soit caractérisé à l’aide de trois points de référence :

1. Un taux d’exploitation de référence;
2. Un point de référence limite (PRL);
3. Un point de référence supérieur du stock (PRS).

Dans la présente évaluation, ces points de référence sont intégrés aux tableaux de décision (section \@ref(sec:projections-and-decision-tables)), où les probabilités projetées de dépassement des points de référence sont indiquées, c.-à-d. que les points de référence ne sont pas incorporés dans une règle officielle de contrôle des prises.

Des valeurs provisoires de $USR = 0,8 B_{MSY}$ et de $LRP = 0,4 B_{MSY}$ sont proposées en l’absence de points de référence propres au stock [@dfo2009]. Le cadre précise un taux d’exploitation de référence limite de $F_{MSY}$. Tout au long du présent document, nous désignons le taux d’exploitation de référence comme étant le taux d’exploitation limite (TEL). La politique de l’AP approuve également les approximations « fondées sur l’historique » basées sur une estimation de la biomasse féconde moyenne et de la mortalité par pêche sur une période historique productive [@dfo2009].

Comme il a déjà été mentionné, les importantes incertitudes qui entourent les paramètres de productivité *M* et *h* ont entraîné de grandes incertitudes concernant les points de référence fondés sur le RMS pour le stock de morue du Pacifique du détroit d’Hécate dans les évaluations antérieures [@Starr2002; @sinclair2005; @forrest2013]. Compte tenu de l’incertitude des paramètres de productivité pour ce stock, @sinclair2005 a suggéré d’utiliser d’autres points de référence fondés sur l’historique reconstitué du stock, c.‑à‑d. les points de référence « fondés sur l’historique ». Il a recommandé de prendre pour point de référence limite la biomasse féconde minimale à partir de laquelle le stock s’est rétabli au-dessus des niveaux moyens. On a estimé que cela s’était produit en 1971 (c.-à-d. $LRP = B_{1971}$). @sinclair2005 a aussi proposé d’utiliser la biomasse moyenne à long terme (B_$B_{Avg}$) comme variable de remplacement pour le point de référence supérieur du stock et le taux de récolte moyen à long terme ($U_{Avg}$) comme substitut pour le taux d’exploitation de référence.

@sinclair2005 et @forrest2013 ont reconnu que l’estimation absolue de la biomasse en 1971 dépend de la formulation du modèle, mais ont constaté que, dans la plupart des formulations de modèles, 1971 était l’année où le stock était le plus bas et s’est ensuite rétabli au-dessus des niveaux moyens. C’est pourquoi ils ont recommandé de fixer le PRL à $B_{1971}$, selon l’estimation du modèle d’évaluation. Le Sous-comité du poisson de fond du CEESP [@fargo2005] a par la suite recommandé d’utiliser $B_{1971}$ comme PRL pour le stock du détroit d’Hécate et un processus régional d’examen par les pairs a de nouveau accepté cette valeur comme PRL pour la zone 5CD en 2014 [@dfo2015]. Parallèlement, le processus régional d’examen par les pairs a accepté la biomasse moyenne à long terme ($B_{Avg}$) entre 1956 et 2004 comme PRS, et la mortalité par pêche moyenne à long terme ($F_{Avg}$) comme TEL pour la même période [@dfo2015].

Bien qu’il n’existe pas de précédent pour les points de référence dans le bassin de la Reine-Charlotte, la taille minimale du stock à partir de laquelle on a estimé que la biomasse s’était rétablie au-dessus d’un niveau moyen a été enregistrée en 1985 [@forrest2013]. Ces auteurs ont proposé $B_{1985}$ comme PRL pour le bassin de la Reine-Charlotte, avec la biomasse et la mortalité par pêche moyennes pour la période 1956-2004 comme PRS et TEL, respectivement. Toutefois, le processus régional d’examen par les pairs n’a accepté aucun point de référence pour le stock de morue du Pacifique du bassin de la Reine-Charlotte (zone 5AB) [@dfo2015-2]. La principale raison invoquée était que la pêche dans la zone 5AB était devenue une pêche « d’évitement » pour la morue du Pacifique (pour éviter de dépasser le TAC de la morue du Pacifique avant d’avoir atteint les TAC d’autres espèces de poisson de fond). Les participants au processus régional d’examen par les pairs ont donc jugé qu’il n’était pas possible de présumer que les estimations de l’abondance après 1996, qui s’appuyaient en grande partie sur les faibles prises, reflétaient l’abondance avec exactitude.

@forrest2018 ont testé en simulation un ensemble d’autres points de référence pour la morue du Pacifique et la fausse limande (*Lepidopsetta* spp.) du détroit d’Hécate. Ils ont constaté que les points de référence « fondés sur l’historique » (ou points de contrôle opérationnels, PCO) qui avaient été utilisés pour la morue du Pacifique en 2013 [@forrest2013] résistaient bien aux biais de l’évaluation des stocks parce qu’ils s’échelonnaient dans la même direction que le biais dans les estimations de la biomasse et de la mortalité par pêche. Cependant, ils ne constituaient pas nécessairement de bons substituts pour les points de référence basés sur le RMS et avaient tendance à produire des recommandations de prises plus prudentes que les points de référence fondés sur $B_{MSY}$, $B_{0}$ et le ratio du potentiel de frai (RPF; @clark1991). Bien que les points de référence « fondés sur l’historique » aient donné de meilleurs résultats pour la conservation à long terme que les autres, il y a parfois eu d’importants compromis en ce qui concerne les prises et la stabilité des prises [@forrest2018]. Les points de référence fondés sur $B_{0}$ ont produit des résultats semblables aux points de référence « fondés sur l’historique », mais avaient tendance à avoir de meilleures propriétés en ce qui concerne les compromis [@forrest2018].

Nous avons peut-être réglé certaines des préoccupations relatives aux points de référence du modèle de la zone 5AB en combinant les données des zones 5AB et 5CD dans la présente évaluation des stocks. Par conséquent, nous suggérons d’utiliser le même PRS pour la zone 5ABCD que celui appliqué pour la zone 5CD dans [@forrest2013]. Durant la réunion d’examen de la présente évaluation, les examinateurs et les participants ont décidé de modifier le PRL et d’utiliser la biomasse estimée la plus faible reconnue comme représentant un état non souhaitable à éviter. Cette modification a été motivée par la modulation limitée des estimations de la biomasse ces dernières années (de 1992 à aujourd’hui) jugée acceptable par le comité. La modification de la définition a mené à l’utilisation de la faible biomasse en 2000 comme point de référence limite pour cette évaluation (c.-à-d. $LRP = B_{2000}$).

En l’absence de points de référence acceptés pour la zone 3CD, nous suggérons d’appliquer la même approche. Nous avons conservé comme PRL la biomasse en 1986, comme dans l’évaluation précédente, car il a été convenu que sa modification aurait un effet négligeable. En plus du TEL, du PRL et du PRS dont il a été question plus haut, deux points de repère sont également inclus : (i) $F_{2017}$ et (ii) $B_{2018}$. Les projections de la biomasse et de la mortalité par pêche par rapport à ces points de repère sont incluses dans les tableaux de décision pour montrer si : (i) la mortalité par pêche devrait augmenter ou diminuer selon les autres niveaux de prises projetés pour 2018; et (ii) si la biomasse devrait augmenter ou diminuer selon les autres niveaux de prises projetés pour 2018.

Les points de référence et les points de repère suggérés pour les deux zones sont indiqués dans le section \@ref(sec:reference-points-and-decision-tables).

# MODÈLES DU SCÉNARIO DE RÉFÉRENCE {#sec:reference-case-models}

Les modèles du scénario de référence pour les zones 5ABCD et 3CD présentaient des caractéristiques semblables en ce qui concerne les choix de données, les distributions de probabilité a priori et les réglages des paramètres fixes. Dans un souci de concision, les deux modèles de scénario de référence sont décrits dans cette section, et les différences sont expliquées au besoin. Le modèle bayésien de type différence-délai est décrit en détail à l’annexe \@ref(app:delay-difference-model).

La distribution conjuguée a posteriori pour chaque modèle a été estimée numériquement à l’aide de routines de Monte Carlo par chaînes de Markov intégrées dans AD Model Builder (algorithme de Metropolis-Hastings) [@fournier2012]. Des échantillons a posteriori ont été tirés à chaque 5 000e itération d’une chaîne longue de 10 millions, ce qui a donné 2 000 échantillons a posteriori (les 1 000 premiers échantillons ont été omis pour permettre un rodage suffisant). Nous avons évalué la cohérence avec la convergence de la chaîne en inspectant visuellement les graphiques des traces et les graphiques d’autocorrélation et en calculant la statistique de réduction d'échelle potentielle $\hat{R}$ et le nombre réel de tirages dans la simulation $n_\mathrm{eff}$ au moyen du progiciel Stan en R [@rstan2018].

<!-- https://github.com/stan-dev/stan/blob/238faf42b556c007197c9faca20214ad9b37f0b2/src/docs/reference-manual/analysis.Rmd -->

La statistique de réduction d’échelle potentielle [@gelman1992] est un paramètre courant, utilisé dans les statistiques bayésiennes pour évaluer la convergence des chaînes [@gelman2014; @hobbs2015; @stan-manual2017]. La statistique mesure le ratio de la variance moyenne des échantillons de MCCM dans chaque chaîne par rapport à la variance des échantillons dans l’ensemble des chaînes. À mesure que $\hat{R}$ approche de 1,0, les chaînes deviennent convergentes. Dans notre cas, nous n’avions qu’une seule chaîne pour chaque passe du modèle, mais en suivant les conseils donnés dans @gelman2014, nous avons d’abord divisé la chaîne en deux, en traitant effectivement la première et la deuxième moitié comme des chaînes séparées. Selon la notation de @hobbs2015, nous pouvons calculer $\hat{R}$ pour un paramètre donné $\theta$ comme suit. Pour les chaînes $j = 1, ..., m$ (deux demi-chaînes ici), nous calculons la moyenne des variances $w$ selon la formule :

$$
w=\frac{1}{m}\sum_{j=1}^{m}\operatorname{var}\left(\theta_{j}\right)
$$

où $\theta_{j}$ est défini comme
$\theta_{j}=\frac{1}{K-1}\sum_{n=1}^{K}\left(\theta_{kj}-\overline{\theta}_{j}\right)^{2}$ sur $k = 1, ..., K$ itérations. Nous définissons ensuite la variance entre les chaînes $b$ comme suit :

$$
b=\frac{K}{m-1}\sum_{j=1}^{m}\left(\overline{\theta}_{j}-\overline{\overline{\theta}}\right)^{2}
$$

où
$\overline{\overline{\theta}}=\frac{1}{m}\sum_{j=1}^{m}\overline{\theta}_{j}$.
La variance d’une distribution stationnaire de$\theta$ est ensuite calculée comme une moyenne pondérée
$\sigma_{\theta}^{2}=\left(1-\frac{1}{K}\right)w+\frac{1}{K}b$,
et nous pouvons définir le facteur de réduction d’échelle potentiel comme$\hat { R } = \sqrt{\frac{\sigma_{ \theta}^{2}}{w}}$.

La statistique $n_\mathrm{eff}$ mesure le nombre réel d’échantillons indépendants MCCM après la prise en compte de l’autocorrélation. Dans un souci de concision, nous ne définissons pas ici le calcul complet, mais celui-ci est disponible dans [@gelman2014 p.286-287] ou [@stan-manual2017 p. 373-376].

## CHOIX DES DONNÉES

Les deux modèles ont été ajustés aux données sur les prises observées, à la moyenne du poids moyen annuel observé dans les prises commerciales et aux indices de l’abondance indépendants et dépendants de la pêche. Des détails sur les composantes des fonctions objectives du modèle sont fournis à l’annexe \@ref(app:delay-difference-model).

Les sources des données sur les prises observées sont décrites à la section \@ref(sec:data-sources), et les valeurs sont indiquées dans les tableaux \@ref(tab:tab-catch-5abcd) et \@ref(tab:tab-catch-3cd), ainsi que sur les figures \@ref(fig:fig-catch-5abcd) à \@ref(fig:fig-discards-5cd) pour la zone 5ABCD et sur les figures  \@ref(fig:fig-catch-3cd) à \@ref(fig:fig-discards-3cd) pour la zone 3CD.

Les indices de l’abondance d’après la superficie balayée, indépendants de la pêche, sont documentés à l’annexe \@ref(app:fishery-independent-indices-of-abundance), y compris les estimations de la biomasse, les CV et les années couvertes.

Pour la zone 5ABCD, il s’agit des relevés suivants :

1. le relevé de la communauté d’espèces ou multispécifique dans le détroit d’Hécate;
2. le relevé synoptique dans le bassin de la Reine-Charlotte;
3. le relevé synoptique dans le détroit d’Hécate.

Pour la zone 3CD, il s’agit des relevés suivants :

1. le relevé synoptique sur la côte ouest de l’île de Vancouver;
2. le relevé triennal du NMFS (au Canada).

Les indices dépendants des pêches sont entièrement documentés à l’annexe \@ref(app:commercial-cpue-standardization). Dans chaque zone, les séries chronologiques des CPUE sont des modèles linéaires généralisés à effets mixtes (MLGM) normalisés, avec des analyses distinctes pour les périodes avant et après la mise en place du niveau de présence à 100 % des observateurs en mer en 1996, qui a permis d’améliorer grandement les estimations des prises et des rejets, et la fiabilité générale des données. Les deux périodes sont appelées « historique » (1956-1995) et « moderne » (1996-2017) (annexe \@ref(app:commercial-cpue-standardization)).

Des détails sur le calcul de la moyenne du poids moyen annuel dans la pêche commerciale sont fournis à l’annexe \@ref(app:analysis-of-biological-data). L’inclusion de données sur la moyenne du poids moyen annuel vise à fournir des renseignements sur le recrutement en l’absence de données sur la composition selon l’âge. Cette moyenne dépend de l’hypothèse sous-jacente du modèle de type différence-délai (annexe \@ref(app:delay-difference-model)) selon laquelle la sélectivité, la croissance et la mortalité naturelle sont constantes et en lame de couteau tout au long de la période couverte par le modèle (1956-2017). Il est important de noter qu’une moyenne plus basse du poids moyen annuel dans les données commerciales pourrait indiquer un événement de recrutement, mais pourrait aussi avoir d’autres causes, notamment des proportions plus petites de poissons plus âgés ou plus gros dues à la mortalité par pêche ou à la mortalité naturelle, des changements dans la répartition spatiale de la pêche ou des changements dans la croissance.

## DISTRIBUTIONS DE PROBABILITÉ A PRIORI ET PARAMÈTRES DE VARIANCE FIXES

Les distributions de probabilité a priori pour les paramètres avancés dans les modèles de scénario de référence pour les zones 5ABCD et 3CD sont fournies dans les tableaux \@ref(tab:tab-priors-5abcd) et \@ref(tab:tab-priors-3cd). Les figures \@ref(fig:fig-base-mcmc-priors-5abcd) et \@ref(fig:fig-base-mcmc-priors-3cd) présentent graphiquement les distributions de probabilité a priori. La sensibilité du modèle aux hypothèses a priori est mise à l’essai dans la section \@ref(sec:sensitivity-analyses).

## PARAMÈTRES AVANCÉS

Une distribution de probabilité a priori large et uniforme a été utilisée pour $\ln(R_0)$, reflétant le fait que l’on ne connaît pas l’échelle de la population.

Une distribution bêta a été appliquée pour la pente éloignée a priori avec des paramètres de forme qui ont donné une distribution avec une moyenne = 0,7 et un ET = 0,15. Ces choix de paramètres ont produit une distribution avec une densité de probabilité faible à nulle pour des valeurs inférieures à 0,2 (figure \@ref(fig:fig-base-mcmc-priors-5abcd)), ce qui signifie qu’aucune transformation n’était nécessaire. Il s’agit de la même distribution de probabilité a priori que celle dont l‘utilisation a été acceptée dans l’évaluation précédente des stocks [@forrest2013]. @sinclair2005 a fixé la pente à 0,75 dans l’un de ses scénarios « privilégiés ». Dans son autre scénario « privilégié », l’estimation de la DPM de la pente était de 0,53. La distribution de probabilité a priori choisie ici englobe ces deux valeurs.

Une distribution normale a été utilisée pour $\ln(M)$ avec une moyenne = $\ln(0,5)$ et un ET = 0,1, comme dans @forrest2013. @sinclair2005 a obtenu des estimations de la DPM de *M* de 0,596 et 0,567 dans ses deux scénarios « privilégiés », et @forrest2013 des estimations de la DPM de 0,393 *a*^-1^ et 0,426 *a*^-1^ pour les zones 5CD et 5AB, respectivement. D’après une analyse de transition effectuée par @forrest2013, *M* pourrait être considérablement plus faible, selon les valeurs d’autres paramètres fixes ou estimés, et les estimations de *M* pour la morue du Pacifique ont considérablement varié tout au long de l’historique d’évaluation de l’espèce [@fournier1983; @haist1998; @sinclair2001].

## PARAMÈTRES D’ÉCHELLE DES RELEVÉS (CAPTURABILITÉ)

Des distributions de probabilité a priori uniformes ont été utilisées pour le paramètre de mise à l'échelle $q_{k}$ pour les indices *k* :

1. Relevé de la communauté d’espèces ou multispécifique dans le détroit d’Hécate;
1. Relevé triennal du NMFS;
1. Indices des CPUE commerciales.

Ces valeurs a priori reflétaient le fait que l’on ignorait l’échelle de l’indice du relevé par rapport à la population. Le relevé de la communauté d’espèces ou multispécifique dans le détroit d’Hécate n’a jamais été conçu comme un relevé aléatoire stratifié au chalut. Au lieu de cela, il s’agissait d’un relevé effectué selon un quadrillage avec une station fixe par grille. @sinclair1999 a assigné chaque station à une strate de profondeur et a analysé les données comme si le relevé utilisait un plan aléatoire stratifié. En raison de cette approche de stratification après coup, on ne connaît pas la relation entre l’indice du relevé et la population de morue du Pacifique. Le relevé triennal du National Marine Fisheries Service (NMFS) a été réalisé sept fois dans les eaux canadiennes entre 1980 et 2001. Le relevé suivait un plan par transects aléatoires, utilisant un départ aléatoire, puis remontant la côte ouest des États-Unis et du Canada à des intervalles de 50 milles marins. Chaque transect était stratifié par profondeur et les stations le long du transect étaient sélectionnées au hasard. L’étendue du relevé triennal au Canada variait selon les relevés, mais les données ont été analysées comme si le relevé couvrait la même superficie chaque année (voir l’annexe \@ref(app:fishery-independent-indices-of-abundance)). Ce relevé a été inclus dans la présente évaluation des stocks de la zone 3CD afin de fournir des renseignements indépendants des pêches sur la biomasse dans les années 1980 et 1990. Toutefois, comme pour le relevé de la communauté d’espèces ou multispécifique dans le détroit d’Hécate, on ne connaît pas la relation entre l’indice du relevé et la population de morue du Pacifique dans la zone 3CD. Les indices des CPUE commerciales sont des taux de prises normalisés (annexe \@ref(app:commercial-cpue-standardization)) avec une relation inconnue avec l’abondance de la population.

Des distributions normales ont été utilisées pour $\ln(q_{k})$ pour les indices *k* = :

1. Relevé synoptique dans le bassin de la Reine-Charlotte;
2. Relevé synoptique dans le détroit d’Hécate;
3. Relevé synoptique sur la côte ouest de l’île de Vancouver.

Le choix de la distribution de probabilité a priori pour les paramètres de mise à l’échelle du relevé peut avoir des effets importants sur les résultats de l’évaluation des stocks. Nous présentons donc un certain nombre d’autres formulations des valeurs a priori sous la forme d’analyses de sensibilité pour les distributions de probabilité a priori informatives suivantes à la section \@ref(sec:sensitivity-analyses).

### Paramètres de mise à l’échelle du relevé pour la zone 5ABCD {#sec:survey-scaling-parameters-for-area-5abcd}   

Nous avons utilisé des distributions de probabilité a priori informatives pour les deux relevés synoptiques en nous fondant sur les estimations a posteriori médianes de *q* tirées de la plus récente évaluation des stocks de fausse limande [@holt2016]. Cela a permis de limiter la tendance dans les modèles à estimer des tailles de stock invraisemblablement élevées. La fausse limande est une espèce de poisson plat qui occupe une tranche d’eau semblable (quoique dans des eaux légèrement moins profondes) à celle de la morue du Pacifique. @holt2016 ont obtenu des estimations a posteriori médianes de *q* = 0,6280 pour la zone 5AB et de *q* = 0,1869 pour la zone 5CD. Ils n’ont pas utilisé de distribution de probabilité a priori informative pour *q*. Le CV de leurs estimations était d’environ 0,3. Pour notre évaluation combinée de la zone 5ABCD, nous avons calculé ces valeurs au prorata en fonction des zones relatives d’habitat dans les zones 5AB et 5CD. En additionnant les superficies de toutes les strates de profondeur visées par le relevé dans chaque région, nous avons obtenu un ratio d’environ 0,65:0,35 (5AB:5CD). Nous avons donc utilisé les valeurs suivantes comme moyennes pour les distributions de probabilité a priori normales pour $\ln(q_{k})$, pour

1. *k* = Relevé synoptique dans le bassin de la Reine-Charlotte : Moyenne de $\ln(q_{k})$ = $\ln(0,6280\cdot 0,65)$
   = -0,895998;
2. *k* = Relevé synoptique dans le détroit d’Hécate : Moyenne de $\ln(q_{k})$ = $\ln(0,1869 \cdot
   0,35)$ = -2,727539;

Pour les deux sondages synoptiques, l’écart-type de la distribution normale de la probabilité antérieure pour $ ln(q_{k})$ a été fixé à 0,3 dans l’espace logarithmique.

### Paramètres de mise à l’échelle du relevé pour la zone 3CD {#sec:survey-scaling-parameters-for-area-3cd}

Comme pour la zone 5ABCD, nous avons utilisé une distribution de probabilité a priori informative pour le relevé synoptique sur la côte ouest de l’île de Vancouver en nous fondant sur une estimation a posteriori médiane tirée d’une évaluation récente. Encore une fois, l’objectif était de limiter les très grandes estimations de la taille des stocks produites par le modèle lorsqu’une valeur a priori uniforme était appliquée. Il y a eu moins d’évaluations récentes des stocks qui portaient uniquement sur la zone 3CD et aucune pour des espèces occupant la même tranche d’eau que la morue du Pacifique. Ici, nous avons utilisé une distribution de probabilité a priori normale pour $\ln(q_{k})$, avec la moyenne établie à l’estimation a posteriori médiane de *q* tirée de l’évaluation la plus récente pour le sébaste à longue mâchoire (*Sebastes alutus*) dans la zone 3CD [@edwards2013-2], c.-à-d. une moyenne de $\ln(q_{k})$ = $\ln(0,228)$ = -1,47841; l’écart-type de la distribution de probabilité a priori normale pour $ln(q_{k})$ a été fixé à 0,3 dans l’espace logarithmique, comme pour la zone 5ABCD. Le sébaste à longue mâchoire occupe une tranche d’eau plus profonde que la morue du Pacifique, mais il s’agit d’une espèce ciblée majeure pour la pêche au chalut qui peut donc renseigner sur la capturabilité dans cette zone. @edwards2013-2 n’a pas utilisé de distribution de probabilité a priori informative pour *q*.

## PARAMÈTRES DE VARIANCE FIXES {#sec:fixed-variance-parameters}

L’approche des erreurs dans les variables utilisée pour séparer les erreurs de traitement des erreurs d’observation est décrite de manière détaillée à l’annexe \@ref(app:delay-difference-model). En résumé, le paramètre de variance clé est l’inverse de la variance totale, c.-à-d. de la précision totale $\phi^{-2}$ [@martell2011]. Ce paramètre peut être fixe ou estimé. Il est fixe ici. La variance totale est répartie entre les composantes d’erreur due à l’observation et d’erreur due au traitement par le paramètre de modèle $\rho$, qui représente la proportion de la variance totale attribuable à une erreur d’observation [@punt1993; @deriso2007]. Ces paramètres servent à dériver la composante d’erreur d’observation de la variance totale ($\sigma_O$, éq. \@ref(eq:ddsigo)) et du terme de l’erreur de traitement ($\sigma_R$, éq. \@ref(eq:ddsigr)), qui saisit la fonction objective dans la fonction de log-vraisemblance pour les résidus du recrutement (éq. \@ref(eq:ddrlt)).

@forrest2013 ont constaté qu’il n’était pas possible d’obtenir des estimations vraisemblables du terme de variance $\phi^{-2}$ pour leur modèle de scénario de référence. Toutes les tentatives d’estimation de $\phi^{-2}$ ont donné des estimations de $\sigma_R$ proches de 2,0 et des estimations de $\sigma_O$ proches de 1,5, et des ajustements extrêmement médiocres avec les indices de l’abondance, en particulier les données sur les CPUE commerciales. Il a donc fallu fixer $\phi^{-2}$ et $\rho$ pour avoir des valeurs fixes de $\sigma_O$ et de $\sigma_R$. @sinclair2005 ont également utilisé des paramètres de variance fixes dans leur évaluation de la morue du Pacifique dans la zone 5CD. @forrest2013 ont employé des valeurs de $\phi^{-2}$ et de $\rho$ qui ont produit $\sigma_O$ = 0,25 et $\sigma_R$ = 0,8. Les passes préliminaires du modèle avec l’ensemble de données actuel ont montré que $\sigma_O$ = 0,25 donnait de mauvais ajustements aux indices de l’abondance d’après les relevés synoptiques, particulièrement dans la zone 5ABCD. Par conséquent, dans la présente évaluation, nous avons réduit $\sigma_O$ à 0,2 dans les deux modèles de scénario de référence. Les tests de sensibilité sont décrits à la section \@ref(sec:sensitivity-analyses).

En plus du terme de l’erreur d’observation globale $\sigma_O$, les points d’indice annuels pour chaque série d’indices de l’abondance ont été pondérés par les CV annuels à l’aide d’une approche de pondération multiplicative entièrement décrite à l’annexe \@ref(app:delay-difference-model).

Comme pour l’évaluation précédente des stocks de morue du Pacifique [@forrest2013], nous avons utilisé les composantes de variance fixes pour les composantes de vraisemblance pour les prises annuelles ($\sigma_C$) et la moyenne du poids moyen annuel ($\sigma_W$). Les problèmes d’interprétation des données sur le poids moyen ont été abordés dans @forrest2013, leur annexe C. Ils découlent de l’évolution au fil du temps de la taille des échantillons de différentes catégories de données sur la longueur, c.-à-d. les catégories triées et non triées et le manque de données sur les poissons plus petits avant que les observateurs ne mesurent les poissons en mer. L’examen de l’évaluation de 2005 [@fargo2005] a également mentionné des préoccupations entourant l’utilisation des données sur le poids moyen. @sinclair2005 ont reconnu ce problème, en remarquant que la série sur les poids moyens était nécessaire pour l’estimation des paramètres du modèle, mais qu’elle était sous-pondérée dans la fonction objective. Comme dans @forrest2013, $\sigma_W$ a été fixé à 0,2 dans les modèles de scénario de référence. Étant donné que le modèle suppose que les prises observées sont connues sans erreur, $\sigma_C$ a été défini à une petite valeur, c.-à-d. $\sigma_C$ = 0,05. Les tests de sensibilité à ces hypothèses sont cependant fournis dans la section \@ref(sec:sensitivity-analyses).

# RÉSULTATS

## ZONE 5ABCD : BASSIN DE LA REINE-CHARLOTTE ET DÉTROIT D’HÉCATE

Le modèle semblait avoir convergé (figure \@ref(fig:fig-base-mcmc-trace-5abcd)) et l’autocorrélation a posteriori était mineure pour la plupart des paramètres (figure \@ref(fig:fig-base-mcmc-autocor-5abcd)). La valeur de $\hat{R}$ était de 1,00 pour tous les paramètres (tableau \@ref(tab:tab-param-est-table-5abcd)).

Le modèle de densité a posteriori maximale (DPM) est ajusté aux cinq indices de l’abondance présentés sur la figure \@ref(fig:fig-base-index-fits-5abcd). Le modèle a suivi les tendances générales des trois indices indépendants de la pêche, mais n’a pas pu être ajusté à certains des pics les plus importants (par exemple, les pics de 2004 et 2005 dans le relevé synoptique dans le bassin de la Reine-Charlotte et le pic de 2013 dans le relevé synoptique dans le détroit d’Hécate, figure \@ref(fig:fig-base-index-fits-5abcd)). De même, il a suivi les principales tendances des deux indices des CPUE, mais n’a pas reflété tous les pics (figure \@ref(fig:fig-base-index-fits-5abcd)).

@forrest2013 considéraient la qualité de l’ajustement aux indices de l’abondance comme un facteur principal d’incertitude dans leur évaluation, puisque les estimations des paramètres de productivité étaient sensibles à la mesure dans laquelle le modèle était ajusté aux pics observés dans les indices. Ils ont présenté un certain nombre d’analyses de sensibilité pour le traitement du paramètre d’erreur d’observation $\sigma_O$, dont certaines sont explorées dans la présente évaluation (section \@ref(sec:sensitivity-analyses)).

L’ajustement du modèle à la moyenne du poids annuel moyen dans la pêche commerciale (figure \@ref(fig:fig-base-mean-weight-5abcd)) était légèrement meilleur que dans l’évaluation de 2013 [@forrest2013, leur Figure 37], qui avait tendance à sous-estimer le poids moyen annuel. Toutefois, le modèle actuel avait aussi tendance à sous-estimer le poids moyen annuel, surtout entre 1970 et 2000. L’ajustement légèrement amélioré par rapport à l’évaluation précédente est probablement en partie attribuable à la mise à jour des paramètres de croissance utilisés dans le modèle actuel (voir la section \@ref(sec:sensitivity-analyses)). Les effets des autres valeurs de $\sigma_W$ sont évalués dans la section \@ref(sec:sensitivity-analyses).

L’ajustement du modèle aux prises commerciales totales est illustré sur la figure \@ref(fig:fig-base-catch-fit-5abcd). Les ajustements du modèle sont presque parfaits en raison de la valeur de $\sigma_C$ = 0,05 fixée dans la fonction d’objectif (annexe \@ref(app:delay-difference-model)). Cela a été fait de façon à ce que le modèle soit essentiellement conditionné par les données sur les prises, qui étaient présumées connues avec très peu d’erreurs, même si les taux de rejet d’avant 1996 sont incertains.

Les distributions de probabilité a posteriori des paramètres estimés sont présentées sur la figure \@ref(fig:fig-base-mcmc-priors-posts-5abcd) et dans le tableau \@ref(tab:tab-param-est-table-5abcd). Les estimations de la médiane et des 2,5^th^ et 97,5^th^ centiles des paramètres a posteriori et celles de la densité a posteriori maximale (DPM) sont indiquées dans le tableau \@ref(tab:tab-param-est-table-5abcd). À l’exception de la pente, les estimations a posteriori ne semblaient pas fortement influencées par les distributions de probabilité a priori. La distribution de probabilité a posteriori pour la pente était très semblable à la distribution de probabilité a priori (figure \@ref(fig:fig-base-mcmc-priors-posts-5abcd)), ce qui signifie que les données disponibles contiennent peu d’information sur ce paramètre. Cela est fréquent dans de nombreuses évaluations des stocks et a également été noté dans les évaluations précédentes des stocks pour les zones 5AB et 5CD [@forrest2013]. La sensibilité à la distribution a priori présumée pour la pente est mise à l'essai dans la section \@ref(sec:sensitivity-analyses).

Les estimations de probabilité a posteriori de $\ln(M)$ avaient tendance à être inférieures aux valeurs a priori (figure \@ref(fig:fig-base-mcmc-priors-posts-5abcd)), avec une estimation de la médiane a posteriori de 0,346 *a*^-1^, une valeur légèrement inférieure à l’estimation de la médiane a posteriori de 0,393 *a*^-1^ obtenue par @forrest2013 pour le stock de la zone 5CD. Comme il a été mentionné précédemment, @forrest2013 ont signalé que les estimations a posteriori de $M$ étaient fortement influencées par l’ajustement aux données sur l’indice de l’abondance. De ce fait, la valeur présumée de $\sigma_O$ a probablement une plus grande influence sur les estimations de $M$ que la distribution de probabilité a priori de $\ln(M)$. Cette question est abordée de manière plus détaillée dans la section \@ref(sec:sensitivity-analyses).

Les paramètres de mise à l’échelle du relevé ($q_{k}$) étaient fortement corrélés positivement l’un avec l’autre, en particulier pour les deux relevés synoptiques $q_2$ et $q_3$ sur la figure \@ref(fig:fig-base-mcmc-pairs-5abcd), qui affichaient une corrélation linéaire. Cela implique qu’une modification de la distribution de probabilité a priori pour l’un de ces paramètres aura un effet important sur l’autre et, par conséquent, sur l’échelle de la biomasse estimée dans le modèle. Étant donné que les deux relevés synoptiques sont le plus souvent effectués les mêmes années, le modèle semble avoir eu peu de latitude pour modifier le ratio de leurs échelles relatives (voir la section \@ref(sec:sensitivity-analyses)). Les paramètres de mise à l’échelle des relevés affichaient une corrélation négative avec $M$. $R_0$ était également corrélé négativement avec $M$, ce qui montre que les données contiennent des renseignements limités pour différencier une petite population productive d’une autre, plus nombreuse et moins productive (figure \@ref(fig:fig-base-mcmc-pairs-5abcd)). La distribution a posteriori estimée pour la valeur de $q$ dans le bassin de la Reine-Charlotte sortait largement de la distribution a priori, tandis que la distribution a posteriori du paramètre de mise à l’échelle pour le relevé synoptique dans le détroit d’Hécate était décalé, mais encore dans les limites de la distribution a priori (figure \@ref(fig:fig-base-mcmc-priors-posts-5abcd)). Ces résultats montrent que la distribution a priori pour le relevé synoptique dans le bassin de la Reine-Charlotte pourrait ne pas convenir pour cette combinaison espèce/relevé, surtout compte tenu de la forte corrélation linéaire entre les deux relevés synoptiques ($q_2$ et $q_3$ sur la figure \@ref(fig:fig-base-mcmc-pairs-5abcd)).

Les estimations des points de référence et des points de repère sont présentées dans le tableau \@ref(tab:tab-ref-points-table-5abcd).

La médiane de la biomasse estimée a posteriori $B_{t}$ (avec un intervalle de crédibilité de 95 %) est illustrée sur la figure \@ref(fig:fig-base-biomass-5abcd), et les valeurs sont indiquées dans le tableau \@ref(tab:tab-post-biomass-5abcd). Il convient de souligner la diminution de la biomasse estimée depuis 2011, qui contraste avec l’évaluation de 2013 [@forrest2013, leur figure 16], qui projetait une augmentation de la biomasse pour 2014. Dans la présente évaluation, cette baisse est attribuable à une tendance à la baisse dans les relevés synoptiques depuis 2013, ainsi qu’à l’indice des CPUE modernes (figure \@ref(fig:fig-base-index-fits-5abcd)) Il convient également de noter l’estimation plus faible, comparativement à l’évaluation précédente, de $B_0$, qu’on estime maintenant inférieure à la biomasse de la population de 1956, avec un intervalle de confiance plus petit (figure \@ref(fig:fig-base-biomass-5abcd)). Cette réduction est attribuable au changement structurel apporté dans la présente évaluation, où tous les paramètres de recrutement moyen sont maintenant établis à la même valeur estimée (voir la section \@ref(sec:stock-assessment-model)), et peut aussi être fonction de la diminution de la biomasse causée par la baisse des indices de la biomasse.

La médiane de la biomasse relative estimée a posteriori ($B_{t}/B_0$)) (avec un intervalle de crédibilité de 95 %) est présentée sur la figure \@ref(fig:fig-base-depl-5abcd) et dans le tableau \@ref(tab:tab-post-depl-5abcd). La figure \@ref(fig:fig-base-recr-5abcd) et le tableau \@ref(tab:tab-post-recr-5abcd) montrent la médiane des écarts estimés a posteriori entre les recrues d’âge-2 et le recrutement (avec un intervalle de crédibilité de 95 %). On estime que le recrutement est inférieur à la moyenne depuis 1990, avec des écarts de recrutement négatifs depuis 2010, ce qui est probablement la principale raison pour laquelle ce stock ne se porte pas bien, malgré les faibles mortalités par pêche estimées (figure \@ref(fig:fig-base-f-5abcd)).

La médiane de la mortalité par pêche estimée a posteriori ($F_{t}$) est illustrée sur la figure \@ref(fig:fig-base-f-5abcd). La mortalité par pêche en 2017 était faible comparativement à la période historique, avec une médiane a posteriori estimée à 0,03 *a*^-1^ (tableaux \@ref(tab:tab-ref-points-table-5abcd) et \@ref(tab:tab-post-f-5abcd)).

Nous avons effectué une analyse rétrospective, en retirant de manière séquentielle les données de l’année finale pendant quatre ans pour montrer les effets des données de chaque année (figure \@ref(fig:fig-base-retro-biomass-5abcd)). Les résultats indiquent clairement les effets des relevés synoptiques biennaux sur les estimations terminales de la biomasse. L’élimination de quatre années de données a ramené le modèle à son état de 2013, avec une augmentation de la biomasse telle qu’elle avait été projetée dans l’évaluation précédente pour le stock de la zone 5CD [@forrest2013]. L’ajout des données de 2014 a eu peu d’effet sur le modèle, car il n’y a pas eu de relevés dans les zones 5AB ou 5CD en 2014. Toutefois, l’ajout des données de 2015 a entraîné une diminution de la biomasse terminale estimée en raison d’une chute importante de l’indice du relevé synoptique dans le détroit d’Hécate de 2015 (figure \@ref(fig:fig-base-index-fits-5abcd)).

## ZONE 3CD : CÔTE OUEST DE L’ÎLE DE VANCOUVER

Le modèle semblait avoir convergé (figure \@ref(fig:fig-base-mcmc-trace-3cd)) et l’autocorrélation a posteriori était mineure pour la plupart des paramètres (figure \@ref(fig:fig-base-mcmc-autocor-3cd)). La valeur de $\hat{R}$ était de 1,00 pour tous les paramètres (tableau \@ref(tab:tab-param-est-table-3cd)).

Le modèle de densité a posteriori maximale (DPM) est ajusté aux quatre indices de l’abondance présentés sur la figure \@ref(fig:fig-base-index-fits-3cd). Le modèle était assez étroitement ajusté aux deux indices indépendants de la pêche (figure \@ref(fig:fig-base-index-fits-3cd) a et d), mais pas aux points de données de 2012 du relevé synoptique sur la côte ouest de l’île de Vancouver. De même, il a suivi les principales tendances des deux indices des CPUE, mais n’a pas reflété tous les pics (figure \@ref(fig:fig-base-index-fits-3cd) b et c).

Comme dans le cas de la zone 5ABCD, le modèle avait tendance à être sous-ajusté à la moyenne du poids annuel moyen dans la pêche commerciale (figure \@ref(fig:fig-base-mean-weight-3cd)). Les effets des autres valeurs de $\sigma_W$ sont évalués dans la section \@ref(sec:sensitivity-analyses).

L’ajustement du modèle aux prises commerciales totales est illustré sur la figure \@ref(fig:fig-base-catch-fit-3cd).

Les distributions de probabilité a posteriori des paramètres estimés sont présentées sur la figure \@ref(fig:fig-base-mcmc-priors-posts-3cd) et dans le tableau \@ref(tab:tab-param-est-table-3cd). Les estimations de la médiane et des 2,5^th^  et 97,5^th^ centiles des paramètres a posteriori et celles de la densité a posteriori maximale (DPM) sont indiquées dans le tableau \@ref(tab:tab-param-est-table-3cd). Comme dans le cas de la zone 5ABCD, à l’exception de la pente, les estimations a posteriori ne semblaient pas fortement influencées par les distributions de probabilité a priori. La distribution de probabilité a posteriori pour la pente était cependant très semblable à la distribution de probabilité a priori (figure \@ref(fig:fig-base-mcmc-priors-posts-3cd)), ce qui signifie que les données disponibles contiennent peu d’information sur ce paramètre. La sensibilité à la distribution a priori présumée pour la pente est mise à l'essai dans la section \@ref(sec:sensitivity-analyses).

Comme pour la zone 5ABCD, les estimations de probabilité a posteriori de $\ln(M)$ avaient tendance à être inférieures aux valeurs a priori (figure \@ref(fig:fig-base-mcmc-priors-posts-3cd)), avec une estimation de la médiane a posteriori de 0,413 *a*^-1^, supérieure à l’estimation de la médiane a posteriori de 0,346 *a*^-1^ obtenue pour le stock de la zone 5ABCD (tableau \@ref(tab:tab-param-est-table-3cd)) et très semblable à la valeur de 0,42 *a*^-1^ obtenue par @sinclair2001 pour le stock de la zone 3CD.

Les paramètres de mise à l’échelle du relevé ($q_{k}$) étaient fortement corrélés positivement l’un avec l’autre (figure \@ref(fig:fig-base-mcmc-pairs-3cd)). Comme pour la zone 5ABCD, les paramètres de mise à l’échelle des relevés affichaient une corrélation négative avec $M$, ce qui montre que les données contiennent des renseignements limités pour différencier une petite population productive d’une autre, plus nombreuse et moins productive (figure \@ref(fig:fig-base-mcmc-pairs-3cd)). Il est intéressant de noter la corrélation positive entre $R_0$ et $M$. Comme pour le relevé synoptique dans le bassin de la Reine-Charlotte, la distribution a posteriori estimée pour le paramètre de mise à l’échelle du relevé synoptique sur la COIV sortait de la distribution a priori (figure \@ref(fig:fig-base-mcmc-priors-posts-3cd)).

Les estimations des points de référence et des points de repère sont présentées dans le tableau \@ref(tab:tab-ref-points-table-3cd).

La médiane de la biomasse estimée a posteriori $B_{t}$ (avec un intervalle de crédibilité de 95 %) est illustrée sur la figure \@ref(fig:fig-base-biomass-3cd), et les valeurs sont indiquées dans le tableau \@ref(tab:tab-post-biomass-3cd). On estime que la biomasse suit une trajectoire à la baisse depuis 2015, qui fait suite à la tendance à la hausse par rapport à un faible niveau historique entre 1998 et 2014. On estime que l’abondance du stock a augmenté depuis 2008, ce qui correspond à une tendance à la hausse de l’abondance observée dans le relevé synoptique sur la côte ouest de l’île de Vancouver depuis 2010, ainsi qu’à une augmentation générale de l’indice des CPUE modernes depuis 2008 (figure \@ref(fig:fig-base-index-fits-3cd)). Le repli de la biomasse estimée en 2017 correspond à une légère baisse de l’indice du relevé synoptique sur la côte ouest de l’île de Vancouver et à une forte diminution de l’indice des CPUE modernes en 2017.

La médiane de la biomasse relative estimée a posteriori ($B_{t}/B_0$)) (avec un intervalle de crédibilité de 95 %) est présentée sur la figure \@ref(fig:fig-base-depl-3cd) et dans le tableau \@ref(tab:tab-post-depl-3cd). La figure \@ref(fig:fig-base-recr-3cd) et le tableau \@ref(tab:tab-post-recr-3cd) montrent la médiane des écarts estimés a posteriori entre les recrues d’âge-2 et le recrutement (avec un intervalle de crédibilité de 95 %). On estime que le recrutement a été inférieur à la moyenne la plupart des années depuis deux décennies, avec des pics au-dessus de la moyenne en 2009, 2013 et 2014.

La médiane de la mortalité par pêche estimée a posteriori ($F_{t}$) est illustrée sur la figure \@ref(fig:fig-base-f-3cd). On estime que la mortalité par pêche en 2017 est très faible, avec la médiane a posteriori estimée à 0,01 *a*^-1^ (tableaux \@ref(tab:tab-ref-points-table-3cd) et \@ref(tab:tab-post-f-3cd)), ce qui reflète les faibles prises au cours de la dernière décennie. (figure \@ref(fig:fig-base-catch-fit-5abcd)) et une croissance apparente de la biomasse (figure \@ref(fig:fig-base-biomass-3cd)).

Nous avons effectué une analyse rétrospective, en retirant de manière séquentielle les données de l’année finale pendant quatre ans pour montrer les effets des données de chaque année (figure \@ref(fig:fig-base-retro-biomass-3cd)). Les résultats n’étaient pas aussi systématiques que pour la zone 5ABCD (figure \@ref(fig:fig-base-retro-biomass-3cd)) et l’ampleur relative du biais était plus petite. L’effet le plus important a été l’ajout des données de 2017, qui a entraîné un décalage sensible de l’estimation de la biomasse terminale, fort probablement en raison de la baisse importante de l’indice des CPUE modernes en 2017 (figure \@ref(fig:fig-base-index-fits-3cd)).

# ANALYSES DE SENSIBILITÉ {#sec:sensitivity-analyses}

Nous présentons un certain nombre d’analyses de sensibilité pour montrer l’influence de certaines sources de données, des paramètres fixes et des distributions de probabilité a priori sur les résultats du modèle pour les modèles du scénario de référence dans les zones 5ABCD et 3CD. Les distributions de probabilité a priori pour les paramètres avancés sont indiquées dans les tableaux \@ref(tab:tab-priors-5abcd) et \@ref(tab:tab-priors-3cd). Les paramètres fixes sont fournis à la section \@ref(sec:reference-case-models).

Pour les deux stocks, nous avons testé la sensibilité des sorties du modèle aux données et hypothèses suivantes :

1. L’inclusion d’une interaction lieu-année comme effet aléatoire dans les données des CPUE commerciales (période historique : avant 1996 et période moderne : après 1995)
1. L’inclusion des indices des CPUE commerciales pour les périodes historique et moderne
1. L’inclusion de l’indice du relevé triennal du NMFS pour la zone 3CD
1. La distribution de probabilité a priori pour $\ln(q)$
1. La distribution de probabilité a priori pour $\ln(M)$
1. La distribution de probabilité a priori pour la pente
1. L’hypothèse d’une sélectivité en lame de couteau et de la maturité à l’âge de 2 ans
1. Les paramètres de croissance mis à jour
1. La valeur fixe présumée de l’erreur d’observation $\sigma_O$
1. La valeur fixe présumée de $\sigma_R$
1. La valeur fixe présumée de $\sigma_W$
1. L’influence des données annuelles sur le poids moyen annuel avant 1996
1. L’hypothèse selon laquelle les données sur les prises avant 1996 sont parfaitement connues

Les résultats sont présentés dans les rubriques ci-après. Pour toutes les analyses de sensibilité, comme pour les modèles du scénario de référence, des échantillons a posteriori ont été tirés à chaque 5 000e itération d’une chaîne longue de 10 millions, ce qui a donné 2 000 échantillons a posteriori. Les 1 000 premiers échantillons ont été omis pour permettre un rodage suffisant.

## SC 1B ET SC 1C. EXCLUSION D’UNE INTERACTION LIEU-ANNÉE COMME EFFET ALÉATOIRE DANS LES INDICES DES CPUE COMMERCIALES

Les modèles de scénario de référence ont été ajustés aux indices historiques et modernes des CPUE commerciales qui englobaient une interaction lieu-année comme effet aléatoire (voir l’annexe \@ref(app:commercial-cpue-standardization), les équations \@ref(eq:cpue-tweedie) à \@ref(eq:cpue-vessel)). Deux analyses de sensibilité illustrent l’effet de l’omission du terme de l’interaction lieu-année (équation \@ref(eq:cpue-locality-year)) dans les indices historiques et modernes :

> **Sc 1b.** Utiliser les équations sans le terme de l’interaction pour créer les indices des CPUE
> pour les périodes historique et moderne. Utiliser les CV annuels résultant de
> l’analyse comme termes de pondération annuelle dans la fonction objective du modèle de type différence-délai
> (équations \@ref(eq:ddsigjt), \@ref(eq:ddcjt)).

> **Sc 1c.** Utiliser les équations sans le terme de l’interaction pour créer les indices des CPUE
> pour les périodes historique et moderne **et** doubler les CV annuels résultant
> de l’analyse. Entrer les CV doublés comme termes de pondération dans la fonction objective
> du modèle de type différence-délai (équations \@ref(eq:ddsigjt),
> \@ref(eq:ddcjt)).

Le scénario 1c a été effectué parce que les CV annuels des indices des CPUE dans lesquels les interactions lieu-année étaient omises étaient très faibles (moins de 0,1 certaines années). Les CV annuels ont été doublés pour répondre aux préoccupations selon lesquelles la fonction objective du modèle de type différence-délai aurait peut-être accordé trop de poids aux indices des CPUE.

Les estimations a posteriori ainsi obtenues de la biomasse, du recrutement et de la mortalité par pêche par rapport aux modèles du scénario de référence sont représentées sur les figures \@ref(fig:fig-sens1-biomass-5abcd) à \@ref(fig:fig-sens1-f-5abcd) pour la zone 5ABCD, et sur les figures \@ref(fig:fig-sens8-biomass-3cd) à \@ref(fig:fig-sens8-f-3cd) pour la zone 3CD. L’élimination de l’interaction de l’effet aléatoire lieu-année n’a pas eu d’incidence majeure sur les valeurs a posteriori de la biomasse, du recrutement ou de la mortalité par pêche. Parmi ces analyses de sensibilité, c’est l’élimination de l’interaction de l’effet aléatoire lieu-année sans doubler artificiellement le CV qui a eu l’effet le plus important - cette analyse de sensibilité a légèrement abaissé l’estimation absolue de la biomasse et a quelque peu rétréci les intervalles de crédibilité.

## SC 1D à 1F. EXCLUSION DES INDICES DES CPUE COMMERCIALES

Une analyse de sensibilité a été effectuée en retirant l’indice des CPUE modernes entièrement du modèle (Sc 1d). Elle visait à répondre aux préoccupations selon lesquelles les CPUE de la période après la mise en place des QIB (après 1995) pourraient ne pas être un bon indice de l’abondance, puisque certains capitaines ont déclaré éviter la morue du Pacifique lorsque les quotas étaient bas, surtout dans la zone 5AB [@forrest2013]. À des fins de comparaison, on a retiré l’indice des CPUE historiques pour illustrer son effet sur la sortie du modèle (Sc 1e). Enfin, pour montrer l’influence globale des données des CPUE commerciales sur les résultats du modèle, on a retiré les deux indices des CPUE commerciales (Sc 1f) :

> **Sc 1d.** Retirer du modèle l’indice des CPUE modernes. L’indice historique inclut le terme d’interaction lieu-année comme effet aléatoire.

> **Sc 1e.** Retirer du modèle l’indice des CPUE historiques. L’indice moderne inclut le terme d’interaction lieu-année comme effet aléatoire.

> **Sc 1f.** Retirer du modèle les deux indices des CPUE.

Les estimations a posteriori ainsi obtenues de la biomasse, du recrutement et de la mortalité par pêche par rapport aux modèles du scénario de référence sont représentées sur les figures \@ref(fig:fig-sens1-biomass-5abcd) à \@ref(fig:fig-sens1-f-5abcd) pour la zone 5ABCD, et sur les figures \@ref(fig:fig-sens8-biomass-3cd) à \@ref(fig:fig-sens8-f-3cd) pour la zone 3CD. Pour plus de clarté, les trajectoires de la biomasse sans les Sc 1e et 1f sont indiquées sur les figures \@ref(fig:fig-sens1-sub2-biomass-5abcd) et \@ref(fig:fig-sens8-sub2-biomass-3cd).

Le retrait du modèle de l’indice des CPUE modernes a eu peu d’effet sur les valeurs a posteriori de la biomasse, du recrutement ou de la mortalité par pêche (figures \@ref(fig:fig-sens1-sub2-biomass-5abcd) et \@ref(fig:fig-sens8-sub2-biomass-3cd)). Toutefois, l’élimination de l’indice des CPUE historiques a eu un effet important sur les estimations a posteriori - en particulier les estimations de la biomasse -, en rehaussant considérablement les estimations de la biomasse avant 1970 environ (figures \@ref(fig:fig-sens1-biomass-5abcd) et \@ref(fig:fig-sens8-biomass-3cd)). @forrest2013 ont noté une forte influence semblable des CPUE historiques, et ont inclus une passe du modèle sans CPUE dans leurs tableaux de décision fondés sur la moyenne des modèles.

## SC 1G. EXCLUSION DE L’INDICE DU RELEVÉ TRIENNAL DU NMFS POUR LA ZONE 3CD

Une analyse de sensibilité a été effectuée, pour la zone 3CD uniquement, en retirant du modèle l’indice du relevé triennal du NMFS :

> **Sc 1g (zone 3CD uniquement). ** Retirer du modèle l’indice du relevé triennal du NMFS.

Les estimations a posteriori ainsi obtenues de la biomasse, du recrutement et de la mortalité par pêche par rapport aux modèles du scénario de référence sont incluses sur les figures \@ref(fig:fig-sens8-sub2-biomass-3cd) à \@ref(fig:fig-sens8-f-3cd). Il y a eu très peu d’incidence sur la trajectoire de la biomasse par rapport au scénario de référence dans cette analyse de sensibilité.

## SC 2A ET 2B. DISTRIBUTION DE LA PROBABILITÉ A PRIORI POUR LES PARAMÈTRES D’ÉCHELLE DES RELEVÉS (CAPTURABILITÉ)

Six analyses de sensibilité sont présentées pour la zone 5ABCD afin d’illustrer l’effet des distributions de probabilité a priori normales supposées pour $ln(q)$ pour les relevés synoptiques dans le bassin de la Reine-Charlotte et du détroit d’Hécate (voir les détails du scénario dans les sections \@ref(sec:survey-scaling-parameters-for-area-5abcd) et \@ref(sec:survey-scaling-parameters-for-area-3cd)) :

> **Sc 2a. ** La moyenne de la valeur a priori pour le relevé synoptique dans le bassin de la Reine-Charlotte a été fixée à la même moyenne que celle du relevé synoptique dans le détroit d’Hécate, puis a été calculée au prorata des superficies relatives, c.‑à‑d. moyenne de $\ln(q)$ = $\ln(0,1869\ 0,65)$.

> **Sc 2b.** Aucune valeur a priori n’a été utilisée pour \textit{q} pour les relevés synoptiques dans le bassin de la Reine-Charlotte et du détroit d’Hécate.

Quatre analyses supplémentaires ont été effectuées pour encadrer l’incertitude considérable de l’échelle du stock.

> **Sc 2c.** Les moyennes des valeurs a priori des relevés synoptiques dans le bassin de la Reine-Charlotte et le détroit d’Hécate ont été établies à ln(0,5), puis ont ensuite été calculées au prorata des superficies relatives, c.-à-d. : pour le bassin de la Reine-Charlotte : moyenne de $\ln(q)$ = $\ln(0,5 \cdot 0,65)$; et pour le détroit d’Hécate : moyenne de $\ln(q)$ = $\ln(0,5 \cdot 0,35)$.

> **Sc 2d.** Les moyennes des valeurs a priori des relevés synoptiques dans le bassin de la Reine-Charlotte et le détroit d’Hécate ont été établies à ln(1), puis calculées au prorata des superficies relatives, c.‑à‑d. : pour le bassin de la Reine-Charlotte : moyenne de $\ln(q)$ = $\ln(0,65)$; et pour le détroit d’Hécate : moyenne de $\ln(q)$ = $\ln(0,35)$.

> **Sc 2e.** Les ET des valeurs a priori des relevés synoptiques dans le bassin de la Reine-Charlotte et le détroit d’Hécate ont été fixées à 0,6.

> **Sc 2f.** Les ET des valeurs a priori des relevés synoptiques dans le bassin de la Reine-Charlotte et le détroit d’Hécate ont été fixées à 1,0.

Pour la zone 3CD, six analyses de sensibilité illustrent l’effet de la distribution de probabilité a priori normale présumée pour $\ln(q)$ pour le relevé synoptique sur la COIV :

> **Sc 2a. ** L’écart-type du relevé synoptique sur la COIV a été fixé au même ET que la valeur estimée par @edwards2013-2 pour le sébaste à longue mâchoire : ET = 0,448.

> **Sc 2b.** Aucune valeur a priori n’a été utilisée pour \textit{q} pour le relevé synoptique sur la COIV.

Comme pour la zone 5ABCD, quatre analyses supplémentaires ont été effectuées pour encadrer l’incertitude considérable de l’échelle du stock.

> **Sc 2c.** La moyenne de la valeur a priori du relevé synoptique sur la COIV a été établie à ln(0,5).

> **Sc 2d.** La moyenne de la valeur a priori du relevé synoptique sur la COIV a été établie à ln(1).

> **Sc 2e.** L’ET de la valeur a priori du relevé synoptique sur la COIV a été établi à 0,6.

> **Sc 2f.** L’ET de la valeur a priori du relevé synoptique sur la COIV a été établi à 1,0.

Les modèles étaient modérément sensibles au choix des paramètres utilisés pour la valeur a priori normale de $\ln(q)$ (Sc 2a; figures \@ref(fig:fig-sens2-biomass-5abcd) et \@ref(fig:fig-sens9-biomass-3cd)). Dans un souci de clarté, les trajectoires estimées de la biomasse sans le Sc 2b sont fournies pour la zone 3Cd sur la figure \@ref(fig:fig-sens9-biomass-3cd-sub). En gros, la diminution de la valeur de la moyenne (zone 5ABCD) ou l’augmentation de la variance (zone 3CD) a donné des estimations plus basses de $q$ (tableaux \@ref(tab:tab-param-table-sens2a-5abcd) et \@ref(tab:tab-param-table-sens2a-3cd)), ce qui donne lieu à des estimations plus importantes de la biomasse (figures \@ref(fig:fig-sens2-biomass-5abcd) et \@ref(fig:fig-sens9-biomass-3cd-sub)) et du recrutement (figures \@ref(fig:fig-sens2-recr-5abcd) et \@ref(fig:fig-sens9-recr-3cd)).

En particulier, l’élimination de la valeur a priori informative dans le Sc 2b a produit des estimations très faibles de $q$ pour ces relevés (tableaux \@ref(tab:tab-param-table-sens2b-5abcd) et \@ref(tab:tab-param-table-sens2b-3cd)), ce qui a donné lieu à des estimations très élevées et incertaines de la biomasse (figures \@ref(fig:fig-sens2-biomass-5abcd) et \@ref(fig:fig-sens9-biomass-3cd)) et du recrutement (figures \@ref(fig:fig-sens2-recr-5abcd) et \@ref(fig:fig-sens9-recr-3cd)). Cette tendance était extrêmement prononcée pour la zone 3CD (tableau \@ref(tab:tab-param-table-sens2b-3cd) et sur la figure \@ref(fig:fig-sens9-biomass-3cd)). Pour les deux zones, l’augmentation des estimations de la biomasse a entraîné une diminution des estimations de $F_{t}$ (figures \@ref(fig:fig-sens2-f-5abcd) et \@ref(fig:fig-sens9-f-3cd)).

Compte tenu de la sensibilité du modèle aux valeurs a priori présumées pour $ln(q)$ du relevé, ainsi que de la tendance des estimations à produire des valeurs très faibles sans contrainte a priori, il semble justifié d’utiliser une distribution de probabilité a priori étayée par des évaluations structurées selon l’âge pour les espèces de poisson de fond capturées dans les mêmes zones avec le même engin, même si ces estimations dépendent des hypothèses inhérentes à ces modèles. Il faudrait considérer la valeur *q* du relevé synoptique comme une source majeure d’incertitude dans cette évaluation, et nous suggérons d’inclure le scénario 2a (les deux zones) dans l’ensemble des modèles pour les tableaux de décision fondés sur la moyenne des modèles (section \@ref(sec:projections-and-decision-tables)).

## SC 3A À 3C. DISTRIBUTION DE PROBABILITÉ A PRIORI POUR *M*

Trois analyses de sensibilité sont présentées pour illustrer l’effet des paramètres de la distribution a priori normale présumée pour $\ln(M)$ :

> **Sc 3a. ** La moyenne a été maintenue à la valeur de 0,5 du scénario de référence, tandis que l’écart-type a été relevé à 0,2.

> **Sc 3b.** La moyenne a été réduite à 0,4 et l’écart-type a été maintenu à la valeur de 0,1 du scénario de référence.

> **Sc 3c.** La moyenne a été réduite à 0,4 et l’écart-type a été augmenté à 0,2.

Les estimations a posteriori ainsi obtenues de la biomasse, du recrutement et de la mortalité par pêche par rapport aux modèles du scénario de référence sont représentées sur les figures \@ref(fig:fig-sens3-biomass-5abcd) à \@ref(fig:fig-sens3-f-5abcd) pour la zone 5ABCD, et sur les figures \@ref(fig:fig-sens10-biomass-3cd) à \@ref(fig:fig-sens10-f-3cd) pour la zone 3CD. Les estimations des paramètres ainsi obtenues sont indiquées dans les tableaux \@ref(tab:tab-param-table-sens3a-5abcd) à \@ref(tab:tab-param-table-sens3c-5abcd) pour la zone 5ABCD et dans les tableaux \@ref (tab:tab-param-table-sens3a-3cd) à \@ref (tab:tab-param-table-sens3cd) pour la zone 3CD.

Pour la zone 5ABCD, les estimations a posteriori médianes respectives de *M* pour les scénarios 3a, 3b et 3c étaient de 0,324 *a*^-1^, 0,287 *a*^-1^ et 0,298 *a*^-1^. Ces valeurs sont à comparer à l’estimation a posteriori médiane du scénario de référence de *M* = 0,346 *a*^-1^.

Pour la zone 3CD, les estimations a posteriori médianes respectives de *M* pour les scénarios 3a, 3b et 3c étaient de 0,392 *a*^-1^, 0,391 *a*^-1^ et 0,398 *a*^-1^. Ces valeurs sont à comparer à l’estimation a posteriori médiane du scénario de référence de *M* = 0,413 *a*^-1^.

Pour la zone 5ABCD, toutes les analyses de sensibilité ont donné des estimations de la biomasse inférieures à celles du modèle du scénario de référence (figure \@ref(fig:fig-sens3-biomass-5abcd)), ce qui n’était pas surprenant puisqu’elles avaient toutes des estimations de la médiane postérieure inférieures à *M*. Les différences dans l’estimation de la biomasse entre les scénarios étaient plus faibles pour la zone 3CD, même si toutes étaient légèrement inférieures à celles du modèle du scénario de référence (figure \@ref(fig:fig-sens10-biomass-3cd)).

Nous suggérons d’inclure le scénario 3b (les deux zones) dans l’ensemble de modèles pour les tableaux de décision fondés sur la moyenne des modèles (section \@ref(sec:projections-and-decision-tables))), car c’est ce scénario qui a généré la plus grande différence dans la biomasse estimée dans les deux zones.

## SC 4A ET SC 4B. DISTRIBUTION DE PROBABILITÉ A PRIORI POUR LA PENTE

Deux analyses de sensibilité ont été effectuées pour illustrer l’effet de la distribution de probabilité a priori supposée pour la pente dans le modèle du scénario de référence :

> **Sc 4a. ** Utiliser une valeur a priori uniforme pour la pente, fixée entre 0,21 et 0,999.

> **Sc 4b.** Utiliser une valeur a priori bêta pour la pente avec la moyenne = 0,85 et l’écart-type = 0,15.

Les estimations a posteriori ainsi obtenues de la biomasse, du recrutement et de la mortalité par pêche par rapport aux modèles du scénario de référence sont représentées sur les figures \@ref(fig:fig-sens4-biomass-5abcd) à \@ref(fig:fig-sens4-f-5abcd) pour la zone 5ABCD, et sur les figures \@ref(fig:fig-sens11-biomass-3cd) à \@ref(fig:fig-sens11-f-3cd) pour la zone 3CD. Les estimations des paramètres ainsi obtenues sont indiquées dans les tableaux \@ref(tab:tab-param-table-sens4a-5abcd) à \@ref(tab:tab-param-table-sens4b-5abcd) pour la zone 5ABCD et dans les tableaux \@ref (tab:tab-param-table-sens4a-3cd) à \@ref (tab:tab-param-table-sens3cd) pour la zone 3CD.

Pour la zone 5ABCD, les estimations a posteriori médianes respectives de *h* pour les scénarios 4a et 4b étaient de 0,479 et de 0,883. Pour la zone 3CD, les estimations a posteriori médianes respectives de *h* pour les scénarios 4a et 4b étaient de 0,497 et de 0,889. Ces valeurs ont été comparées à celles de 0,744 pour le scénario de référence de la zone 5ABCD et de 0,747 pour le scénario de référence de la zone 3CD.

Malgré la très grande fourchette des estimations a posteriori médianes de *h* parmi les scénarios pour les deux zones, il n’y avait presque aucun effet perceptible sur la biomasse et le recrutement estimés, particulièrement pour la zone 3CD (figures \@ref(fig:fig-sens4-biomass-5abcd) et \@ref(fig:fig-sens11-biomass-3cd)). L’insensibilité du modèle à la distribution de probabilité a priori pour *h* explique en partie pourquoi la distribution de probabilité a posteriori correspondait si étroitement à la valeur a priori pour les deux modèles (figures \@ref(fig:fig-base-mcmc-priors-posts-5abcd) et \@ref(fig:fig-base-mcmc-priors-posts-3cd)).

Les différences de sensibilité du modèle à la valeur a priori pour *h* dans la présente évaluation par rapport à l’évaluation précédente pour la zone 5CD peuvent s’expliquer par des changements dans le traitement du recrutement moyen. Le modèle utilisé dans @forrest2013 estimait $R_{0}$ comme un paramètre distinct du recrutement annuel moyen ($R_{Avg}$). Par conséquent, lorsque @forrest2013 ont testé une valeur a priori uniforme de *h*, alors que les estimations de la biomasse n’étaient pas touchées, leurs estimations a posteriori de $B_{0}$ sont devenues très élevées [@forrest2013, leurs figures 33 et 34]. Ils ont décrit une piètre convergence du modèle pour la plupart des paramètres et ont noté que la tendance du modèle à échantillonner des estimations très faibles de la pente coïncidait avec les estimations très élevées de $\ln(R_0)$. On peut en déduire que les données contenaient très peu d’information pour estimer un paramètre distinct $\ln(R_0)$ en l’absence de données sur la composition selon l’âge, ce qui suggère qu’il peut être préférable de combiner le recrutement moyen et le recrutement non exploité, comme cela a été fait dans la présente évaluation.

## SC 5A ET 5B. L’HYPOTHÈSE D’UNE SÉLECTIVITÉ EN LAME DE COUTEAU ET DE LA MATURITÉ À L’ÂGE DE 2 ANS ET LES EFFETS DE MISE À JOUR DES PARAMÈTRES DE CROISSANCE

Les modèles de type différence-délai du scénario de référence supposaient une sélectivité en lame de couteau et une maturité à l’âge de 2 *a* (c.-à-d. âge au recrutement $k$ = 2, tableau \@ref(tab:tab-param-list)). D’après une nouvelle analyse des données sur l’âge et la maturité, l’âge à 50 % de maturité pourrait se rapprocher de 3 *a* pour la morue du Pacifique en Colombie-Britannique (annexe \@ref(app:analysis-of-biological-data)). Une analyse de sensibilité (Sc 5a) a été effectuée pour illustrer l’effet de l’hypothèse que les poissons recrutent et arrivent à maturité à l’âge de 3 *a* :

Une autre analyse de sensibilité (Sc 5b) a été réalisée pour montrer les effets du retour aux paramètres de croissance de von Bertalanffy utilisés dans les évaluations antérieures de la zone 5CD [@forrest2013; @sinclair2005], qui ont également été utilisés par @sinclair2001 dans la dernière évaluation de la zone 3CD. Ces évaluations antérieures des stocks utilisaient les paramètres de von Bertalanffy que @westrheim1996 a indiqués pour la zone 3CD ($L_{inf}$ = 89,48 cm; $K_{VB}$ = 0,307 *a*^1^; et $a_0$ = -0.116 *a*).

La présente évaluation de la zone 5ABCD a utilisé les valeurs des paramètres de croissance des femelles estimées à l’annexe \@ref(app:analysis-of-biological-data) à l’aide des données sur l’âge et la longueur des relevés synoptiques dans le détroit d’Hécate et le bassin de la Reine-Charlotte ($L_{inf}$ = 99,07 cm; $K_{VB}$ = 0,185 *a*^1^; et $a_0$ = -0,832 *a*). La présente évaluation de la zone 3CD a utilisé les valeurs des paramètres de croissance des femelles estimées à l’annexe \@ref(app:analysis-of-biological-data) à l’aide des données sur l’âge et la longueur du relevé synoptique sur la côte ouest de l’île de Vancouver ($L_{inf}$ = 83,29 cm; $K_{VB}$ = 0,266 *a*^1^; et $a_0$ = -0,572 *a*). Pour les deux zones, les nouvelles valeurs du taux de croissance $K_{VB}$ étaient beaucoup plus basses que celles utilisées dans les évaluations précédentes. Le modèle de type différence-délai du scénario 5b a utilisé les paramètres de Ford-Walford $W_{k}$, $\alpha_g$ and $\rho_g$ tirés des paramètres de croissance précédents utilisés dans [@forrest2013; @sinclair2005; @sinclair2001].

En résumé, les deux nouveaux scénarios sont les suivants :

> **Sc 5a. ** Fixer k$ = 3 a$ et mettre à jour le poids au recrutement $W_k$ et les paramètres de Ford-Walford en conséquence.

> **Sc 5b.** Exécuter le modèle en utilisant les paramètres de croissance de von Bertalanffy appliqués dans l’évaluation précédente des stocks [@forrest2013].

Les estimations a posteriori ainsi obtenues de la biomasse, du recrutement et de la mortalité par pêche par rapport aux modèles du scénario de référence sont représentées sur les figures \@ref(fig:fig-sens5-biomass-5abcd) à \@ref(fig:fig-sens5-f-5abcd) pour la zone 5ABCD, et sur les figures \@ref(fig:fig-sens12-biomass-3cd) à \@ref(fig:fig-sens12-f-3cd) pour la zone 3CD. Les figures \@ref(fig:fig-sens5-meanweightfit-5abcd) et \@ref(fig:fig-sens12-meanweightfit-3cd) illustrent la moyenne du poids moyen annuel dans la pêche commerciale pour les scénarios 5a et 5b.

Comme on pouvait s’y attendre, le modèle de la zone 5ABCD était sensible à la fois à l’âge à la sélectivité en lame de couteau et aux paramètres de croissance (figure \@ref(fig:fig-sens5-biomass-5abcd)). Pour le scénario 5a, le modèle a estimé une biomasse beaucoup plus faible, surtout pour la période historique. Cela n’est pas surprenant puisque ce scénario n’inclut pas les poissons de 2 ans. L’ajustement à la moyenne du poids moyen annuel pour le scénario 5a (figure \@ref(fig:fig-sens5-meanweightfit-5abcd) a) était meilleur pour la partie historique de la série chronologique que pour le modèle du scénario de référence, qui avait tendance à être beaucoup moins bien ajusté certaines années (figure \@ref(fig:fig-base-mean-weight-5abcd)). Toutefois, il ne faut pas oublier qu’avant 1996, de nombreuses observations de petits poissons étaient absentes des données commerciales sur la longueur car seuls les poissons débarqués étaient mesurés (annexe \@ref(app:analysis-of-biological-data) et @forrest2013, leur Appendix C). De ce fait, le modèle du scénario de référence actuel estime les poids moyens qui étaient probablement présents dans les prises, mais qui n’ont pas été consignés.

Pour le scénario 5b dans la zone 5ABCD, les estimations de la biomasse étaient inférieures à celles du scénario de référence, particulièrement pour la période historique (figure \@ref(fig:fig-sens5-biomass-5abcd)), avec des pics de biomasse plus bas dans les années 1970 et 1990. Le taux de croissance de von Bertalanffy utilisé par @forrest2013 et @sinclair2005 était plus élevé que celui du modèle du scénario de référence, ce qui dénote un stock plus productif. On pourrait donc expliquer les pics marqués des prises par la diminution de la biomasse dans le scénario 5b, en raison de la plus grande productivité des stocks. Les estimations récentes de la biomasse étaient toutefois plus semblables au scénario de référence (figure \@ref(fig:fig-sens5-biomass-5abcd)). Les ajustements à la moyenne du poids moyen annuel pour le scénario 5b (figure \@ref(fig:fig-sens5-meanweightfit-5abcd) b) étaient semblables à ceux du modèle du scénario de référence (figure \@ref(fig:fig-base-mean-weight-5abcd)).

Pour la zone 3CD, les résultats étaient généralement semblables à ceux de la zone 5ABCD, même si les différences de biomasse entre le scénario de référence et les deux scénarios étaient plus marquées (figure \@ref(fig:fig-sens12-biomass-3cd)). L’ajustement aux données sur la moyenne du poids moyen annuel était très mauvais pour le scénario 5a, et assez semblable au modèle du scénario de référence pour le scénario 5b (figure \@ref(fig:fig-sens12-meanweightfit-3cd)). Comme pour la zone 5ABCD, le taux de croissance utilisé dans le modèle du scénario de référence était inférieur à celui utilisé dans le scénario 5b. Par conséquent, le modèle devait expliquer les prises d’une population moins productive ayant une biomasse historique plus forte.

## SC 6A À 6C. VALEUR FIXE PRÉSUMÉE DE L’ERREUR D’OBSERVATION $\sigma_O$

Le paramètre d’erreur d’observation $\sigma_O$ a été fixé à 0,2 dans les modèles du scénario de référence (section \@ref(sec:fixed-variance-parameters)). Trois analyses de sensibilité ont été effectuées pour examiner les répercussions de la modification de cette valeur :

> **Sc 6a. ** Fixer $\sigma_O$ = 0,10.

> **Sc 6b.** Fixer $\sigma_O$ = 0,15.

> **Sc 6c.** Fixer $\sigma_O$ = 0,25.

Les estimations a posteriori ainsi obtenues de la biomasse, du recrutement et de la mortalité par pêche par rapport aux modèles du scénario de référence sont représentées sur les figures \@ref(fig:fig-sens6-biomass-5abcd) à \@ref(fig:fig-sens6-f-5abcd) pour la zone 5ABCD, et sur les figures \@ref(fig:fig-sens13-biomass-3cd) à \@ref(fig:fig-sens13-f-3cd) pour la zone 3CD.

Comme on s’y attendait, la diminution de la valeur de $\sigma_O$ s’est traduite par des ajustements plus étroits aux indices de l’abondance dans les deux zones (figures \@ref(fig:fig-sens6-index-cpue-post1995-5abcd) et \@ref(fig:fig-sens13-index-triennial-3cd)). Dans la zone 5ABCD, la réduction de $\sigma_O$ a également entraîné une diminution de la biomasse historique estimée, en particulier dans le scénario 6a, même si les estimations récentes de la biomasse étaient semblables entre les scénarios (figure \@ref(fig:fig-sens6-biomass-5abcd)). Dans la zone 3CD, les résultats étaient moins prononcés (figure \@ref(fig:fig-sens13-biomass-3cd)), avec des ajustements des indices plus semblables entre les scénarios (figure \@ref(fig:fig-sens13-index-triennial-3cd)).

Les paramètres de productivité *M* et *h* étaient sensibles aux changements de $\sigma_O$, tout comme les paramètres d’échelle $R_{0}$ et les paramètres de capturabilité \textit{q} (tableaux \@ref(tab:tab-param-table-sens6a-5abcd) à \@ref(tab:tab-param-table-sens6c-5abcd) pour la zone 5ABCD et tableaux \@ref(tab:tab-param-table-sens6a-3cd) à \@ref(tab:tab-param-table-sens6c-3cd) pour la zone 3CD).

## SC 6C. VALEUR FIXE PRÉSUMÉE DE L’ERREUR DE TRAITEMENT $\sigma_R$

Le paramètre d’erreur de traitement $\sigma_R$ a été fixé à 0,8 dans les modèles du scénario de référence (section \@ref(sec:fixed-variance-parameters)) car ce stock semble avoir connu un recrutement très variable depuis le début de la pêche. Une analyse de sensibilité a été réalisée pour vérifier l’effet de l’augmentation de la valeur présumée de $\sigma_R$ :

> **Sc 6d.** Fixer $\sigma_R$ = 1,0.

Il y avait très peu de différences perceptibles dans l’estimation de la biomasse, du recrutement et de la mortalité par pêche entre le modèle du scénario de référence et le scénario 6d (figures \@ref(fig:fig-sens6-biomass-5abcd) à \@ref(fig:fig-sens6-f-5abcd) pour la zone 5ABCD et figures \@ref(fig:fig-sens13-biomass-3cd) à \@ref(fig:fig-sens13-f-3cd) pour la zone 3CD).

## SC 7A. VALEUR FIXE PRÉSUMÉE DE $\sigma_W$

Compte tenu des incertitudes liées à l’interprétation de la série chronologique du poids moyen (voir la section \@ref(sec:reference-case-models)) et à sa capacité de fournir des renseignements directs pour la mise à l’échelle de l’effectif de la population, deux analyses de sensibilité ont été effectuées pour illustrer l’effet de la valeur fixe de $\sigma_W$ :

> **Sc 7a. ** Fixer $\sigma_W$ = 0,4.

> **Sc 7b.** Fixer $\sigma_W$ = 0,15.

Les estimations a posteriori ainsi obtenues de la biomasse, du recrutement et de la mortalité par pêche par rapport aux modèles du scénario de référence sont représentées sur les figures \@ref(fig:fig-sens7-biomass-5abcd) à \@ref(fig:fig-sens7-f-5abcd) pour la zone 5ABCD, et sur les figures \@ref(fig:fig-sens14-biomass-3cd) à \@ref(fig:fig-sens14-f-3cd) pour la zone 3CD.

L’augmentation de $\sigma_W$ dans le scénario 7a a entraîné une réduction importante de la biomasse estimée dans les deux zones (figures \@ref(fig:fig-sens7-biomass-5abcd) et \@ref(fig:fig-sens14-biomass-3cd)), mais des ajustements très mauvais aux données sur la moyenne du poids moyen annuel (figures \@ref(fig:fig-sens7-meanweightfit-5abcd) a et \@ref(fig:fig-sens14-meanweightfit-3cd) a). La diminution de $\sigma_w$ dans le scénario 7b n’a pas eu d’effet notable sur la biomasse prévue (figures \@ref(fig:fig-sens7-biomass-5abcd) et \@ref(fig:fig-sens14-biomass-3cd)) ou sur les ajustements aux données sur le poids moyen (figures \@ref(fig:fig-sens7-meanweightfit-5abcd) b et \@ref(fig:fig-sens14-meanweightfit-3cd) b).

## SC 7C. INFLUENCE DU POIDS MOYEN ANNUEL HISTORIQUE DANS LES PRISES COMMERCIALES
On sait que les données sur le poids moyen annuel étaient biaisées avant 1996 en raison du manque d’échantillons de poissons rejetés en mer. Pour les deux stocks, on a procédé à une analyse de sensibilité en retirant les données sur le poids moyen annuel antérieures à 1996, afin d’illustrer leur influence sur le modèle.

> **Sc 7c.** Retirer les données sur le poids moyen annuel observé avant 1996.

## SC 8A et 8B. EFFET DE L’HYPOTHÈSE DES PRISES HISTORIQUES PARFAITEMENT CONNUES
Pour chaque stock, deux analyses de sensibilité ont été effectuées, dans lesquelles les données sur les prises commerciales d’avant 1996 ont été gonflées d’une quantité fixe. Cela visait principalement à encadrer l’incertitude du modèle attribuable à l’incertitude entourant les rejets historiques et, dans une moindre mesure, les prises étrangères au début de la série chronologique. Ces scénarios ne cherchent pas à représenter des estimations réelles des rejets historiques, qui sont recommandées à titre d’important domaine pour les recherches futures.

> **Sc 8a. ** Gonfler les prises d’avant 1996 de 25 %.

> **Sc 8b.** Gonfler les prises d’avant 1996 de 50 %.


\clearpage

# PROJECTIONS ET TABLEAUX DE DÉCISION {#sec:projections-and-decision-tables}

Les mesures du rendement ont été calculées sur une séquence de niveaux de prises projetés de rechange pour 2018 et sont fondées sur une projection d’un an jusqu’en 2019 (figures \@ref(fig:fig-base-biomass-5abcd-proj) et \@ref(fig:fig-base-biomass-3cd-proj)). L’incertitude entre dans les projections par des anomalies du recrutement pour l’année de projection, qui ont été tirées au hasard à partir d’une distribution normale, $\mathcal{N}(0,\sigma_R^2)$. Les mesures du rendement suivantes ont été évaluées :

1. $P(B_{2019} < B_{2018})$
1. $P(F_{2018} > F_{2017})$
1. $P(B_{2019} < LRP)$
1. $P(B_{2019} < USR)$
1. $P(F_{2018} > LRR)$

où

1. $USR$ (point de référence supérieur du stock) est la moyenne historique des estimations de la biomasse de 1956 à 2004 (les deux zones).
1. $LRP$ (point de référence limite) est la biomasse estimée la plus basse reconnue comme constituant un état indésirable à éviter. Pour la zone 5ABCD, il s’agit de l’estimation de la biomasse pour 2000. Pour la zone 3CD, il s’agit de l’estimation de la biomasse pour 1986.
1. $LRR$ (taux d’exploitation de référence limite) est le taux moyen de mortalité par pêche de 1956 à 2004 (les deux zones).

Pour de plus amples renseignements sur les points de référence, voir la section \@ref(sec:reference-points).

Les mesures du rendement susmentionnées visent à présenter les probabilités d’atteindre les états « indésirables » selon les niveaux de prises de rechange projetés pour 2018. Par exemple, on obtient une mesure du rendement fondée sur la biomasse « indésirable » lorsque la biomasse projetée pour 2019 est inférieure au PRL, c.-à-d. que $B_{2019}/LRP < 1$. On obtient une mesure du rendement fondée sur la mortalité par pêche « indésirable » lorsque la mortalité par pêche de 2014 projetée est supérieure au point de référence, c.-à-d. que $F_{2018}/LRR > 1$.

Les probabilités de ces états sont mesurées comme la proportion d’échantillons a posteriori du rodage qui répondent aux critères ci-avant (proportion d’échantillons a posteriori < 1 pour les mesures du rendement fondées sur la biomasse; proportion d’échantillons a posteriori > 1 pour les mesures du rendement fondées sur la mortalité par pêche).

@forrest2013 ont utilisé une approche de calcul de la moyenne des modèles pour préparer des tableaux de décision fondés sur des échantillons a posteriori combinés provenant de cas présentant différentes sensibilités. Ils cherchaient ainsi à résoudre certaines des principales incertitudes insolubles associées à l’évaluation des stocks. Une approche semblable a été utilisée dans l’évaluation de 2011 du merlu du Pacifique [@stewart2011], où deux autres modèles d’évaluation des stocks ont été jugés tout aussi possibles par le Comité scientifique et statistique du Pacific Fishery Management Council. Une approche « d’ensemble » semblable est appliquée dans les évaluations annuelles du flétan du Pacifique, pour lesquelles quatre modèles structurellement distincts sont utilisés [@stewart2016].

Dans les sections qui suivent, nous présentons les tableaux de décision du scénario de référence pour chaque zone, puis les tableaux de décision de rechange « fondés sur la moyenne des modèles » qui intègrent l’incertitude des modèles du scénario de référence (section \@ref(sec:reference-case-models)) et un sous-ensemble des cas de sensibilité ci-avant (section \@ref(sec:sensitivity-analyses)). Les détails de l’approche de calcul de la moyenne pour les zones 5ABCD et 3CD sont donnés ci-après.

Nous n’avons pas tenté d’attribuer des pondérations différentes aux modèles de rechange pour préparer les résultats fondés sur la moyenne des modèles.

## TABLEAUX DE DÉCISION DU SCÉNARIO DE RÉFÉRENCE

### Zone 5ABCD

Le tableau de décision pour le modèle du scénario de référence de la zone 5ABCD est fourni dans le tableau \@ref(tab:tab-decision-avg-5abcd). Des projections ont été établies pour une fourchette de niveaux de prises de 2018 allant de `r dt.5abcd.min.catch` tonnes métriques (t) à 3 000 t, soit environ trois fois le TAC combiné actuel de la zone 5ABCDE, qui est de 950 t (tableau \@ref(tab:tab-tac)).

La probabilité que la biomasse de 2019 soit inférieure à celle de 2018 variait de `r dt.5abcd.b.2019.2018.c0` % pour des prises nulles en 2018 à `r dt.5abcd.b.2019.2018.cmax` % pour des prises de `r dt.5abcd.max.catch` t.

La probabilité que la biomasse de 2019 soit inférieure au PRL allait de `r dt.5abcd.b.2019.lrp.c0` % à `r dt.5abcd.b.2019.lrp.cmax` % pour la fourchette des niveaux de prises considérés. Il y avait une probabilité de `r dt.5abcd.b.2019.usr.cmax` % que la biomasse de 2019 soit inférieure au PRS pour toute la fourchette des niveaux de prises considérés.

La probabilité que la mortalité par pêche en 2018 soit supérieure à la mortalité par pêche en 2017 variait de `r dt.5abcd.f.2018.2017.c0` % à `r dt.5abcd.f.2018.2017.cmax` %. La probabilité que la mortalité par pêche en 2018 soit supérieure au TEL variait également de 0 % à 100 %.

Pour un niveau de prises de 900 t en 2018, proche du TAC de 2017, il y a une probabilité estimée de `r dt.5abcd.b.2019.lrp.c900` % que la biomasse de 2019 sera inférieure au PRL et une probabilité de `r dt.5abcd.b.2019.usr.c900` % que la biomasse de 2019 sera inférieure au PRS.

### Zone 3CD

Le tableau de décision pour le modèle du scénario de référence de la zone 3CD est fourni dans le tableau \@ref(tab:tab-decision-avg-3cd). Des projections ont été faites pour une fourchette de niveaux de prises de 2018 allant de `r dt.3cd.min.catch` à 1 500 t, soit environ trois fois le TAC actuel de 500 t (tableau \@ref(tab:tab-tac)).

La probabilité que la biomasse de 2019 soit inférieure à celle de 2018 variait de `r dt.3cd.b.2019.2018.c0` % pour des prises nulles en 2018 à `r dt.3cd.b.2019.2018.cmax` % pour des prises de `r dt.3cd.max.catch` t.

La probabilité que la biomasse de 2019 soit inférieure au PRL était de 0% pour la fourchette des niveaux de prises considérés. Il y avait une probabilité de 98 % à 99 % que la biomasse de 2019 soit inférieure au PRS pour la fourchette des niveaux de prises considérés.

La probabilité que la mortalité par pêche en 2018 soit supérieure à la mortalité par pêche en 2017 variait de `r dt.3cd.f.2018.2017.c0` % à 100 %. La probabilité que la mortalité par pêche en 2018 soit supérieure au TEL variait également de `r dt.3cd.f.2018.lrr.c0` % à 100 %.

Pour un niveau de prises de 500 t en 2018, proche du TAC de 2017, il y a une probabilité estimée de `r dt.3cd.b.2019.lrp.c500` % que la biomasse de 2019 sera inférieure au PRL et une probabilité de `r dt.3cd.b.2019.usr.c500` % que la biomasse de 2019 sera inférieure au PRS.

## TABLEAUX DE DÉCISION FONDÉS SUR LA MOYENNE DES MODÈLES

Nous avons choisi quatre scénarios de sensibilité (plus le scénario de référence) à inclure dans un tableau de décision fondé sur la moyenne des modèles pour chaque zone. Les scénarios de sensibilité ci-après ont été choisis parce qu’ils ont produit des résultats possibles qui divergeaient des modèles du scénario de référence. L’inclusion de ces échantillons a posteriori dans le tableau de décision pourrait donc mieux circonscrire l’incertitude en raison des différentes hypothèses reflétées dans les scénarios de sensibilité. Toutefois, veuillez noter que les choix des scénarios de sensibilité inclus dans les tableaux fondés sur la moyenne des modèles devraient être considérés comme des éléments à discuter et convenir à la prochaine réunion régionale d’examen par les pairs.

Les vecteurs de 1 000 échantillons a posteriori retirés par le rodage dans chacun des cinq modèles, pour chaque mesure du rendement, sous chaque niveau des prises de rechange de 2018, ont été combinés en un seul vecteur de 5 000 échantillons et les probabilités de mesures du rendement ont été calculées à partir des échantillons combinés.

### Zone 5ABCD

Pour la zone 5ABCD, nous présentons un tableau de décision de rechange avec les probabilités calculées à partir des estimations a posteriori combinées des mesures du rendement des cinq modèles suivants :

1. Le scénario de référence;
2. Le scénario de sensibilité sans les données sur les CPUE commerciales (Sc 1f);
3. Le scénario de sensibilité avec la valeur a priori pour le bassin de la Reine-Charlotte de $q$ : moyenne de $\ln(q)$ = $\ln(0,1869 \cdot 0,65)$ (Sc 2a);
4. Le scénario de sensibilité avec la valeur a priori de ln($M$) : $\mathcal{N}\sim(0.4,0.1)$ (Sc 3b);
5. Le scénario de sensibilité avec $\sigma_0 = 0,15$ (Sc 6b).

Les probabilités du tableau de décision « fondé sur la moyenne des modèles » pour les zones 5ABCD sont présentées dans le tableau \@ref(tab:tab-decision-avg-5abcd).

La probabilité que la biomasse de 2019 soit inférieure à celle de 2018 variait de 10 % pour des prises nulles en 2018 à 89 % pour des prises de 3 000 t.

La probabilité que la biomasse de 2019 soit inférieure au PRL variait de 82 à 96% pour la fourchette des niveaux de prises considérés. Il y avait une probabilité de 100 % que la biomasse de 2019 soit inférieure au PRS pour toute la fourchette des niveaux de prises considérés.

La probabilité que la mortalité par pêche en 2018 soit supérieure à la mortalité par pêche en 2017 variait de 0,0 % à 100 %. La probabilité que la mortalité par pêche en 2018 soit supérieure au TEL variait également de 0,0 % à 100 %.

Pour un niveau de prises de 900 t en 2018, proche du TAC de 2017, il y a une probabilité estimée de 89 % que la biomasse de 2019 sera inférieure au PRL et une probabilité de 100 % que la biomasse de 2019 sera inférieure au PRS.

### Zone 3CD

Pour la zone 3CD, nous présentons un tableau de décision de rechange avec les probabilités calculées à partir des estimations a posteriori combinées des mesures du rendement des cinq modèles suivants :

1. Le scénario de référence;
2. Le scénario de sensibilité sans les données sur les CPUE commerciales (Sc 1f);
3. Le scénario de sensibilité avec l’ET de la valeur a priori pour le relevé synoptique sur la COIV = 0,448 (Sc 2a);
4. Le scénario de sensibilité avec la valeur a priori de ln($M$) : $\mathcal{N}\sim(0.4,0.1)$ (Sc 3b);
5. Le scénario de sensibilité avec $\sigma_0 = 0,15$ (Sc 6b).

Les probabilités du tableau de décision « fondé sur la moyenne des modèles » pour les zones 3CD sont présentées dans le tableau \@ref(tab:tab-decision-avg-3cd).

Pour la plupart des mesures du rendement, les probabilités étaient semblables à celles du modèle du scénario de référence.

La probabilité que la biomasse de 2019 soit inférieure à celle de 2018 variait de 75 % pour des prises nulles en 2018 à 91 % pour des prises de 1 500 t.

La probabilité que la biomasse de 2019 soit inférieure au PRL était de 18 % pour la fourchette des niveaux de prises considérés. La probabilité que la biomasse de 2019 soit inférieure au PRS variait de 98 à 99 % pour la fourchette des niveaux de prises considérés.

La probabilité que la mortalité par pêche en 2018 soit supérieure à la mortalité par pêche en 2017 variait de 0 % à 100 % pour la fourchette des niveaux de prises considérés. La probabilité que la mortalité par pêche en 2018 soit supérieure au TEL variait également de 0,0 % à 98 %.

Pour un niveau de prises de 500 t en 2018, proche du TAC de 2017, il y a une probabilité estimée de 18 % que la biomasse de 2019 sera inférieure au PRL et une probabilité de 99 % que la biomasse de 2019 sera inférieure au PRS.

## SOMMAIRE

Nous avons présenté les autres tableaux de décision fondés sur la moyenne des modèles pour les zones 5ABCD et 3CD dans le but d’intégrer de façon plus exhaustive l’incertitude structurelle importante des évaluations dans les avis communiqués aux gestionnaires des pêches et aux intervenants. Toutefois, nous insistons sur les importantes incertitudes structurelles que nous n’avons pas été en mesure d’aborder dans cette évaluation, notamment :

1. Les effets de l’hypothèse d’une sélectivité constante dans la pêche au chalut;
1. L’effet de l’hypothèse selon laquelle le recrutement dans la pêche, les relevés et la biomasse féconde sont en lame de couteau à l’âge de 2 ans;
1. L’incidence de l’incertitude entourant la structure des stocks sur la compréhension des tendances de l’abondance;
1. L’incidence de l’incertitude entourant l’ampleur des rejets et prises étrangères historiques;
1. L’incidence du changement du niveau de présence des observateurs à bord et de la représentativité des échantillons de longueur provenant des prises commerciales.

L’incertitude est donc sous-représentée dans cette évaluation.

# REMERCIEMENTS

Nous remercions Elise Keppel (Station biologique du Pacifique), qui a reconstitué les données historiques sur les captures commerciales par unité d’effort. Son travail à l’égard de cet important ensemble de données pour la présente évaluation a permis de disposer d’une analyse entièrement reproductible et sera utile pour les évaluations futures d’autres stocks. De façon plus générale, son aide avec le progiciel gfplot R et ses requêtes SQL soigneusement construites ont grandement facilité l’extraction des données pour cette évaluation. Nous remercions Norm Olsen pour ses conseils sur la reconstruction historique des captures commerciales par unité d’effort. Nous remercions également Greg Workman et Maria Surry (Station biologique du Pacifique) pour leur soutien et leurs conseils lors de la préparation de cette évaluation. Nous remercions Bruce Turris et Brian Mose (Canadian Groundfish Research and Conservation Society) pour les conseils qu’ils ont donnés aux auteurs.

\clearpage
